// shashi/student-task/vuejs/src/components/AddTeacher.vue
<!-- eslint-disable prettier/prettier -->
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="teachername">Teacher name</label>
        <input
          type="text"
          class="form-control"
          id="teachername"
          required
          v-model="teacher.teachername"
          name="teachername"
        />
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <textarea
          class="form-control"
          id="address"
          required
          v-model="teacher.address"
          name="address"
          placeholder="address"
        ></textarea>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          required
          v-model="teacher.email"
          name="email"
        />
      </div>
      <div class="form-group">
        <label for="gender">Gender</label>
        <input
          type="text"
          class="form-control"
          id="gender"
          required
          v-model="teacher.gender"
          name="gender"
        />
      </div>
      <label for="gender">Select Gender</label>      
      <div class="form-group">
  <input type="radio" id="Male" value="Male" v-model="teacher.gender">
  <label for="Male">Male</label><br>
  <input type="radio" id="Female" value="Female" v-model="teacher.gender">
  <label for="Female">Female</label><br>
  <input type="radio" id="Others" value="Others" v-model="teacher.gender">
  <label for="Female">Others</label><br>
   </div>
      <label>schoolsList:</label>
      <div class="form-check" v-for="(entry, index) in schoolList" :key="index">
        <input
          type="checkbox"
          class="form-check-input"
          @click="selectedSchoolMethod(entry)"
        />{{ entry.schoolname }}
      </div>
      <button @click="saveTeacher" class="btn btn-success">Submit</button>
    </div>
    <div v-else>
      <h4>You submitted successfully!</h4>
      <button class="btn btn-success" @click="newTutorial">Add</button>
    </div>
    <router-link 
          :to="'/teacherslist'"
          class="badge badge-warning"
          custom
      v-slot="{ navigate }"
          > <button  
          class="btn btn-danger" 
          @click="navigate"  
        role="link"
        >Cancel</button>
      </router-link
        >  
  </div>
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import studentservice from "@/services/studentservice";
import { Teacher } from "@/types/teacher";
import School from "@/types/school";
export default defineComponent({
  name: "add-teacher",  
  data() {
    return {
      teacher: {
        teachername: "",
        address: "",
        email: "",
        gender: "",
      } as Teacher,
      schoolList: [] as School[],
      submitted: false,
      currentSchool: {} as School,
      selectedSchools: [] as School[],
      genderList: [
        { value: "male", label: "Male" },
        { value: "female", label: "Female" },
      ],
  
    };
  },
  methods: {
    saveTeacher() {
      let data = {
        teachername: this.teacher.teachername,
        address: this.teacher.address,
        email: this.teacher.email,
        gender: this.teacher.gender,
        school: this.selectedSchools,
      };
      studentservice
        .createTeacher(data)              
          this.submitted = true;    
    },
    selectedSchoolMethod(school: School) {
      this.currentSchool = school;
      this.selectedSchools?.push(this.currentSchool);
    },
    retrieveSchools() {
      studentservice
        .getAllSchool()
        .then((response) => {
          this.schoolList = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    newTutorial() {
      this.submitted = false;
      this.teacher = {} as Teacher;
    },
  },
  mounted() {
    this.retrieveSchools();
  },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style>
.submit-form {
  max-width: 300px;
  margin: auto;
}
.body {
  padding: 1rem;
}
</style>

// harsha/School-Teacher-Student/client-ReactJS/src/components/add-teacher.component.tsx
import { ChangeEvent, Component } from "react";
import SchoolService from "../services/school.service";
import TeacherService from "../services/teacher.service";
import { Link } from "react-router-dom";
import { Teacher } from "../types/teacher.type";

type Props = {};

type State = Teacher & {
  submitted: boolean;
};

export default class AddTeacher extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.onChangeGender = this.onChangeGender.bind(this);
    this.onChangeEmail = this.onChangeEmail.bind(this);
    this.onChangePhoneNo = this.onChangePhoneNo.bind(this);
    this.onChangeSchools = this.onChangeSchools.bind(this);
    this.saveTeacher = this.saveTeacher.bind(this);

    this.state = {
      teacherName: "",
      address: "",
      gender: "",
      email: "",
      phoneNo: 0,
      schools: [],
      submitted: false,
    };
  }

  componentDidMount() {
    this.retrieveSchools();
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      teacherName: e.target.value,
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      address: e.target.value,
    });
  }

  onChangeGender(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      gender: e.target.value,
    });
  }

  onChangeEmail(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      email: e.target.value,
    });
  }

  onChangePhoneNo(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      phoneNo: e.target.valueAsNumber,
    });
  }

  onChangeSchools(event: any) {
    this.setState({
      schools: event.target.value,
    });
  }

  retrieveSchools() {
    SchoolService.getSchools()
      .then((response: any) => {
        this.setState({
          schools: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  saveTeacher() {
    const teacher: Teacher = {
      teacherName: this.state.teacherName,
      address: this.state.address,
      email: this.state.email,
      gender: this.state.gender,
      schools: this.state.schools,
    };

    TeacherService.create(teacher)
      .then((response: any) => {
        this.setState({
          teacherId: response.data.teacherId,
          teacherName: response.data.teacherName,
          address: response.data.address,
          email: response.state.email,
          gender: response.state.gender,
          schools: response.data.schools,
          submitted: true,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { teacherName, address, gender, email, phoneNo } = this.state;

    return (
      <div className="submit-form">
        <h2>ADD TEACHER</h2>
        <form>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={teacherName}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>

          <div className="form-group">
            <label htmlFor="gender">Gender</label>
            <input
              type="text"
              className="form-control"
              id="gender"
              required
              value={gender}
              onChange={this.onChangeGender}
              name="gender"
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              type="text"
              className="form-control"
              id="email"
              required
              value={email}
              onChange={this.onChangeEmail}
              name="email"
            />
          </div>

          <div className="form-group">
            <label htmlFor="phoneNo">Phone No</label>
            <input
              type="text"
              className="form-control"
              id="phoneNo"
              required
              value={phoneNo}
              onChange={this.onChangePhoneNo}
              name="phoneNo"
            />
          </div>

          <div className="form-group">
            <label htmlFor="schools">Schools</label>
            <input
              type="checkbox"
              name="schools"
              className="form-control"
              value="schools"
            />
          </div>

          <button
            onClick={this.saveTeacher}
            type="button"
            className="btn btn-success"
          >
            Submit
          </button>
          <Link to="/teachers">
            <button type="button" className="btn btn-warning">
              Cancel
            </button>
          </Link>
        </form>
      </div>
    );
  }
}
