// adarsh/school/VUE-client/src/components/AddSchool.vue
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="title">Name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          required
          v-model="school.name"
          name="name"
        />
      </div>

      <div class="form-group">
        <label for="description">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="school.address"
          name="address"
        />
        <br />
      </div>
      <div class="form-group">
        <label for="teacher">Teachers</label>
        <div class="control_wrapper">
          <ejs-multiselect
            id="multiselect"
            :dataSource="this.teachers"
            :fields="fields"
            placeholder="'Select Teachers'"
            @change="onSelectedTeacher(this.teachers)"
          ></ejs-multiselect>
        </div>
        <br />
      </div>
      <div class="form-group">
        <label for="description">Student</label>
        <div class="control_wrapper">
          <ejs-multiselect
            id="multiselect"
            :dataSource="this.students"
            :fields="fields"
            placeholder="'Select Students'"
          ></ejs-multiselect>
        </div>
      </div>
      <br />
      <button @click="saveSchool" class="btn btn-success">Submit</button>
      <button @click="onCancle" class="btn btn-danger">cancle</button>
    </div>

    <div v-else>
      <h4>You submitted successfully!</h4>
      <button class="btn btn-success" @click="newTutorial">Add</button>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { School } from "@/types/school";
import { MultiSelectPlugin } from "@syncfusion/ej2-vue-dropdowns";
import SchoolService from "@/services/SchoolService";
import { Student } from "@/types/student";
import { Teacher } from "@/types/teacher";
import App from "@/App.vue";
Vue.use(MultiSelectPlugin);

@Component
export default class AddSchool extends Vue {
  students: Student[] = [];
  private school: School = {
    name: "",
    address: "",
    teachers: [],
    students: [],
  };
  components!: {
    App:"ejs-multiselect";
  };
  teachers: Teacher[] = [];
  slectedStudent: Student[] = [];
  studentSelected: Student = new Student();
  slectedTeacher: Teacher[] = [];
  teacherSelected: Teacher = new Teacher();

  data() {
    return {
      fields: { text: "name", value: "id" },
      index: 2,
    };
  }

  private submitted: boolean = false;
  schools: School[] = [];

  retrieveStudent() {
    SchoolService.getAllStudents()
      .then((response) => {
        this.students = response.data;
        console.log(response.data);
      })
      .catch((e) => {
        console.log(e);
      });
  }
  retrieveTeachers() {
    SchoolService.getAllTeachers()
      .then((response) => {
        this.teachers = response.data;
      })
      .catch((e) => {});
  }
  saveSchool() {
    let data = {
      name: this.school.name,
      address: this.school.address,
    };

    SchoolService.createSchool(data)
      .then((response) => {
        this.school = response.data;
        this.submitted = true;
      })
      .catch((e) => {});
  }

  onCancle() {
    this.$router.replace("/school");
  }

  mounted() {
    this.retrieveStudent();
    this.retrieveTeachers();
  }
  onSelectedStudent(student: Student) {
    this.studentSelected = student;
    this.slectedStudent.push(this.studentSelected);
  }
  onSelectedTeacher(teacher: Teacher) {
    this.teacherSelected = teacher;
    this.slectedTeacher.push(this.teacherSelected);
  }
}
</script>

<style scoped>
.submit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// harsha/School-Teacher-Student/client-ReactJS/src/components/add-school.component.tsx
import { ChangeEvent, Component } from "react";
import SchoolService from "../services/school.service";
import TeacherService from "../services/teacher.service";
import StudentService from "../services/student.service";
import { Link, RouteComponentProps } from "react-router-dom";
import { School } from "../types/school.type";
import Multiselect from "multiselect-react-dropdown";

interface RouterProps {}

type Props = RouteComponentProps<RouterProps>;

type State = School & {
  submitted: boolean;
};

export default class AddSchool extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.saveSchool = this.saveSchool.bind(this);

    this.state = {
      schoolName: "",
      address: "",
      submitted: false,
    };
  }

  componentDidMount() {
    this.retrieveTeachers();
    this.retrieveStudents();
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      schoolName: e.target.value,
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      address: e.target.value,
    });
  }

  retrieveTeachers() {
    TeacherService.getTeachers()
      .then((response: any) => {
        this.setState({
          teachers: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  retrieveStudents() {
    StudentService.getStudents()
      .then((response: any) => {
        this.setState({
          students: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  saveSchool() {
    const school: School = {
      schoolName: this.state.schoolName,
      address: this.state.address,
    };

    SchoolService.create(school)
      .then((response: any) => {
        this.setState({
          schoolId: response.data.schoolId,
          schoolName: response.data.schoolName,
          address: response.data.address,
          submitted: true,
        });
        this.props.history.push("/schools");
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { schoolName, address, teachers, students } = this.state;

    return (
      <div className="submit-form">
        <h2>ADD SCHOOL</h2>
        <form>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={schoolName}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>

          <div className="form-group">
            <Multiselect
              options={teachers}
              closeIcon="close"
              placeholder="Choose Teachers"
              displayValue="teacherName"
            />
          </div>

          <div className="form-group">
            <Multiselect
              options={students}
              closeIcon="close"
              placeholder="Choose Students"
              displayValue="studentName"
            />
          </div>

          <button
            onClick={this.saveSchool}
            type="button"
            className="btn btn-success"
          >
            Submit
          </button>
          <Link to="/schools">
            <button type="button" className="btn btn-warning">
              Cancel
            </button>
          </Link>
        </form>
      </div>
    );
  }
}
