// shashi/student-task/vuejs/src/components/StudentList.vue
<!-- eslint-disable vue/no-parsing-error -->
<!-- eslint-disable prettier/prettier -->
<template>
    <div class="list row">
      <div class="col-md-8"></div>
      <div class="col-md-6">
        <h4>students List</h4>
        <div class="searchBar">
          <div class="input-group mb-5">
            <input
              type="search"
              class="form-control"           
              placeholder="Student's Name"
              aria-label="Recipient's username"
              aria-describedby="button-addon2"
            />
          </div>
        </div>
        <table id="schools-list" class="table table-bordered table-striped">
          <thead>
            <tr>
              <!-- loop through each value of the fields to get the table header -->
              <th v-for="field in fields" :key="field">
                {{ field }}
                <i class="bi bi-sort-alpha-down" aria-label="Sort Icon"></i>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(entry, index) in studentData" :key="index">             
              <td>{{ entry.studentname }}</td>
              <td>{{ entry.email }}</td>
              <td>{{ entry.dob }}</td>
              <router-link 
          :to="'/student/' + entry.studentid"
          class="badge badge-warning"
          custom
      v-slot="{ navigate }"
          > <button  
          class="badge badge-success mr-2" 
          @click="navigate"  
        role="link"
        >EDIT</button>
      </router-link
        >
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </template>
  
  <script lang="ts">
  /* eslint-disable */
  
  import { computed, ref } from "vue";
  import { defineComponent } from "vue";
  import studentservice from "@/services/studentservice";
  import ResponseData from "@/types/ResponseData"; 
  import { Student } from "@/types/student";
  import type { Header, Item } from "vue3-easy-data-table";
  
  export default defineComponent({
    name: "students-list",
    data() {
      return {        
        studentData: [] as Student[],
        studentname: "",
      };
    },
    methods: {
      retrieveStudents() {
        studentservice
          .getAllStudents()
          .then((response: ResponseData) => {
            this.studentData = response.data;
            console.log(response.data);
          })
          .catch((e: Error) => {
            console.log(e);
          });
      },
      searchTitle() {
        studentservice
          .findByTitle(this.studentname)
          .then((response: ResponseData) => {
            this.studentData = response.data;
            console.log(response.data);
          })
          .catch((e: Error) => {
            console.log(e);
          });
      },
    },
    mounted() {
      this.retrieveStudents();
    },
    setup() {
      const fields = ["STUDENT_NAME", "E-MAIL", "DATE_OF_BIRTH","ACTIONS"];
      return { fields };
    },
  });
  </script>
  <style>
  .list {
    text-align: left;
    max-width: 750px;
    margin: auto;
  }
  .table th:hover {
    background: #f2f2f2;
    width: 100px;
  }
  </style>

// harsha/School-Teacher-Student/client-ReactJS/src/components/student-list.component.tsx
import { Component } from "react";
import StudentService from "../services/student.service";
import { Link } from "react-router-dom";
import { Student } from "../types/student.type";

type Props = {};

type State = {
  students: Array<Student>;
};

export default class StudentsList extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.retrieveStudents = this.retrieveStudents.bind(this);

    this.state = {
      students: [],
    };
  }

  componentDidMount() {
    this.retrieveStudents();
  }

  retrieveStudents() {
    StudentService.getStudents()
      .then((response: any) => {
        this.setState({
          students: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { students } = this.state;

    return (
      <>
        <div>
          <Link to={"/add-student"}>
            <button type="button" className="btn btn-success">
              Add Student
            </button>
          </Link>
        </div>
        <h4>Students List</h4>
        <div className="list row">
          <div className="col-md-6">
            <table className="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Address</th>
                  <th>Gender</th>
                  <th>DOB</th>
                  <th>Email</th>
                  <th>Created Date</th>
                  <th>Phone No</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {students.map((student: Student) => {
                  return (
                    <tr key={student.studentId}>
                      <td>{student.studentId}</td>
                      <td>{student.studentName}</td>
                      <td>{student.address}</td>
                      <td>{student.gender}</td>
                      <td>{student.dateOfBirth}</td>
                      <td>{student.email}</td>
                      <td>{student.createdDate}</td>
                      <td>{student.phoneNo}</td>
                      <td>
                        {
                          <Link to={"/edit-student"}>
                            <button type="button" className="btn btn-primary">
                              Edit
                            </button>
                          </Link>
                        }
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </>
    );
  }
}
