// harsha/School-Teacher-Student/client-ReactJS/src/components/student/add-student.component.tsx
import { ChangeEvent, Component } from "react";
import { Link, RouteComponentProps } from "react-router-dom";
import { Student } from "../../types/student.type";
import SchoolService from "../../services/school.service";
import StudentService from "../../services/student.service";
import { School } from "../../types/school.type";

interface RouterProps {}

type Props = RouteComponentProps<RouterProps>;

type State = Student & {
  schools: Array<School>;
  submitted: boolean;
};

const genders = [{ value: "Male" }, { value: "Female" }];

export default class AddStudent extends Component<Props, State> {
  currentSchool: School={};
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.onChangeGender = this.onChangeGender.bind(this);
    this.onChangeEmail = this.onChangeEmail.bind(this);
    this.onChangeDateOfBirth = this.onChangeDateOfBirth.bind(this);
    this.onChangePhoneNo = this.onChangePhoneNo.bind(this);
    this.onChangeSchool = this.onChangeSchool.bind(this);
    this.saveStudent = this.saveStudent.bind(this);

    this.state = {
      studentName: "",
      address: "",
      gender: "",
      email: "",
      dateOfBirth: "",
      school: {
        schoolName: "",
      },
      schools: [],
      submitted: false,
    };
  }

  componentDidMount() {
    this.retrieveSchools();
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      studentName: e.target.value,
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      address: e.target.value,
    });
  }

  onChangeGender(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      gender: e.target.value,
    });
  }

  onChangeEmail(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      email: e.target.value,
    });
  }

  onChangeDateOfBirth(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      dateOfBirth: e.target.value,
    });
  }

  onChangePhoneNo(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      phoneNo: e.target.valueAsNumber,
    });
  }

  onChangeSchool(school: School) {
    this.setState({
      school:school ,
    });
  }

  onSchoolSelect(event: any) {
    const schoolData = this.state.schools.filter((school) => school.schoolName === event.target.value);
    this.currentSchool = schoolData[0];
    console.log(schoolData);
    this.setState({
      school: this.currentSchool,
    });
  }

  retrieveSchools() {
    SchoolService.getSchools()
      .then((response: any) => {
        this.setState({
          schools: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  saveStudent() {
    const student: Student = {
      studentName: this.state.studentName,
      address: this.state.address,
      email: this.state.email,
      gender: this.state.gender,
      dateOfBirth: this.state.dateOfBirth,
      phoneNo: this.state.phoneNo,
      school: this.state.school,
    };

    StudentService.create(student)
      .then((response: any) => {
        this.setState({
          studentId: response.data.studentId,
          studentName: response.data.studentName,
          address: response.data.address,
          email: response.state.email,
          gender: response.state.gender,
          dateOfBirth: response.state.dateOfBirth,
          phoneNo: response.state.phoneNo,
          school: response.data.school,
          submitted: true,
        });
        this.props.history.push("/students");
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { studentName, address, email, dateOfBirth, phoneNo, schools } =
      this.state;

    return (
      <div className="submit-form">
        <h2>ADD STUDENT</h2>
        <form>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={studentName}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>

          <div className="form-group">Select a Gender</div>
          {genders.map((gender, i) => (
            <label key={i}>
              <input
                type="radio"
                name="gender"
                value={gender.value}
                onChange={this.onChangeGender}
              />{" "}
              {gender.value}
            </label>
          ))}
          <br />

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              type="text"
              className="form-control"
              id="email"
              required
              value={email}
              onChange={this.onChangeEmail}
              name="email"
            />
          </div>

          <div className="form-group">
            <label htmlFor="date">DOB</label>
            <input
              type="date"
              className="form-control"
              required
              value={dateOfBirth}
              onChange={this.onChangeDateOfBirth}
              name="date"
            />
          </div>

          <div className="form-group">
            <label htmlFor="phoneNo">Phone No</label>
            <input
              type="number"
              className="form-control"
              id="phoneNo"
              required
              value={phoneNo}
              onChange={this.onChangePhoneNo}
              name="phoneNo"
            />
          </div>

          <div className="form-group">
            <select  onChange={(event) => this.onSchoolSelect(event)}>
              <option value="">Select School</option>
              {schools.map((school) => (
                <option
                  key={school.schoolId}
                  typeof="checked"
                  value={school.schoolName}
                 
                >
                  {school.schoolName}
                </option>
              ))}
            </select>
          </div>

          <button
            onClick={this.saveStudent}
            type="button"
            className="btn btn-success"
          >
            Submit
          </button>
          <Link to="/students">
            <button type="button" className="btn btn-warning">
              Cancel
            </button>
          </Link>
        </form>
      </div>
    );
  }
}

// shashi/student-task/vuejs/src/components/AddStudent.vue
<!-- eslint-disable prettier/prettier -->
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="studentname">Student name</label>
        <input
          type="text"
          class="form-control"
          id="studentname"
          placeholder="studentname"
          required
          v-model="student.studentname"
          name="studentname"
        />
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <textarea
          class="form-control"
          id="address"
          required
          v-model="student.address"
          name="address"
          placeholder="address"
        ></textarea>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          placeholder="email"
          required
          v-model="student.email"
          name="email"
        />
      </div>
      <div class="form-group">
        <label for="phonenumber">Phone number</label>
        <input
          type="text"
          class="form-control"
          id="phonenumber"
          placeholder="phonenumber"
          required
          v-model="student.phonenumber"
          name="phonenumber"
        />
      </div>
      <div class="form-group">
        <label for="gender">Gender</label>
        <input
          type="text"
          class="form-control"
          placeholder="gender"
          id="gender"
          required
          v-model="student.gender"
          name="gender"
        />
      </div>  
      
      <label for="gender">Select Gender</label>      
      <div class="form-group">
  <input type="radio" id="Male" value="Male" v-model="student.gender">
  <label for="Male">Male</label><br>
  <input type="radio" id="Female" value="Female" v-model="student.gender">
  <label for="Female">Female</label><br>
  <input type="radio" id="Others" value="Others" v-model="student.gender"> 
  <label for="Female">Others</label><br>
</div>
      <div class="form-group">
        <label for="dob">Date of birth</label>
        <input
          type="Date"
          class="form-control"
          id="dob"
          required
          v-model="student.dob"
          name="dob"
        />
      </div> 
      <div class="form-group">
        <label>School List: </label>      
        <select  v-model="student.school" @change="onSchoolSelect($event)">
          <option>Select School</option>
          <option           
            placeholder="select school"           
            v-for="(entry, index) in schoolList"
            :key="index"
            :value="entry.schoolid"
          >
            {{ entry.schoolname }}
          </option>
        </select>
      </div>  
      <button @click="saveStudent" class="btn btn-success">Submit</button>
    </div>
    <div v-else>
      <h4>You submitted successfully!</h4>
      <button class="btn btn-success" @click="newTutorial">Add</button>
    </div>
    <br />
      <router-link 
          :to="'/studentlist'"
          class="badge badge-warning"
          custom
      v-slot="{ navigate }"
          > <button  
          class="btn btn-danger" 
          @click="navigate"  
        role="link"
        >Cancel</button>
      </router-link
        >  
  </div>
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import studentservice from "@/services/studentservice";
import { Student } from "@/types/student";
import ResponseData from "@/types/ResponseData";
import School from "@/types/school";
export default defineComponent({
  name: "add-student",
  data() {
    return {
      student: {
        studentname: "",
        address: "",
        email: "",
        gender: "",
      } as Student,
      genderList: [
        { value: "male", label: "Male" },
        { value: "female", label: "Female" },
      ],
      submitted: false,
      schoolList: [] as School[],
      currentSchool: {} as School,
    };
  },
  methods: {
    saveStudent() {
      let data = {
        studentname: this.student.studentname,
        address: this.student.address,
        email: this.student.email,
        gender: this.student.gender,
        dob: this.student.dob,
        phonenumber: this.student.phonenumber,
        school: this.student.school
      };
console.log('create url starts')
      studentservice
        .createStudent(data)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.submitted = true;
          console.log('student created')
        })
        
        .catch((e: Error) => {
          console.log(e);
        });
        console.log('student not created')
    },
    retrieveSchools() {
      studentservice
        .getAll()
        .then((response: ResponseData) => {
          this.schoolList = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    
    onSchoolSelect(event:any) { 
      const src = event.target.value;
      const data = this.schoolList.filter((s) => s.schoolid === +src);
     this.currentSchool = data[0];
     console.log(this.currentSchool);
    },

    newTutorial() {
      this.submitted = false;
      this.student = {} as Student;
    },
  },
  mounted() {
    this.retrieveSchools();
  },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style>
.submit-form {
  max-width: 300px;
  margin: auto;
}
.body {
  padding: 1rem;
}
</style>
