// harsha/School-Teacher-Student/client-ReactJS/src/components/school/add-school.component.tsx
import { ChangeEvent, Component } from "react";
import SchoolService from "../../services/school.service";
import TeacherService from "../../services/teacher.service";
import StudentService from "../../services/student.service";
import { Link, RouteComponentProps } from "react-router-dom";
import { School } from "../../types/school.type";
import Multiselect from "multiselect-react-dropdown";

interface RouterProps {}

type Props = RouteComponentProps<RouterProps>;

type State = School & {
  submitted: boolean;
};

export default class AddSchool extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.saveSchool = this.saveSchool.bind(this);

    this.state = {
      schoolName: "",
      address: "",
      submitted: false,
    };
  }

  componentDidMount() {
    this.retrieveTeachers();
    this.retrieveStudents();
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      schoolName: e.target.value,
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      address: e.target.value,
    });
  }

  retrieveTeachers() {
    TeacherService.getTeachers()
      .then((response: any) => {
        this.setState({
          teachers: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  retrieveStudents() {
    StudentService.getStudents()
      .then((response: any) => {
        this.setState({
          students: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  saveSchool() {
    const school: School = {
      schoolName: this.state.schoolName,
      address: this.state.address,
    };

    SchoolService.create(school)
      .then((response: any) => {
        this.setState({
          schoolId: response.data.schoolId,
          schoolName: response.data.schoolName,
          address: response.data.address,
          submitted: true,
        });
        this.props.history.push("/schools");
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { schoolName, address, teachers, students } = this.state;

    return (
      <div className="submit-form">
        <h2>ADD SCHOOL</h2>
        <form>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={schoolName}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>

          <div className="form-group">
            <Multiselect
              options={teachers}
              closeIcon="close"
              placeholder="Choose Teachers"
              displayValue="teacherName"
            />
          </div>

          <div className="form-group">
            <Multiselect
              options={students}
              closeIcon="close"
              placeholder="Choose Students"
              displayValue="studentName"
            />
          </div>

          <button
            onClick={this.saveSchool}
            type="button"
            className="btn btn-success"
          >
            Submit
          </button>
          <Link to="/schools">
            <button type="button" className="btn btn-warning">
              Cancel
            </button>
          </Link>
        </form>
      </div>
    );
  }
}

// shashi/student-task/vuejs/src/components/AddSchool.vue
<!-- eslint-disable prettier/prettier -->
<template>
    <div class="submit-form">
 <div v-if="!submitted">
        <div class="form-group">
          <label for="schoolname">school name</label>
          <input
            type="text"
            class="form-control"
            id="schoolname"
            required
            v-model="school.schoolname"
            name="schoolname"
          />
        </div>
        <div class="form-group">
          <label for="address">Address</label>
          <textarea
            class="form-control"
            id="address"
            required
            v-model="school.address"
            name="address"
            placeholder="address"
          ></textarea>
        </div> 
        <div class="form-group">
          <multiselect
            class="form-control"
            id="teacher"
            required
            v-model="selectedTeachers"
            name="teacher"
            :options="teacherData"
            :multiple="true"
            :close-on-select="false"
            :clear-on-select="false"
            :preserve-search="true"
            placeholder="Select Teacher"
            label="teachername"
            track-by="teachername"
            :preselect-first="true"
          >
          </multiselect>
        </div>
        <div class="form-group">
          <multiselect
            class="form-control"
            id="student"
            required
            v-model="selectedStudents"
            name="student"
            :options="studentData"
            :multiple="true"
            :close-on-select="false"
            :clear-on-select="false"
            :preserve-search="true"
            placeholder="Select Student"
            label="studentname"
            track-by="studentname"
            :preselect-first="true"
          >
          </multiselect>
        </div>
        <button @click="saveSchool" class="btn btn-success">Submit</button>
      </div>
      <div v-else>
        <h4>You submitted successfully!</h4>
        <button class="btn btn-success" @click="newTutorial">Add</button>
      </div>
      <br />
      <router-link 
          :to="'/school'"
          class="badge badge-warning"
          custom
      v-slot="{ navigate }"
          > <button  
          class="btn btn-danger" 
          @click="navigate"  
        role="link"
        >Cancel</button>
      </router-link
        >        
    </div>
  </template>
  <!-- eslint-disable prettier/prettier -->
  <script lang="ts">
  import { defineComponent } from "vue";
  import studentservice from "@/services/studentservice";
  import { Student } from "@/types/student";
  import ResponseData from "@/types/ResponseData";
  import School from "@/types/school";
import { Teacher } from "@/types/teacher";
import Multiselect from "@suadelabs/vue3-multiselect";
  export default defineComponent({
    name: "add-student",
    components: { Multiselect },
    data() {
    return {
      school: {
        schoolname: "",
        address: "",
      } as School,
      teacherData: [] as Teacher[],
      studentData: [] as Student[],
      submitted: false,
      selectedTeachers: [] as Teacher[],
      selectedStudents: [] as Student[],
    };
  },
    methods: {
      saveSchool() {    
        let data = {
            schoolname: this.school.schoolname,
        address: this.school.address,
        teacher: this.selectedTeachers,
        student:this.selectedStudents
        };
  
        studentservice
          .createSchool(data)
          .then((response: ResponseData) => {
            console.log(response.data);
            this.submitted = true;
          })
          .catch((e: Error) => {
            console.log(e);
          });
      },  
      retrieveTeachers() {
      studentservice
        .getAllTeacherss()
        .then((response: ResponseData) => {
          this.teacherData = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    retrieveStudents() {
      studentservice
        .getAllStudents()
        .then((response: ResponseData) => {
          this.studentData = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },  
  
      newTutorial() {
        this.submitted = false;
        this.school = {} as School;
      },
     
    },mounted() {
      this.retrieveStudents();
      this.retrieveTeachers()
    },
  });
  </script>
  <!-- eslint-disable prettier/prettier -->
  <style src="vue-multiselect/dist/vue-multiselect.min.css">
  .submit-form {
    max-width: 300px;
    margin: auto;
  }
  .body {
    padding: 1rem;
  }
  </style>
