// harsha/School-Teacher-Student/client-ReactJS/src/components/edit-school.component.tsx
import { Component, ChangeEvent } from "react";
import { Link, RouteComponentProps } from "react-router-dom";
import SchoolService from "../services/school.service";
import { School } from "../types/school.type";

interface RouterProps {
  // type for `match.params`
  id: string; // must be type `string` since value comes from the URL
}

type Props = RouteComponentProps<RouterProps>;

type State = {
  currentSchool: School;
};

export default class EditSchool extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.getSchool = this.getSchool.bind(this);
    this.updateSchool = this.updateSchool.bind(this);

    this.state = {
      currentSchool: {
        schoolId: null,
        schoolName: "",
        address: "",
      },
    };
  }

  componentDidMount() {
    this.getSchool(this.props.match.params.id);
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    const schoolName = e.target.value;

    this.setState(function (prevState) {
      return {
        currentSchool: {
          ...prevState.currentSchool,
          schoolName: schoolName,
        },
      };
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    const address = e.target.value;

    this.setState((prevState) => ({
      currentSchool: {
        ...prevState.currentSchool,
        address: address,
      },
    }));
  }

  getSchool(id: string) {
    SchoolService.get(id)
      .then((response: any) => {
        this.setState({
          currentSchool: response.data,
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  updateSchool() {
    SchoolService.update(
      this.state.currentSchool,
      this.state.currentSchool.schoolId
    )
      .then((response: any) => {
        console.log(response.data);
        this.props.history.push("/schools");
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { currentSchool } = this.state;

    return (
      <>
        <h4>EDIT SCHOOL</h4>
        <div className="edit-form">
          <form>
            <div className="form-group">
              <label htmlFor="schoolName">Name</label>
              <input
                type="text"
                className="form-control"
                id="schoolName"
                value={currentSchool.schoolName}
                onChange={this.onChangeName}
              />
            </div>
            <div className="form-group">
              <label htmlFor="address">Address</label>
              <input
                type="text"
                className="form-control"
                id="address"
                value={currentSchool.address}
                onChange={this.onChangeAddress}
              />
            </div>
          </form>

          <button
            type="submit"
            className="btn badge-success"
            onClick={this.updateSchool}
          >
            Update
          </button>
          <Link to={"/schools"}>
            <button type="submit" className="btn badge-warning">
              Cancel
            </button>
          </Link>
        </div>
      </>
    );
  }
}

// shashi/student-task/vuejs/src/components/EditSchool.vue
<script lang="ts">
/* eslint-disable */
import { defineComponent } from "vue";
import studentservice from "@/services/studentservice";
import School from "@/types/school";
import ResponseData from "@/types/ResponseData";

export default defineComponent({
  name: "edit-school",
  data() {
    return {
      currentSchool: {} as School,
      message: "",
    };
  },
  methods: {
    getSchool(id: any) {
      studentservice
        .getSchoolById(id)
        .then((response: ResponseData) => {
          this.currentSchool = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },   
  },
  mounted() {
    this.message = "";
    this.getSchool(this.$route.params.id);
  },
});
</script>
<template>
  <div v-if="currentSchool.schoolid" class="edit-form">
    <h4>Edit-School</h4>
    <form>
      <div class="form-group">
        <label for="schoolname">Schoolname</label>
        <input
          type="text"
          class="form-control"
          id="schoolname"
          v-model="currentSchool.schoolname"
        />
      </div>
      <div class="form-group">
        <label for="address">address</label>
        <input
          type="text"
          class="form-control"
          id="address"
          v-model="currentSchool.address"
        />
      </div>
      <label for="address">Teachers List:-</label>
      <div class="col-md-6" v-for="(entry, index) in currentSchool.teacher" :key="index">     
      <label>
         {{ entry.teachername }}
    </label>    
           
    </div>
    <br />              
    </form>
    <button class="badge badge-danger mr-2">Delete</button>

    <button type="submit" class="badge badge-success mr-2" >Update</button>

    <router-link 
          :to="'/school/'"
          class="badge badge-success"
          >Back</router-link>
    <p>{{ message }}</p>
  </div>

  <div v-else>
    <br />
    <p>Please click on a Tutorial...</p>
  </div>
</template>
<style>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
