// shashi/student-task/vuejs/src/components/TutorialsList.vue
<template>
  <div class="list row">
    <div class="col-md-8">
      <div class="input-group mb-3">
        <input
          type="text"
          class="form-control"
          placeholder="Search by title"
          v-model="title"
        />
        <div class="input-group-append">
          <button
            class="btn btn-outline-secondary"
            type="button"
            @click="searchTitle"
          >
            Search
          </button>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <h4>Tutorials List</h4>
      <ul class="list-group">
        <li
          class="list-group-item"
          :class="{ active: index == currentIndex }"
          v-for="(tutorial, index) in tutorials"
          :key="index"
          @click="setActiveTutorial(tutorial, index)"
        >
          {{ tutorial.title }}
        </li>
      </ul>

      <button class="m-3 btn btn-sm btn-danger" @click="removeAllTutorials">
        Remove All
      </button>
    </div>
    <div class="col-md-6">
      <div v-if="currentTutorial.id">
        <h4>Tutorial</h4>
        <div>
          <label><strong>Title:</strong></label> {{ currentTutorial.title }}
        </div>
        <div>
          <label><strong>Description:</strong></label>
          {{ currentTutorial.description }}
        </div>
        <div>
          <label><strong>Status:</strong></label>
          {{ currentTutorial.published ? "Published" : "Pending" }}
        </div>

        <router-link
          :to="'/tutorials/' + currentTutorial.id"
          class="badge badge-warning"
          >Edit</router-link
        >
      </div>
      <div v-else>
        <br />
        <p>Please click on a Tutorial...</p>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
/* eslint-disable */
import { defineComponent } from "vue";
import TutorialDataService from "@/services/TutorialDataService";
import Tutorial from "@/types/Tutorial";
import ResponseData from "@/types/ResponseData";

export default defineComponent({
  name: "tutorials-list",
  data() {
    return {
      tutorials: [] as Tutorial[],
      currentTutorial: {} as Tutorial,
      currentIndex: -1,
      title: "",
    };
  },
  methods: {
    retrieveTutorials() {
      TutorialDataService.getAll()
        .then((response: ResponseData) => {
          this.tutorials = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    refreshList() {
      this.retrieveTutorials();
      this.currentTutorial = {} as Tutorial;
      this.currentIndex = -1;
    },

    setActiveTutorial(tutorial: Tutorial, index = -1) {
      this.currentTutorial = tutorial;
      this.currentIndex = index;
    },

    removeAllTutorials() {
      TutorialDataService.deleteAll()
        .then((response: ResponseData) => {
          console.log(response.data);
          this.refreshList();
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    searchTitle() {
      TutorialDataService.findByTitle(this.title)
        .then((response: ResponseData) => {
          this.tutorials = response.data;
          this.setActiveTutorial({} as Tutorial);
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
  },
  mounted() {
    this.retrieveTutorials();
  },
});
</script>

<style>
.list {
  text-align: left;
  max-width: 750px;
  margin: auto;
}
</style>

// adarsh/tutorial/clint/src/app/components/tutorials-list/tutorials-list.component.ts
import { Component, OnInit } from '@angular/core'
import { Tutorial } from 'src/app/models/tutorial.model'
import { TutorialService } from 'src/app/services/tutorial.service'

@Component({
  selector: 'app-tutorials-list',
  templateUrl: './tutorials-list.component.html',
  styleUrls: ['./tutorials-list.component.css'],
})
export class TutorialsListComponent implements OnInit {
  tutorials?: Tutorial[]
  tutorial: any;
  categories:any
  clickDetailed!: boolean; 
  currentTutorial: Tutorial = {
    title: '',
    description: '',
    categories: undefined
   }
  currentIndex = -1
  title = ''
  Token: any;

  constructor(private tutorialService: TutorialService) {}

  ngOnInit(): void {
    this.getAuthentication();
    this.retrieveCategory();
    this.retrieveTutorials();
    
     }

  async retrieveTutorials(): Promise<void> {
    this.tutorial = await this.tutorialService.getAll();
  }
  async retrieveCategory(): Promise<void> {
    this.categories = await this.tutorialService.getCategories();
  }
  
  refreshList(): void {
    this.currentTutorial = {}
    this.currentIndex = -1
  }

  setActiveTutorial(tutorial: Tutorial, index: number): void {
    this.currentTutorial = tutorial
    this.currentIndex = index
  }

  removeAllTutorials(): void {
    this.tutorialService.deleteAll().subscribe(
      (response) => {
        console.log(response)
        this.refreshList()
      },
      (error) => {
        console.log(error)
      },
    )
  }

  searchTitle(): void {
    this.currentTutorial = {}
    this.currentIndex = -1
    this.tutorialService.findByTitle(this.title).subscribe(
      (data) => {
        this.tutorials = data
        console.log(data)
      },
      (error) => {
        console.log(error)
      },
    )
  }

async getAuthentication() {
this.Token = await this.tutorialService.getAthontication();
localStorage.setItem('id_token', this.Token.token);
const expiration = localStorage.getItem('id_token');
 }
}

<div class="col-md-6">
  <h4>Tutorials List</h4>
  <button class="m-3 btn btn-sm btn-danger" routerLink="/tutorials/add">Add</button>

  <ul class="list-group">
    <li class="list-group-item" *ngFor="let tutorial of tutorial; let i = index" [class.active]="i == currentIndex"
      (click)="setActiveTutorial(tutorial, i)">
      {{ tutorial.title }}
      <a class="btn btn-info btn-sm mr-2" routerLink="/tutorials-view/{{ currentTutorial.id }}"> View Details </a>
    </li>

  </ul>
</div>
<div class="col-md-6">
  <div *ngIf="currentTutorial.id" class="edit-form">
    <h4>Tutorial</h4>
    <div>
      <label><strong>Title:</strong></label>{{ currentTutorial.title }}
    </div>
    <div>
      <label><strong>Description:</strong></label>{{ currentTutorial.description }}
    </div>
    <a class="btn btn-info btn-sm mr-2" routerLink="/tutorials/{{ currentTutorial.id }}"> Edit </a>
  </div>
  <div *ngIf="!currentTutorial">
    <br />
    <p>Please click on a Tutorial...</p>
  </div>


  <!-- 
<div class="list row">
  <div class="col-md-8">
    <div class="input-group mb-3">
      <input
        type="text"
        class="form-control"
        placeholder="Search by title"
        [(ngModel)]="title"
      />
      <div class="input-group-append">
        <button
          class="btn btn-outline-secondary"
          type="button"
          (click)="searchTitle()"
        >
          Search
        </button>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <h4>Tutorials List</h4>
    <ul class="list-group">
      (click)="setActiveTutorial(tutorial, i)" 
      <li
        class="list-group-item"
        *ngFor="let tutorial of tutorial; let i = index"
        [class.active]="i == currentIndex"
        routerLink="/newTutorial/{{ tutorial.id }}">
        {{ tutorial.title }}
      </li>
    </ul>

    <button class="m-3 btn btn-sm btn-danger" (click)="removeAllTutorials()">
      Remove All
    </button>
  </div>
  <div class="col-md-6">
    <div *ngIf="currentTutorial.id">
      <h4>Tutorial</h4>
      <div>
        <label><strong>Title:</strong></label>
        {{ currentTutorial.title }}
      </div>
      <div>
        <label><strong>Description:</strong></label>
        {{ currentTutorial.description }}
      </div>
      <div>
        <label><strong>Status:</strong></label>
        {{ currentTutorial.published ? 'Published' : 'Pending' }}
      </div>
      <a
        class="badge badge-warning"
        routerLink="/tutorials/{{ currentTutorial.id }}"
      >
        Edit
      </a>
    </div>

    <div *ngIf="!currentTutorial">
      <br />
      <p>Please click on a Tutorial...</p>
    </div>
  </div>
</div> 
<div class="col-md-6"> -->
  <!-- <ul class="list-group">
    <li class="list-group-item">
      {{ selectedCategory }} 
    </li>
  </ul> -->
