// adarsh/school/VUE-client/src/components/SchoolEdit.vue
<template>
  <div v-if="currentSchool.id" class="edit-form">
    <h4>School</h4>
    <form>
      <div class="form-group">
        <label for="name">Name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          v-model="currentSchool.name"
        />
      </div>
      <div class="form-group">
        <label for="address">Adresss</label>
        <input
          type="text"
          class="form-control"
          id="address"
          v-model="currentSchool.address"
        />
      </div>
      <div class="form-group">
        <label for="teachers">Teachers</label>
        <ejs-multiselect
          :dataSource="this.teachers"
          :value="this.slectedValues"
          :fields="fields"
        ></ejs-multiselect>
      </div>
      <div class="form-group">
        <label for="students">Student</label>
        <ejs-multiselect
          :dataSource="this.students"
          :value="this.slectedValues"
          :fields="fields"
        ></ejs-multiselect>
      </div>
    </form>
    <button type="cancle" @click="updateSchool" class="btn btn-success">
      Update
    </button>
    <button type="cancle" class="btn btn-danger" @click="onCancle">
      cancle
    </button>
    <p>{{ message }}</p>
  </div>

  <div v-else>
    <br />
    <p>Please click on a Tutorial...</p>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { School } from "@/types/school";
import SchoolService from "@/services/SchoolService";
import { Student } from "@/types/student";
import { Teacher } from "@/types/teacher";
import App from "@/App.vue"
import { MultiSelectPlugin } from "@syncfusion/ej2-vue-dropdowns";
Vue.use(MultiSelectPlugin);

@Component
export default class SchoolEdit extends Vue {
  schools: School[] = [];
  slectedValues: string[] = [];
  private message: string = "";
  currentSchool: School = {
    name: "",
    address: "",
    teachers: [],
    students: [],
  };
  teachers: Teacher[] = [];
  students: Student[] = [];
  components!: {

  };

  data() {
    return {
      fields: { text: "name", value: "id" },
    };
  }

  getSchool(id: any) {
    SchoolService.getSchool(id)
      .then((response) => {
        this.currentSchool = response.data;
        for (var teacher of this.currentSchool.teachers!) {
          this.slectedValues.push(teacher.name!);
         
        }
      })
      .catch((e) => {});
    this.data;
  }

  updateSchool() {
    SchoolService.updateSchool(this.currentSchool.id!, this.currentSchool)
      .then((response) => {
        this.message = "The tutorial was updated successfully!";
      })
      .catch((e) => {});
  }

  retrieveTeachers() {
    SchoolService.getAllTeachers()
      .then((response) => {
        this.teachers = response.data;
      })
      .catch((e) => {});
  }
  retrieveSchools() {
    SchoolService.getAllSchools()
      .then((response) => {
        this.schools = response.data;
      })
      .catch((e) => {});
  }
  retrieveStudent() {
    SchoolService.getAllStudents()
      .then((response) => {
        this.students = response.data;
      })
      .catch((e) => {});
  }
  onCancle() {
    this.$router.replace("/school");
  }

  mounted() {
    this.getSchool(this.$route.params.id);
    this.retrieveSchools();
    this.retrieveTeachers();
    this.message = "";
    this.retrieveStudent();
  }
}
</script>

<style scoped>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// druthvik/StudentManagement/client-reactjs/src/components/school/schooledit.component.tsx
import Multiselect from "multiselect-react-dropdown";
import { Component, ChangeEvent } from "react";
import { Link, RouteComponentProps } from "react-router-dom";
import SchoolService from "../../services/school.service";
import ISchoolData from "../../types/school.types";
import { TeacherData } from "../../types/teacher.types";
import { IStudentData } from "../../types/student.types";
interface RouterProps {
  id: string;
}
type Props = RouteComponentProps<RouterProps>;
type State = {
  currentSchool: ISchoolData;
  teachers: Array<TeacherData>;
  students: Array<IStudentData>;
  message: string;
};
export default class EditSchool extends Component<Props, State> {
  teachers: TeacherData[] = [];
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.getTutorial = this.getTutorial.bind(this);
    // this.updatePublished = this.updatePublished.bind(this);
    this.updateSchool = this.updateSchool.bind(this);
    this.state = {
      currentSchool: {
        schoolid: null,
        name: "",
        address: "",
      },
      teachers: [],
      students: [],
      message: "",
    };
  }
  componentDidMount() {
    this.getTutorial(this.props.match.params.id);
  }
  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    const name = e.target.value;
    this.setState(function (prevState) {
      return {
        currentSchool: {
          ...prevState.currentSchool,
          name: name,
        },
      };
    });
  }
  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    const address = e.target.value;
    this.setState((prevState) => ({
      currentSchool: {
        ...prevState.currentSchool,
        address: address,
      },
    }));
  }
  getTutorial(id: string) {
    SchoolService.get(id)
      .then((response: any) => {
        this.setState({
          currentSchool: response.data,
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  // updatePublished(status: boolean) {
  //   const data: ISchoolData = {
  //     schoolid: this.state.currentSchool.schoolid,
  //     name: this.state.currentSchool.name,
  //   };
  //   SchoolService.update(data, this.state.currentSchool.schoolid)
  //     .then((response: any) => {
  //       this.setState((prevState) => ({
  //         currentSchool: {
  //           ...prevState.currentSchool,
  //           published: status,
  //         },
  //         message: "The status was updated successfully!",
  //       }));
  //       console.log(response.data);
  //     })
  //     .catch((e: Error) => {
  //       console.log(e);
  //     });
  // }
  updateSchool() {
    SchoolService.update(
      this.state.currentSchool,
      this.state.currentSchool.schoolid
    )
      .then((response: any) => {
        console.log(response.data);
        this.setState({
          message: "The tutorial was updated successfully!",
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { currentSchool, teachers, students } = this.state;
    return (
      <>
        <h4>EDIT SCHOOL</h4>
        <div className="edit-form">
          <form>
            <div className="form-group">
              <label htmlFor="schoolName">Name</label>
              <input
                type="text"
                className="form-control"
                id="schoolName"
                value={currentSchool.name}
                onChange={this.onChangeName}
              />
            </div>
            <div className="form-group">
              <label htmlFor="address">Address</label>
              <input
                type="text"
                className="form-control"
                id="address"
                value={currentSchool.address}
                onChange={this.onChangeAddress}
              />
            </div>
            <div className="form-group">
              <label>Teachers</label>

              <Multiselect
                options={teachers}
                selectedValues={currentSchool.teacher}
                closeIcon="close"
                placeholder="Choose Teachers"
                displayValue="name"
              />
            </div>
            <div className="form-group">
              <label>Students</label>

              <Multiselect
                options={students}
                selectedValues={currentSchool.students}
                closeIcon="close"
                placeholder="Choose School"
                displayValue="name"
              />
            </div>
          </form>
          <Link to={"/schools"}>
            <button
              onClick={this.updateSchool}
              type="submit"
              className="btn badge-success"
            >
              Update
            </button>

            <button type="submit" className="btn badge-warning">
              Cancel
            </button>
          </Link>
        </div>
      </>
    );
  }
}
