// harsha/School-Teacher-Student/client-ReactJS/src/components/login.component.tsx
import { Formik, Form, Field, ErrorMessage } from "formik";
import { Component } from "react";
import { RouteComponentProps } from "react-router-dom";
import * as Yup from "yup";
import AuthService from "../services/auth.service" 

interface RouterProps {}

type Props = RouteComponentProps<RouterProps>;

type State = {
  username: string,
  password: string,
  loading: boolean,
  message: string
};

export default class Login extends Component<Props, State> {
    constructor(props: Props) {
        super(props);
        this.handleLogin = this.handleLogin.bind(this);

        this.state = {
          username: "",
          password: "",
          loading: false,
          message: ""
        };
    }

    componentDidMount() {
        const currentUser = AuthService.getCurrentUser();
    
        // if (currentUser) {
        //   this.setState({ redirect: "/schools" });
        // };
      }

    validationSchema() {
        return Yup.object().shape({
          username: Yup.string().required("This field is required!"),
          password: Yup.string().required("This field is required!"),
        });
      }
    
      handleLogin(formValue: { username: string; password: string }) {
        const { username, password } = formValue;
    
        this.setState({
          message: "",
          loading: true
        });

        AuthService.login(username, password).then(
            () => {
              this.setState({
                
              });
              this.props.history.push("/students");
            },
            error => {
              const resMessage =
                (error.response &&
                  error.response.data &&
                  error.response.data.message) ||
                error.message ||
                error.toString();
      
              this.setState({
                loading: false,
                message: resMessage
              });
            }
          );
    }

    render() {
        const { loading, message } = this.state;
    
        const initialValues = {
          username: "",
          password: "",
        };
    
        return (
          <div className="col-md-12">
            <div className="card card-container">
              <img
                src="//ssl.gstatic.com/accounts/ui/avatar_2x.png"
                alt="profile-img"
                className="profile-img-card"
              />
    
              <Formik
                initialValues={initialValues}
                validationSchema={this.validationSchema}
                onSubmit={this.handleLogin}
              >
                <Form>
                  <div className="form-group">
                    <label htmlFor="username">Username</label>
                    <Field name="username" type="text" className="form-control" />
                    <ErrorMessage
                      name="username"
                      component="div"
                      className="alert alert-danger"
                    />
                  </div>
    
                  <div className="form-group">
                    <label htmlFor="password">Password</label>
                    <Field name="password" type="password" className="form-control" />
                    <ErrorMessage
                      name="password"
                      component="div"
                      className="alert alert-danger"
                    />
                  </div>
    
                  <div className="form-group">
                    <button type="submit" className="btn btn-primary btn-block" disabled={loading}>
                      {loading && (
                        <span className="spinner-border spinner-border-sm"></span>
                      )}
                      <span>Login</span>
                    </button>
                  </div>
    
                  {message && (
                    <div className="form-group">
                      <div className="alert alert-danger" role="alert">
                        {message}
                      </div>
                    </div>
                  )}
                </Form>
              </Formik>
            </div>
          </div>
        );
      }
    }

// Shubhankar/CompanyDept/client/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/auth/auth.service';
import { LoginUser } from 'src/app/models/login';


@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginform!: FormGroup;
  login: LoginUser = {
    username:'',
    password:'',
  };
  submitted = false;
  constructor(private authService: AuthService, 
    private router: Router,
    private formBuilder: FormBuilder
  ) {}

  ngOnInit(): void {
    this.loginform = this.formBuilder.group({
      username: ['', Validators.required],
      password: ['', Validators.required],
    });
  }

 get fval() {
    return this.loginform.controls;
  }
  async signup() {
    if (this.loginform.invalid) {
      return;
    }
  }
  LoginDetail() {
    this.authService.userLogin(this.login).subscribe((data) => {
      if (data) {
        this.router.navigate(['admin']);
      }
    });
  }
 
}
<div class="col-md-2">
  <div class="card card-container">
    <img
      id="profile-img"
      src="//ssl.gstatic.com/accounts/ui/avatar_2x.png"
      class="profile-img-card"
    />
    <form [formGroup]="loginform" (ngSubmit)="signup()">
      <div class="form-group">
        <h4>Login</h4>
        <div class="formbox">
          <div class="form-group">
            <label for="username">UserName</label>
            <input
              type="username"
              formControlName="username"
              class="form-control"
              id="username"
              [(ngModel)]="login.username"
              [ngClass]="{ 'is-invalid': submitted && fval.username.errors }"
            />
            <div
              *ngIf="submitted && fval.username.errors"
              class="invalid-feedback"
            >
              <div *ngIf="fval.username.errors.required">
                User Field is required
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="password">Password</label>
            <input
              type="password"
              formControlName="password"
              class="form-control"
              id="password"
              [(ngModel)]="login.password"
              [ngClass]="{ 'is-invalid': submitted && fval.password.errors }"
            />
            <div
              *ngIf="submitted && fval.password.errors"
              class="invalid-feedback"
            >
              <div *ngIf="fval.password.errors.required">
                password Field is required
              </div>
            </div>
          </div>

          <br />
          <button type="button" class="btn btn-primary" (click)="LoginDetail()">
            login
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
