// adarsh/school/VUE-client/src/components/AddStudent.vue
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="title">Name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          required
          v-model="students.name"
          name="name"
        />
      </div>

      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="students.address"
          name="address"
        />
        <br />
      </div>
      <div class="form-group">
        <label for="email">EMAIL</label>
        <input
          class="form-control"
          id="email"
          required
          v-model="students.email"
          name="email"
        />
        <br />
      </div>
      <div class="form-group">
        <label for="dateOfBirth">DATE</label>
        <input
          class="form-control"
          id="dateOfBirth"
          type="date"
          required
          v-model="students.dateOfBirth"
          name="dateOfBirth"
        />
        <br />
      </div>
      <div class="form-group">
        <label for="phone">PHONE</label>
        <input
          class="form-control"
          id="phone"
          required
          v-model="students.phone"
          name="phone"
        />
        <br />
      </div>
      <label for="gender">Select Gender</label>
      <div class="form-group" v-for="(gender, index) in genders" :key="index">
        <input type="radio" v-model="students.gender" name="gender" />{{
          gender
        }}
      </div>
      <br />
      <div class="form-group">
        <label>School List: </label>
        <select  v-model="students.schools" @change="onSchoolSelect($event)">
          <option>Select School</option>
          <option           
            placeholder="select school"           
            v-for="(school, index) in schools"
            :key="index"
            :value="school.id"
          >
            {{ school.name }}
          </option>
        </select>
      </div>
      <br />

      <button @click="saveStudent" class="btn btn-success">Submit</button>

      <button @click="saveStudent" class="btn btn-danger">cancle</button>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { School } from "@/types/school";
import SchoolService from "@/services/SchoolService";
import App from "@/App.vue";
import { Student } from "@/types/student";
import { Teacher } from "@/types/teacher";


@Component
export default class AddStudent extends Vue {
  genders: string[] = ["MALE", "FEMALE"];
  students: Student = {
    name: "",
    address: "",
    email: "",
    gender: "",
    dateOfBirth: "",
    schools: {},
  };
 
  teachers: Teacher[] = [];
 currentSchool: School={};



  private submitted: boolean = false;
  schools: School[] = [];

  retrieveStudent() {
    SchoolService.getAllStudents()
      .then((response) => {
        this.students = response.data;
      })
      .catch((e) => {});
  }
  retrieveSchools() {
    SchoolService.getAllSchools()
      .then((response) => {
        this.schools = response.data;
      })
      .catch((e) => {
    
      });
  }
  saveStudent() {
    let data = {
      name: this.students.name,
      address: this.students.address,
      email: this.students.email,
      gender: this.students.gender,
      dateOfBirth: this.students.dateOfBirth,
      schools:  this.currentSchool,
    };

    SchoolService.createStudent(data)
      .then((response) => {
        this.students = response.data;
        this.submitted = true;
      })
      .catch((e) => {
      });
  }

  
     onSchoolSelect(event:any) { 
      const sourc = event.target.value;
      const data = this.schools.filter((s) => s.id === +sourc);
     this.currentSchool = data[0];

    } 

  onCancle() {
    this.$router.replace("/");
  }

  mounted() {
    this.retrieveStudent();
    this.retrieveSchools();
  }
}
</script>

<style scoped>
.submit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// harsha/School-Teacher-Student/client-ReactJS/src/components/student/add-student.component.tsx
import { ChangeEvent, Component } from "react";
import { Link, RouteComponentProps } from "react-router-dom";
import { Student } from "../../types/student.type";
import SchoolService from "../../services/school.service";
import StudentService from "../../services/student.service";
import { School } from "../../types/school.type";

interface RouterProps {}

type Props = RouteComponentProps<RouterProps>;

type State = Student & {
  schools: Array<School>;
  submitted: boolean;
};

const genders = [{ value: "Male" }, { value: "Female" }];

export default class AddStudent extends Component<Props, State> {
  currentSchool: School={};
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.onChangeGender = this.onChangeGender.bind(this);
    this.onChangeEmail = this.onChangeEmail.bind(this);
    this.onChangeDateOfBirth = this.onChangeDateOfBirth.bind(this);
    this.onChangePhoneNo = this.onChangePhoneNo.bind(this);
    this.onChangeSchool = this.onChangeSchool.bind(this);
    this.saveStudent = this.saveStudent.bind(this);

    this.state = {
      studentName: "",
      address: "",
      gender: "",
      email: "",
      dateOfBirth: "",
      school: {
        schoolName: "",
      },
      schools: [],
      submitted: false,
    };
  }

  componentDidMount() {
    this.retrieveSchools();
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      studentName: e.target.value,
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      address: e.target.value,
    });
  }

  onChangeGender(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      gender: e.target.value,
    });
  }

  onChangeEmail(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      email: e.target.value,
    });
  }

  onChangeDateOfBirth(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      dateOfBirth: e.target.value,
    });
  }

  onChangePhoneNo(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      phoneNo: e.target.valueAsNumber,
    });
  }

  onChangeSchool(school: School) {
    this.setState({
      school:school ,
    });
  }

  onSchoolSelect(event: any) {
    const schoolData = this.state.schools.filter((school) => school.schoolName === event.target.value);
    this.currentSchool = schoolData[0];
    console.log(schoolData);
    this.setState({
      school: this.currentSchool,
    });
  }

  retrieveSchools() {
    SchoolService.getSchools()
      .then((response: any) => {
        this.setState({
          schools: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  saveStudent() {
    const student: Student = {
      studentName: this.state.studentName,
      address: this.state.address,
      email: this.state.email,
      gender: this.state.gender,
      dateOfBirth: this.state.dateOfBirth,
      phoneNo: this.state.phoneNo,
      school: this.state.school,
    };

    StudentService.create(student)
      .then((response: any) => {
        this.setState({
          studentId: response.data.studentId,
          studentName: response.data.studentName,
          address: response.data.address,
          email: response.state.email,
          gender: response.state.gender,
          dateOfBirth: response.state.dateOfBirth,
          phoneNo: response.state.phoneNo,
          school: response.data.school,
          submitted: true,
        });
        this.props.history.push("/students");
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { studentName, address, email, dateOfBirth, phoneNo, schools } =
      this.state;

    return (
      <div className="submit-form">
        <h2>ADD STUDENT</h2>
        <form>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={studentName}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>

          <div className="form-group">Select a Gender</div>
          {genders.map((gender, i) => (
            <label key={i}>
              <input
                type="radio"
                name="gender"
                value={gender.value}
                onChange={this.onChangeGender}
              />{" "}
              {gender.value}
            </label>
          ))}
          <br />

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              type="text"
              className="form-control"
              id="email"
              required
              value={email}
              onChange={this.onChangeEmail}
              name="email"
            />
          </div>

          <div className="form-group">
            <label htmlFor="date">DOB</label>
            <input
              type="date"
              className="form-control"
              required
              value={dateOfBirth}
              onChange={this.onChangeDateOfBirth}
              name="date"
            />
          </div>

          <div className="form-group">
            <label htmlFor="phoneNo">Phone No</label>
            <input
              type="number"
              className="form-control"
              id="phoneNo"
              required
              value={phoneNo}
              onChange={this.onChangePhoneNo}
              name="phoneNo"
            />
          </div>

          <div className="form-group">
            <select  onChange={(event) => this.onSchoolSelect(event)}>
              <option value="">Select School</option>
              {schools.map((school) => (
                <option
                  key={school.schoolId}
                  typeof="checked"
                  value={school.schoolName}
                 
                >
                  {school.schoolName}
                </option>
              ))}
            </select>
          </div>

          <button
            onClick={this.saveStudent}
            type="button"
            className="btn btn-success"
          >
            Submit
          </button>
          <Link to="/students">
            <button type="button" className="btn btn-warning">
              Cancel
            </button>
          </Link>
        </form>
      </div>
    );
  }
}
