// shashi/student-task/vuejs/src/components/AddTeacher.vue
<!-- eslint-disable prettier/prettier -->
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="teachername">Teacher name</label>
        <input
          type="text"
          class="form-control"
          id="teachername"
          required
          v-model="teacher.teachername"
          name="teachername"
        />
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <textarea
          class="form-control"
          id="address"
          required
          v-model="teacher.address"
          name="address"
          placeholder="address"
        ></textarea>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          required
          v-model="teacher.email"
          name="email"
        />
      </div>
      <div class="form-group">
        <label for="gender">Gender</label>
        <input
          type="text"
          class="form-control"
          id="gender"
          required
          v-model="teacher.gender"
          name="gender"
        />
      </div>
      <label for="gender">Select Gender</label>
      <div class="form-group" v-for="(entry, index) in genderList" :key="index">
        <input type="radio" v-model="teacher.gender" name="gender" />{{
          entry.label
        }}
      </div>
      <label>schoolsList:</label>
      <div class="form-check" v-for="(entry, index) in schoolList" :key="index">
        <input
          type="checkbox"
          class="form-check-input"
          @click="selectedSchoolMethod(entry)"
        />{{ entry.schoolname }}
      </div>
      <button @click="saveTeacher" class="btn btn-success">Submit</button>
    </div>
    <div v-else>
      <h4>You submitted successfully!</h4>
      <button class="btn btn-success" @click="newTutorial">Add</button>
    </div>
  </div>
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import studentservice from "@/services/studentservice";
import { Teacher } from "@/types/teacher";
import School from "@/types/school";
import ResponseData from "@/types/ResponseData";
export default defineComponent({
  name: "add-teacher",  
  data() {
    return {
      teacher: {
        teachername: "",
        address: "",
        email: "",
        gender: "",
      } as Teacher,
      schoolList: [] as School[],
      submitted: false,
      currentSchool: {} as School,
      selectedSchools: [] as School[],
      genderList: [
        { value: "male", label: "Male" },
        { value: "female", label: "Female" },
      ],
  
    };
  },
  methods: {
    saveTeacher() {
      let data = {
        teachername: this.teacher.teachername,
        address: this.teacher.address,
        email: this.teacher.email,
        gender: this.teacher.gender,
        school: this.selectedSchools,
      };
      studentservice
        .createTeacher(data)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.submitted = true;
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    selectedSchoolMethod(school: School) {
      this.currentSchool = school;
      this.selectedSchools?.push(this.currentSchool);
    },
    retrieveSchools() {
      studentservice
        .getAll()
        .then((response: ResponseData) => {
          this.schoolList = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    newTutorial() {
      this.submitted = false;
      this.teacher = {} as Teacher;
    },
  },
  mounted() {
    this.retrieveSchools();
  },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style>
.submit-form {
  max-width: 300px;
  margin: auto;
}
.body {
  padding: 1rem;
}
</style>

// druthvik/StudentManagement/client-reactjs/src/components/teacher/addteacher.component.tsx
/* eslint-disable no-labels */
/* eslint-disable @typescript-eslint/no-unused-expressions */
/* eslint-disable no-unused-labels */
import { Component, ChangeEvent } from "react";
import teacherService from "../../services/teacher.service";
import { TeacherData } from "../../types/teacher.types";
import schoolService from "../../services/school.service";
import ISchoolData from "../../types/school.types";

type Props = {
  teacher?: TeacherData;
};
type State = TeacherData & {
  schools?: Array<ISchoolData>;
};

const genderList = [
  { value: "Male", label: "Male" },
  { value: "Female", label: "Female" },
];
export default class AddTeacher extends Component<Props, State> {
  currentSchool = {} as ISchoolData;
  addedSchool: ISchoolData[] = [];
  schools: ISchoolData[] = [];
  onchooseoption: {} = {};
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.onChangephonenumber = this.onChangephonenumber.bind(this);
    this.onChangeemail = this.onChangeemail.bind(this);
    this.onChangegender = this.onChangegender.bind(this);
    this.pushSelectedSchool = this.pushSelectedSchool.bind(this.currentSchool);
    this.state = {
      name: "",
      address: "",
      email: "",
      gender: "",
      school: [],
    };
    schools: [];
  }
  componentDidMount() {
    this.retrieveSchools();
  }

  retrieveSchools() {
    schoolService
      .getAll()
      .then((response: any) => {
        this.setState({
          schools: response.data,
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      name: e.target.value,
    });
  }

  onChangephonenumber(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      phonenumber: e.target.valueAsNumber,
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      address: e.target.value,
    });
  }

  pushSelectedSchool(school = {} as ISchoolData) {
    this.addedSchool.push(school);
    console.log(this.addedSchool);
  }
  onChangeSchools(schools: ISchoolData) {
    this.setState({
      school: this.state.school?.concat(schools),
    });
  }

  onChangeemail(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      email: e.target.value,
    });
  }
  onChangegender(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      gender: e.target.value,
    });
  }

  saveTeacher = () => {
    const data: TeacherData = {
      name: this.state.name,
      address: this.state.address,
      phonenumber: this.state.phonenumber,
      email: this.state.email,
      gender: this.state.gender,
      school: this.state.school,
    };

    teacherService
      .create(data)
      .then((response: any) => {
        this.setState({
          name: response.data.name,
          address: response.data.address,
          phonenumber: response.data.phonenumber,
          email: response.data.email,
          gender: response.data.gender,
          school: response.data.school,
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  };
  render() {
    const { name, address, phonenumber, email, schools } = this.state;

    return (
      <div className="submit-form">
        <div>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={name}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>
          <div className="form-group">
            <label htmlFor="phonenumber">Phonenumber</label>
            <input
              type="number"
              className="form-control"
              id="phonenumber"
              required
              value={phonenumber}
              onChange={this.onChangephonenumber}
              name="name"
            />
          </div>
          <div className="form-group">
            <label htmlFor="name">Email</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={email}
              onChange={this.onChangeemail}
              name="name"
            />
          </div>
          <div className="title">
            <label htmlFor="name">Gender</label>
            {genderList.map((x, i) => (
              <label key={i}>
                <input
                  type="radio"
                  name="gender"
                  value={x.value}
                  onChange={this.onChangegender}
                />{" "}
                {x.label}
              </label>
            ))}
          </div>
          <div className="form-group">
            <label>Schools</label>

            {schools?.map((school, i) => (
              <div key={i}>
                <input
                  type="checkbox"
                  name="schools"
                  value={school}
                  onChange={() => this.onChangeSchools(school)}
                />{" "}
                {school.name}
              </div>
            ))}
          </div>
          <button onClick={this.saveTeacher} className="btn btn-success">
            Submit
          </button>
        </div>
      </div>
    );
  }
}
