// shashi/student-task/vuejs/src/components/EditTeacher.vue
<script lang="ts">
/* eslint-disable */
import { defineComponent } from "vue";
import studentservice from "@/services/studentservice";
import { Teacher } from "@/types/teacher";
import ResponseData from "@/types/ResponseData";
import School from "@/types/school";

export default defineComponent({
  name: "edit-teacher",
  data() {
    return {
      currentTeacher: {} as Teacher,
      schoolList: [] as School[],
      message: "",
      currentSchool: {} as School,
      removeSchool: {} as School,
      value: [] as number[],
    };
  },
  methods: {
    getTeacherById(id: any) {
      studentservice
        .getTeacherById(id)
        .then((response: ResponseData) => {
          this.currentTeacher = response.data;
          console.log(response.data);
          for (const i of this.currentTeacher.school) {
            this.value.push(i.schoolid!);
          }
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    retrieveSchools() {
      studentservice
        .getAll()
        .then((response: ResponseData) => {
          this.schoolList = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    updateTeacher() {
      studentservice
        .updateTeacher(this.currentTeacher)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.message = "The teacher was updated successfully!";
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    async removeSchoolInSchoolList(school: School): Promise<void> {
      this.currentSchool = school;
      this.currentTeacher.school?.push(this.currentSchool);
      this.schoolList.splice(this.schoolList.indexOf(this.currentSchool), 1);
    },
    async removeSelectedSchoolFromTeacher(school: School): Promise<void> {
      this.removeSchool = school;
      this.schoolList.push(this.removeSchool);
      this.currentTeacher.school?.splice(
        this.currentTeacher.school?.indexOf(this.removeSchool),
        1
      );
    },
    deleteTeacher() {
      studentservice.deleteTeacher(this.currentTeacher.teacherid)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.$router.push({ name: "teacherslist" });
        })
        .catch((e: Error) => {
          console.log(e);
        });
    }, 
  },
  mounted() {
    this.message = "";
    this.getTeacherById(this.$route.params.id);
    this.retrieveSchools();
  },
});
</script>
<template>
  <div v-if="currentTeacher.teacherid" class="edit-form">
    <h4>Edit-Teacher</h4>
    <form>
      <div class="form-group">
        <label for="teachername">teacher name</label>
        <input
          type="text"
          class="form-control"
          id="teachername"
          v-model="currentTeacher.teachername"
        />
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <textarea
          class="form-control"
          id="address"
          required
          v-model="currentTeacher.address"
        ></textarea>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          v-model="currentTeacher.email"
        />
      </div>
      <div class="form-group">
        <label for="gender">Gender</label>
        <input
          type="text"
          class="form-control"
          id="gender"
          v-model="currentTeacher.gender"/>        
      </div>
      <label for="gender">Select Gender</label>      
      <div class="form-group">
  <input type="radio" id="Male" value="male" v-model="currentTeacher.gender">
  <label for="male">Male</label><br>
  <input type="radio" id="Female" value="female" v-model="currentTeacher.gender">
  <label for="female">Female</label><br>
  <input type="radio" id="others" value="others" v-model="currentTeacher.gender">
  <label for="Female">Others</label><br>
      </div>
      <h5>PRESENT SCHOOL LISTING:-</h5>
      <div
        class="form-check"
        v-for="(entry, index) in currentTeacher.school"
        :key="index"
      >
        <input
          type="checkbox"
          class="form-check-input"
          :fieldId="entry.schoolname"
          :label="entry.schoolname"          
          :checked="value.includes(entry.schoolid)"
          @click="removeSelectedSchoolFromTeacher(entry)"
        />{{ entry.schoolname }}
      </div>
      <br />
      <h5>CLICK TO ADD SCHOOL:-</h5>
      <div class="form-check" v-for="(entry, index) in schoolList" :key="index">
        <input
          type="checkbox"
          class="form-check-input"
          :fieldId="entry.schoolname"
          :label="entry.schoolname"
          :disabled="value.includes(entry.schoolid)"
          :checked="value.includes(entry.schoolid)"
          @click="removeSchoolInSchoolList(entry)"
        />{{ entry.schoolname }}
      </div>
      <!-- <div class="form-group">
        <label for="schools">Select School</label><br />
        <li v-for="(school, index) in schoolList" :key="index">
          <input
            type="checkbox"
            :fieldId="school.schoolname"
            :label="school.schoolname"
            :checked="value.includes(school.schoolid)"
          />
          <span>{{ school.schoolname }}</span>
        </li>
      </div> -->
    </form>
    <button class="badge badge-danger mr-2" @click="deleteTeacher">Delete</button>

    <button
      type="submit"
      class="badge badge-success mr-2"
      @click="updateTeacher()"
    >
      Update
    </button>

    <router-link
      :to="'/teacherslist'"
      class="badge badge-warning"
      custom
      v-slot="{ navigate }"
    >
      <button class="badge badge-primary mr-2" @click="navigate" role="link">
        Back
      </button>
    </router-link>
    <p>{{ message }}</p>
  </div>
  <div v-else>
    <br />
    <p>Please click on a Tutorial...</p>
  </div>
</template>
<style>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// druthvik/StudentManagement/client-reactjs/src/components/teacher/editteacher.component.tsx
/* eslint-disable react/require-render-return */
import { Component, ChangeEvent } from "react";
import { Link, RouteComponentProps } from "react-router-dom";
import schoolService from "../../services/school.service";
import teacherService from "../../services/teacher.service";
import ISchoolData from "../../types/school.types";
import { TeacherData } from "../../types/teacher.types";

interface RouterProps {
  id: string;
}
type Props = RouteComponentProps<RouterProps>;

type State = {
  currentTeacher: TeacherData;
  schools: Array<ISchoolData>;
};
const genderList = [{ value: "Male" }, { value: "Female" }];

export default class EditTeacher extends Component<Props, State> {
  schools: ISchoolData[] = [];
  currentTeacher = {} as TeacherData;
  currentSchool = {} as ISchoolData;
  removeSchool = {} as ISchoolData;
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.onChangePhoneNumber = this.onChangePhoneNumber.bind(this);
    this.onChangeEmail = this.onChangeEmail.bind(this);
    this.onChangeGender = this.onChangeGender.bind(this);
    this.updateTeacher = this.updateTeacher.bind(this);
    this.removeSchoolInSchoolList = this.removeSchoolInSchoolList.bind(this);
    this.removeSelectedSchoolFromTeacher =
      this.removeSelectedSchoolFromTeacher.bind(this);
    this.state = {
      currentTeacher: {
        teacherid: null,
        name: "",
        address: "",
        email: "",
        gender: "",
      },
      schools: [],
    };
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    const name = e.target.value;
    this.setState((prevState) => ({
      currentTeacher: {
        ...prevState.currentTeacher,
        name: name,
      },
    }));
  }
  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    const address = e.target.value;
    this.setState((prevState) => ({
      currentTeacher: {
        ...prevState.currentTeacher,
        address: address,
      },
    }));
  }
  onChangeEmail(e: ChangeEvent<HTMLInputElement>) {
    const email = e.target.value;
    this.setState((prevState) => ({
      currentTeacher: {
        ...prevState.currentTeacher,
        email: email,
      },
    }));
  }
  onChangeGender(e: ChangeEvent<HTMLInputElement>) {
    const gender = e.target.value;
    this.setState((prevState) => ({
      currentTeacher: {
        ...prevState.currentTeacher,
        gender: gender,
      },
    }));
  }
  onChangePhoneNumber(e: ChangeEvent<HTMLInputElement>) {
    const phonenumber = e.target.valueAsNumber;
    this.setState((prevState) => ({
      currentTeacher: {
        ...prevState.currentTeacher,
        phonenumber: phonenumber,
      },
    }));
  }
  retrieveSchools() {
    schoolService
      .getAll()
      .then((response: any) => {
        this.setState({
          schools: response.data,
        });
        this.schools = this.state.schools;
        console.log(this.schools);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  componentDidMount() {
    this.getTeacher(this.props.match.params.id);
    this.retrieveSchools();
  }
  getTeacher(id: string) {
    teacherService
      .get(id)
      .then((response: any) => {
        this.setState({
          currentTeacher: response.data,
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  updateTeacher() {
    teacherService
      .update(this.state.currentTeacher, this.state.currentTeacher.teacherid)
      .then((response: any) => {
        console.log(response.data);
        this.setState((prevState) => ({
          currentTeacher: {
            ...prevState.currentTeacher,
          },
          schools: {
            ...prevState.schools,
          },
          message: "The status was updated successfully!",
        }));
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  removeSchoolInSchoolList(school: ISchoolData) {
    this.currentSchool = school;
    this.state.currentTeacher.school?.push(this.currentSchool);
    this.state.schools.splice(
      this.state.schools.indexOf(this.currentSchool),
      1
    );
  }
  async removeSelectedSchoolFromTeacher(school: ISchoolData): Promise<void> {
    this.removeSchool = school;
    this.state.schools.push(this.removeSchool);
    this.state.currentTeacher.school?.splice(
      this.state.currentTeacher.school?.indexOf(this.removeSchool),
      1
    );
  }

  render() {
    const { currentTeacher, schools } = this.state;
    return (
      <div className="submit-form">
        <div>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={currentTeacher.name}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={currentTeacher.address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>
          <div className="form-group">
            <label htmlFor="phonenumber">Phonenumber</label>
            <input
              type="number"
              className="form-control"
              id="phonenumber"
              required
              value={currentTeacher.phonenumber}
              onChange={this.onChangePhoneNumber}
              name="name"
            />
          </div>
          <div className="form-group">
            <label htmlFor="name">Email</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={currentTeacher.email}
              onChange={this.onChangeEmail}
              name="name"
            />
          </div>
          <div className="title">
            <label htmlFor="name">Gender</label>
            {genderList.map((x, i) => (
              <label key={i}>
                <input
                  type="radio"
                  name="gender"
                  value={currentTeacher.gender}
                  onChange={this.onChangeGender}
                />{" "}
                {x.value}
              </label>
            ))}
          </div>
          <div className="form-group">
            <label>Current Schools</label>

            {currentTeacher.school?.map((school, i) => (
              <div key={i}>
                <input
                  type="checkbox"
                  name="schools"
                  value={school.name}
                  unselectable="on"
                  onChange={() => this.removeSelectedSchoolFromTeacher(school)}
                />{" "}
                {school.name}
              </div>
            ))}
          </div>
          <div className="form-group">
            <label>Schools</label>
            {schools?.map((school, i) => (
              <div key={i}>
                <input
                  type="checkbox"
                  name="schools"
                  value={currentTeacher.school}
                  onChange={() => this.removeSchoolInSchoolList(school)}
                />{" "}
                {school.name}
              </div>
            ))}
          </div>

          <Link to={"/teacherlist"}>
            <button
              onClick={this.updateTeacher}
              type="submit"
              className="btn badge-success"
            >
              Update
            </button>

            <button type="submit" className="btn badge-warning">
              Cancel
            </button>
          </Link>
        </div>
      </div>
    );
  }
}
