// Shubhankar/School/client vuejs/src/components/Editteacher.vue
<!-- eslint-disable prettier/prettier -->
<template>
<div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="teachername">Name</label>
        <input
          type="text"
          class="form-control"
          id="teachername"
          required
          v-model="selectedTeacher.teachername"
          name="teachername"
        />
      </div>

      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="selectedTeacher.address"
          name="address"
        />
      </div>

      <div class="form-group">
        <label for="phonenumber">Contact</label>
        <input
          type="text"
          class="form-control"
          id="phonenumber"
          required
          v-model="selectedTeacher.phonenumber"
          name="phonenumber"
        />
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          required
          v-model="selectedTeacher.email"
          name="email"
        />
      </div>

   <div class="form-group">
    <label for="gender">Gender</label><br>
  <input type="radio" id="Male" value="Male" v-model="selectedTeacher.gender">
  <label for="Male">Male</label><br>
  <input type="radio" id="Female" value="Female" v-model="selectedTeacher.gender">
  <label for="Female">Female</label><br>
  <input type="radio" id="Others" value="Others" v-model="selectedTeacher.gender">
  <label for="Female">Others</label><br>
  <span>Picked: {{ picked }}</span><br>
   </div>
      
<br />
       <div  class="form-group">
            <label for="schools">Select School</label><br>
            <li v-for="(school, index) in schools"
                  :key="index">
            <input type="checkbox" 
              :fieldId="school.schoolname"
              :label="school.schoolname"
              :checked="value.includes(school.schoolid)"
              v-on:change="addSchooltoTeacher(school)"
              :key="school"
              
               />
              <span>{{ school.schoolname }}</span>
              </li>
          </div>
        </div>
      </div>
      <button @click="updateTeacher" class="btn btn-success">Update</button>
      <button @click="listingPage" class="btn btn-danger">Cancel</button>
 
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import ResponseData from "@/types/ResponseData";
import School from "@/types/School";
import SchoolService from "@/services/SchoolService";
 import TeacherService from "@/services/TeacherService";
import Teacher from "@/types/Teacher";

export default defineComponent({
  name: "edit-teacher", 
  
  
  data() {
    return {
        schools:[] as School[],
         selectedTeacher: {} as Teacher,
          message: "",
          submitted: false,
          value : [] as number[],
          SelectedSchool:[] as School[],
          currentSchool: {} as School,
    };
},

methods: {
    updateTeacher() {  
       
     TeacherService.updateTeacher(this.selectedTeacher)
        .then((response: ResponseData) => {
          console.log(response.data);
           this.$router.replace('/teacher');
          this.message = "the teacher is updated";
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    retrieveTeachers(id: number) {
      TeacherService.createTeacherbyId(id)
        .then((response: ResponseData) => {
          this.selectedTeacher = response.data;
          for(const i of this.selectedTeacher.schools){
            this.value.push(i.schoolid);
          }
       
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    async addSchooltoTeacher(school: School): Promise<void> {
      if (!this.value.includes(school.schoolid)){
      this.currentSchool = school;
      this.selectedTeacher.schools?.push(this.currentSchool);
      }else{
     this.selectedTeacher.schools.splice(this.schools.indexOf(this.currentSchool), 1);
      }
    },
  
   retrieveSchools() {
      SchoolService.getAllSchool()
        .then((response: ResponseData) => {
          this.schools = response.data;
          
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
 listingPage(){
      this.$router.replace('/teacher');
    }
    
},
   mounted() {
    this.retrieveTeachers(this.$route.params.id);
    this.retrieveSchools();
 },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style src="vue-multiselect/dist/vue-multiselect.min.css">
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// druthvik/StudentManagement/client-reactjs/src/components/teacher/editteacher.component.tsx
/* eslint-disable react/require-render-return */
import { Component, ChangeEvent } from "react";
import { Link, RouteComponentProps } from "react-router-dom";
import schoolService from "../../services/school.service";
import teacherService from "../../services/teacher.service";
import ISchoolData from "../../types/school.types";
import { TeacherData } from "../../types/teacher.types";

interface RouterProps {
  id: string;
}
type Props = RouteComponentProps<RouterProps>;

type State = {
  currentTeacher: TeacherData;
  schools: Array<ISchoolData>;
};
const genderList = [{ value: "Male" }, { value: "Female" }];

export default class EditTeacher extends Component<Props, State> {
  schools: ISchoolData[] = [];
  currentTeacher = {} as TeacherData;
  currentSchool = {} as ISchoolData;
  removeSchool = {} as ISchoolData;
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.onChangePhoneNumber = this.onChangePhoneNumber.bind(this);
    this.onChangeEmail = this.onChangeEmail.bind(this);
    this.onChangeGender = this.onChangeGender.bind(this);
    this.updateTeacher = this.updateTeacher.bind(this);
    this.removeSchoolInSchoolList = this.removeSchoolInSchoolList.bind(this);
    this.removeSelectedSchoolFromTeacher =
      this.removeSelectedSchoolFromTeacher.bind(this);
    this.state = {
      currentTeacher: {
        teacherid: null,
        name: "",
        address: "",
        email: "",
        gender: "",
      },
      schools: [],
    };
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    const name = e.target.value;
    this.setState((prevState) => ({
      currentTeacher: {
        ...prevState.currentTeacher,
        name: name,
      },
    }));
  }
  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    const address = e.target.value;
    this.setState((prevState) => ({
      currentTeacher: {
        ...prevState.currentTeacher,
        address: address,
      },
    }));
  }
  onChangeEmail(e: ChangeEvent<HTMLInputElement>) {
    const email = e.target.value;
    this.setState((prevState) => ({
      currentTeacher: {
        ...prevState.currentTeacher,
        email: email,
      },
    }));
  }
  onChangeGender(e: ChangeEvent<HTMLInputElement>) {
    const gender = e.target.value;
    this.setState((prevState) => ({
      currentTeacher: {
        ...prevState.currentTeacher,
        gender: gender,
      },
    }));
  }
  onChangePhoneNumber(e: ChangeEvent<HTMLInputElement>) {
    const phonenumber = e.target.valueAsNumber;
    this.setState((prevState) => ({
      currentTeacher: {
        ...prevState.currentTeacher,
        phonenumber: phonenumber,
      },
    }));
  }
  retrieveSchools() {
    schoolService
      .getAll()
      .then((response: any) => {
        this.setState({
          schools: response.data,
        });
        this.schools = this.state.schools;
        console.log(this.schools);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  componentDidMount() {
    this.getTeacher(this.props.match.params.id);
    this.retrieveSchools();
  }
  getTeacher(id: string) {
    teacherService
      .get(id)
      .then((response: any) => {
        this.setState({
          currentTeacher: response.data,
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  updateTeacher() {
    teacherService
      .update(this.state.currentTeacher, this.state.currentTeacher.teacherid)
      .then((response: any) => {
        console.log(response.data);
        this.setState((prevState) => ({
          currentTeacher: {
            ...prevState.currentTeacher,
          },
          schools: {
            ...prevState.schools,
          },
          message: "The status was updated successfully!",
        }));
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  removeSchoolInSchoolList(school: ISchoolData) {
    this.currentSchool = school;
    this.state.currentTeacher.school?.push(this.currentSchool);
    this.state.schools.splice(
      this.state.schools.indexOf(this.currentSchool),
      1
    );
  }
  async removeSelectedSchoolFromTeacher(school: ISchoolData): Promise<void> {
    this.removeSchool = school;
    this.state.schools.push(this.removeSchool);
    this.state.currentTeacher.school?.splice(
      this.state.currentTeacher.school?.indexOf(this.removeSchool),
      1
    );
  }

  render() {
    const { currentTeacher, schools } = this.state;
    return (
      <div className="submit-form">
        <div>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={currentTeacher.name}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={currentTeacher.address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>
          <div className="form-group">
            <label htmlFor="phonenumber">Phonenumber</label>
            <input
              type="number"
              className="form-control"
              id="phonenumber"
              required
              value={currentTeacher.phonenumber}
              onChange={this.onChangePhoneNumber}
              name="name"
            />
          </div>
          <div className="form-group">
            <label htmlFor="name">Email</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={currentTeacher.email}
              onChange={this.onChangeEmail}
              name="name"
            />
          </div>
          <div className="title">
            <label htmlFor="name">Gender</label>
            {genderList.map((x, i) => (
              <label key={i}>
                <input
                  type="radio"
                  name="gender"
                  value={currentTeacher.gender}
                  onChange={this.onChangeGender}
                />{" "}
                {x.value}
              </label>
            ))}
          </div>
          <div className="form-group">
            <label>Current Schools</label>

            {currentTeacher.school?.map((school, i) => (
              <div key={i}>
                <input
                  type="checkbox"
                  name="schools"
                  value={school.name}
                  unselectable="on"
                  onChange={() => this.removeSelectedSchoolFromTeacher(school)}
                />{" "}
                {school.name}
              </div>
            ))}
          </div>
          <div className="form-group">
            <label>Schools</label>
            {schools?.map((school, i) => (
              <div key={i}>
                <input
                  type="checkbox"
                  name="schools"
                  value={currentTeacher.school}
                  onChange={() => this.removeSchoolInSchoolList(school)}
                />{" "}
                {school.name}
              </div>
            ))}
          </div>

          <Link to={"/teacherlist"}>
            <button
              onClick={this.updateTeacher}
              type="submit"
              className="btn badge-success"
            >
              Update
            </button>

            <button type="submit" className="btn badge-warning">
              Cancel
            </button>
          </Link>
        </div>
      </div>
    );
  }
}
