// shashi/student-task/vuejs/src/App.vue
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
/* eslint-disable prettier/prettier */
import { defineComponent } from "vue";
export default defineComponent({
  name: "App",
});
</script>
<template>
  <div id="app">
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <router-link to="/" class="navbar-brand">bezKoder</router-link>
      <div class="navbar-nav mr-auto">
        <li class="nav-item">
          <router-link to="/tutorials" class="nav-link">Tutorials</router-link>
        </li>
        <li class="nav-item">
          <router-link to="/add" class="nav-link">Add</router-link>
        </li>
        <li class="nav-item">
          <router-link to="/school" class="nav-link">Schoolist</router-link>
        </li>
        <li class="nav-item">
          <router-link to="/addschool" class="nav-link">CreateSchool</router-link>
        </li>
        <li class="nav-item">
          <router-link to="/studentlist" class="nav-link">Studentlist</router-link>
        </li>
        <li class="nav-item">
          <router-link to="/addstudent" class="nav-link">AddStudent</router-link>
        </li>
        <li class="nav-item">
          <router-link to="/teacherslist" class="nav-link">TeachersList</router-link>
        </li>
        <li class="nav-item">
          <router-link to="/addteacher" class="nav-link">CreateTeacher</router-link>
        </li>
      </div>
    </nav>
    <div class="container mt-3">
      <router-view />
    </div>
  </div>
</template>

// druthvik/StudentManagement/client-reactjs/src/App.tsx
import { Component } from "react";
import { Switch, Route, Link } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import "./App.css";
import AddSchool from "./components/school/school.component";
import SchoolList from "./components/school/schoollist.component";
class App extends Component {
  render() {
    return (
      <div>
        <nav className="navbar navbar-expand navbar-dark bg-dark">
          <Link to={"/tutorials"} className="navbar-brand">
            bezKoder
          </Link>
          <div className="navbar-nav mr-auto">
            <li className="nav-item">
              <Link to={"/school"} className="nav-link">
                Add school
              </Link>
            </li>
            <li className="nav-item">
              <Link to={"/schoollist"} className="nav-link">
                School List
              </Link>
            </li>
          </div>
        </nav>

        <div className="container mt-3">
          <Switch>
            <Route exact path={["/", "/schoollist"]} component={SchoolList} />
            <Route path="/school" component={AddSchool} />
            <Route path="/schoollist" component={SchoolList} />
          </Switch>
        </div>
      </div>
    );
  }
}

export default App;
