// adarsh/school/VUE-client/src/components/StudentEdit.vue
<template>
  <div v-if="currentStudent.id" class="edit-form">
    <h4>Student</h4>
    <form>
      <div class="form-group">
        <label for="title">Name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          v-model="currentStudent.name"
        />
      </div>
      <div class="form-group">
        <label for="address">Adresss</label>
        <input
          type="text"
          class="form-control"
          id="address"
          v-model="currentStudent.address"
        />
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          v-model="currentStudent.email"
        />
      </div>

      <div class="form-group">
        <label for="dateOfBirth">DATE</label>
        <input
          type="date"
          class="form-control"
          id="dateOfBirth"
          v-model="currentStudent.dateOfBirth"
        />
      </div>

      <label for="gender">GENDER</label>
      <div class="form-group">
        <input
          type="radio"
          id="MALE"
          value="MALE"
          v-model="currentStudent.gender"
        />
        <label for="MALE">Male</label><br />
        <input
          type="radio"
          id="FEMALE"
          value="FEMALE"
          v-model="currentStudent.gender"
        />
        <label for="FEMALE">Female</label><br />
      </div>

      <div class="form-group col-md-4">
        <label for="name">School : </label>
        <select
          class="select-option"
          required
          v-model="currentStudent.schools.id"
          @change="onSelectedSchool($event)"
        >
          <option
            class="option"
            v-for="(school, index) in schools"
            :key="index"
            :value="school.id"
          >
            {{ school.name }}
          </option>
        </select>
      </div>
      <br />
    </form>
    <button type="cancle" @click="updateStudent" class="btn btn-success">
      Update
    </button>
    <button type="cancle" class="btn btn-danger" @click="onCancle">
      cancle
    </button>
    <p>{{ message }}</p>
  </div>

  <div v-else>
    <br />
    <p>Please click on a Tutorial...</p>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import SchoolService from "@/services/SchoolService";
import { Student } from "@/types/student";
import { School } from "@/types/school";

@Component
export default class StudentEdit extends Vue {
  private message: string = "";
  currentSchool: School = new School();
  currentStudent: Student = {
    name: "",
    address: "",
    email: "",
    gender: "",
    dateOfBirth: "",
    schools: {},
  };

  genders: string[] = ["MALE", "FEMALE"];
  schools: School[] = [];
  schoolId: number[] = [];
  teacherId: number[] = [];

  getStudent(id: any) {
    SchoolService.getStudent(id)
      .then((response) => {
        this.currentStudent = response.data;
      })
      .catch((e) => {});
  }

  retrieveSchools() {
    SchoolService.getAllSchools()
      .then((response) => {
        this.schools = response.data;
      })
      .catch((e) => {});
    this.schoolId = this.schools.map((item) => {
      return item.id!;
    });
    const teacherId = this.schools.map((item) =>
      item.teachers?.map((item) => item.id)
    );
  }

  updateStudent() {
    SchoolService.updateStudent(this.currentStudent.id!, this.currentStudent)
      .then((response) => {
        this.message = "The tutorial was updated successfully!";
      })
      .catch((e) => {});
  }

  async onSelectedSchool(school: string) {
    const data = this.schools.filter((s) => s.id === +school);
    this.currentSchool = data[0];
  }

  onCancle() {
    this.$router.replace("/student");
  }

  mounted() {
    this.message = "";
    this.getStudent(this.$route.params.id);
    this.retrieveSchools();
  }
}
</script>

<style scoped>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// druthvik/StudentManagement/client-reactjs/src/components/students/studentedit.component.tsx
import { Component, ChangeEvent } from "react";
import { Link, RouteComponentProps } from "react-router-dom";
import { IStudentData } from "../../types/student.types";
import studentService from "../../services/student.service";
import schoolService from "../../services/school.service";
import ISchoolData from "../../types/school.types";
interface RouterProps {
  // type for `match.params`
  id: string; // must be type `string` since value comes from the URL
}
type Props = RouteComponentProps<RouterProps>;
type State = {
  currentStudent: IStudentData;
  school?: Array<ISchoolData>;
};

export default class studentedit extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.onChangeEmail = this.onChangeEmail.bind(this);
    this.onChangeGender = this.onChangeGender.bind(this);
    this.onChangeDateOfBirth = this.onChangeDateOfBirth.bind(this);
    this.updateStudents = this.updateStudents.bind(this);
    this.state = {
      currentStudent: {
        studentid: 0,
        name: "",
        address: "",
        email: "",
        gender: "",
        dateofbirth: "",
      },
      school: [],
    };
  }
  componentDidMount() {
    this.getStudentById(this.props.match.params.id);
    this.retrieveSchools();
  }
  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    const name = e.target.value;

    this.setState((prevState) => ({
      currentStudent: {
        ...prevState.currentStudent,
        name: name,
      },
    }));
  }
  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    const address = e.target.value;

    this.setState((prevState) => ({
      currentStudent: {
        ...prevState.currentStudent,
        address: address,
      },
    }));
  }
  onChangeEmail(e: ChangeEvent<HTMLInputElement>) {
    const email = e.target.value;

    this.setState((prevState) => ({
      currentStudent: {
        ...prevState.currentStudent,
        email: email,
      },
    }));
  }
  onChangeGender(e: ChangeEvent<HTMLInputElement>) {
    const gender = e.target.value;

    this.setState((prevState) => ({
      currentStudent: {
        ...prevState.currentStudent,
        gender: gender,
      },
    }));
  }
  onChangeDateOfBirth(e: ChangeEvent<HTMLInputElement>) {
    const dateofbirth = e.target.value;

    this.setState((prevState) => ({
      currentStudent: {
        ...prevState.currentStudent,
        dateofbirth: dateofbirth,
      },
    }));
  }

  getStudentById(id: string) {
    studentService
      .getStudentById(id)
      .then((response) => {
        this.setState({
          currentStudent: response.data,
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  retrieveSchools() {
    schoolService
      .getAllSchools()
      .then((response) => {
        this.setState({
          school: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  updateStudents() {
    studentService
      .updateStudent(
        this.state.currentStudent,
        this.state.currentStudent.studentid
      )
      .then((response) => {
        console.log(response.data);
        this.setState((prevState) => ({
          currentStudent: {
            ...prevState.currentStudent,
          },
          message: "The status was updated successfully!",
        }));
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  render() {
    const { currentStudent } = this.state;

    return (
      <div>
        {currentStudent ? (
          <div className="edit-form">
            <h4>Student</h4>
            <form>
              <div className="form-group">
                <label htmlFor="title">Name</label>
                <input
                  type="text"
                  className="form-control"
                  id="title"
                  value={currentStudent.name}
                  onChange={this.onChangeName}
                />
              </div>
              <div className="form-group">
                <label htmlFor="description">Address</label>
                <input
                  type="text"
                  className="form-control"
                  id="description"
                  value={currentStudent.address}
                  onChange={this.onChangeAddress}
                />
              </div>
              <div className="form-group">
                <label htmlFor="description">Email</label>
                <input
                  type="text"
                  className="form-control"
                  id="description"
                  value={currentStudent.email}
                  onChange={this.onChangeEmail}
                />
              </div>

              <div className="title">Select gender from the list</div>
              <label>
                <input
                  type="radio"
                  name="gender"
                  value={currentStudent.gender}
                  checked
                  onChange={this.onChangeGender}
                />{" "}
                {currentStudent.gender}
              </label>
              <div className="form-group">
                <label htmlFor="date">DOB</label>

                <input
                  type="date"
                  className="form-control"
                  value={currentStudent.dateofbirth}
                  onChange={this.onChangeDateOfBirth}
                  name="date"
                />
              </div>
              <div className="form-group">
                <select>
                  <option
                    key={currentStudent.school?.schoolid}
                    value={currentStudent.school?.name}
                  >
                    {currentStudent.school?.name}
                  </option>
                </select>
              </div>
            </form>
            <Link to={"/studentlist"}>
              <button
                onClick={this.updateStudents}
                type="submit"
                className="btn badge-success"
              >
                Update
              </button>

              <button type="submit" className="btn badge-warning">
                Cancel
              </button>
            </Link>
          </div>
        ) : (
          <div>
            <br />
          </div>
        )}
      </div>
    );
  }
}
