// Shubhankar/School/client vuejs/src/components/AddTutorial.vue
<script lang="ts">
import { defineComponent } from "vue";
import TutorialDataService from "@/services/TutorialDataService";
import Tutorial from "@/types/Tutorial";
import ResponseData from "@/types/ResponseData";

export default defineComponent({
  name: "add-tutorial",
  data() {
    return {
      tutorial: {
        id: null,
        title: "",
        description: "",
        published: false,
      } as Tutorial,
      submitted: false,
    };
  },
  methods: {
    saveTutorial() {
      let data = {
        title: this.tutorial.title,
        description: this.tutorial.description,
      };

      TutorialDataService.create(data)
        .then((response: ResponseData) => {
          this.tutorial.id = response.data.id;
          console.log(response.data);
          this.submitted = true;
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    newTutorial() {
      this.submitted = false;
      this.tutorial = {} as Tutorial;
    },
  },
});
</script>

<style>
.submit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// harsha/Tutorial/client/src/app/components/add-tutorial/add-tutorial.component.ts
import { Component, OnInit } from '@angular/core'
import { Tutorial } from 'src/app/models/tutorial.model'
import { TutorialService } from 'src/app/services/tutorial.service'

@Component({
  selector: 'app-add-tutorial',
  templateUrl: './add-tutorial.component.html',
  styleUrls: ['./add-tutorial.component.css'],
})
export class AddTutorialComponent implements OnInit {
  tutorial: Tutorial = {
    title: '',
    description: '',
    // published: false,
  }
  submitted = false

  constructor(private tutorialService: TutorialService) {}

  ngOnInit(): void {}

  // saveTutorial(): void {
  //   const data = {
  //     title: this.tutorial.title,
  //     description: this.tutorial.description,
  //   }

  //   this.tutorialService.create(data).subscribe(
  //     (response) => {
  //       console.log(response)
  //       this.submitted = true
  //     },
  //     (error) => {
  //       console.log(error)
  //     },
  //   )
  // }

  newTutorial(): void {
    this.submitted = false
    this.tutorial = {
      title: '',
      description: '',
      // published: false,
    }
  }
}
