// harsha/School-Teacher-Student/client/src/app/components/create-school/create-school.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { IDropdownSettings } from 'ng-multiselect-dropdown';
import { School } from 'src/app/models/school.model';
import { Student } from 'src/app/models/student.model';
import { Teacher } from 'src/app/models/teacher.model';
import { SchoolService } from 'src/app/services/school.service';
import { StudentService } from 'src/app/services/student.service';
import { TeacherService } from 'src/app/services/teacher.service';

@Component({
  selector: 'app-create-school',
  templateUrl: './create-school.component.html',
  styleUrls: ['./create-school.component.css'],
})
export class CreateSchoolComponent implements OnInit {
  registerForm!: FormGroup;
  submitted: boolean = false;
  teachers: Teacher[] = [];
  addedTeachers: Teacher[] = [];
  selectedTeacher?: Teacher = {};
  students: Student[] = [];
  addedStudents: Student[] = [];
  selectedStudent?: Student = {};
  dropdownSettingsForTeacher: IDropdownSettings = {};
  dropdownSettings: IDropdownSettings = {};
  id?: number;
  addForm?: boolean;
  currentSchool: School = {
    schoolName: '',
    address: '',
    teachers: [],
    students: [],
  };
  constructor(
    private schoolService: SchoolService,
    private teacherService: TeacherService,
    private studentService: StudentService,
    private router: Router,
    private formBuilder: FormBuilder,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.registerForm = this.formBuilder.group({
      schoolName: ['', Validators.required],
      address: ['', Validators.required],
      teachers: ['', Validators.required],
      students: ['', Validators.required],
    });
    this.getTeachers();
    this.getStudents();
    this.getSchoolById(this.route.snapshot.params.id);
    this.dropdownSettingsForTeacher = {
      idField: 'teacherId',
      textField: 'teacherName',
    };
    this.dropdownSettings = {
      idField: 'studentId',
      textField: 'studentName',
    };
    this.id = this.route.snapshot.params.id;
    this.addForm = !this.id;
  }

  get validation() {
    return this.registerForm.controls;
  }

  signup() {
    this.submitted = true;
    if (this.registerForm.invalid) {
      return;
    }
    alert('form fields are validated successfully!');
    this.saveSchool();
  }

  async getTeachers(): Promise<void> {
    this.teachers = await this.teacherService.getTeachers();
  }

  async getStudents(): Promise<void> {
    this.students = await this.studentService.getStudents();
  }

  async getSchoolById(id: number) {
    this.currentSchool = await this.schoolService.getSchoolById(id);
  }

  async onSelectingTeacher(teacher: any): Promise<void> {
    this.selectedTeacher = teacher;
    this.addedTeachers.push(this.selectedTeacher!);
  }

  onSelectAllTeachers(teachers: any) {
    this.selectedTeacher = teachers;
    this.addedTeachers.push(this.selectedTeacher!);
  }

  async onSelectingStudent(student: any): Promise<void> {
    this.selectedStudent = student;
    this.addedStudents.push(this.selectedStudent!);
  }

  onSelectAllStudents(students: any) {
    this.selectedStudent = students;
    this.addedStudents?.push(this.selectedStudent!);
  }

  async saveSchool(): Promise<void> {
    const school: School = {
      schoolName: this.currentSchool.schoolName,
      address: this.currentSchool.address,
      teachers: this.addedTeachers,
      students: this.addedStudents,
    };
    await this.schoolService.createSchool(school);
    this.router.navigate(['/school-list']);
  }

  async updateSchool(): Promise<void> {
    const school: School = {
      schoolId: this.currentSchool.schoolId,
      schoolName: this.currentSchool.schoolName,
      address: this.currentSchool.address,
      teachers: this.addedTeachers,
      students: this.addedStudents,
    };
    await this.schoolService.updateSchool(this.currentSchool.schoolId!, school);
    this.router.navigate(['/school-list']);
  }
}

<h2 *ngIf="addForm" class="text-center">ADD SCHOOL</h2>
<h2 *ngIf="!addForm" class="text-center">EDIT SCHOOL</h2>
<div class="form">
  <form [formGroup]="registerForm">
    <div class="form-group">
      <label for="schoolName">Name</label>
      <input type="schoolName" formControlName="schoolName" class="form-control item"
        [(ngModel)]="currentSchool.schoolName"
        [ngClass]="{ 'is-invalid': submitted && validation.schoolName.errors }" />
      <div *ngIf="this.submitted && validation.schoolName.errors" class="invalid-feedback">
        <div *ngIf="validation.schoolName.errors.required">
          Name Field is required
        </div>
      </div>
    </div>

    <div class="form-group">
      <label for="address">Address</label>
      <input type="address" formControlName="address" class="form-control item" [(ngModel)]="currentSchool.address"
        [ngClass]="{ 'is-invalid': submitted && validation.address.errors }" />
      <div *ngIf="this.submitted && validation.address.errors" class="invalid-feedback">
        <div *ngIf="validation.address.errors.required">
          Address Field is required
        </div>
      </div>
    </div>

    <div class="form-group">
      <ng-multiselect-dropdown [placeholder]="'Select Teachers'" formControlName="teachers" name="teachers"
        [settings]="dropdownSettingsForTeacher" [data]="teachers" (onSelect)="onSelectingTeacher($event)"
        (onSelectAll)="onSelectAllTeachers($event)" [(ngModel)]="currentSchool.teachers">
      </ng-multiselect-dropdown>
    </div>

    <div class="form-group">
      <ng-multiselect-dropdown [placeholder]="'Select Students'" name="students" formControlName="students"
        [settings]="dropdownSettings" [data]="students" (onSelect)="onSelectingStudent($event)"
        (onSelectAll)="onSelectAllStudents($event)" [(ngModel)]="currentSchool.students">
      </ng-multiselect-dropdown>
    </div>

    <button *ngIf="addForm" type="button" class="btn btn-success" (click)="signup()">
      Save
    </button>
    <button *ngIf="!addForm" type="button" class="btn btn-success" (click)="updateSchool()">
      Update
    </button>
    <button type=" button" class="btn btn-warning" routerLink="/school-list">Cancel</button>
  </form>
</div>

// Shubhankar/School/client vuejs/src/components/Createschool.vue
<!-- eslint-disable prettier/prettier -->
<template>
   <div class="submit-form">   
    <div>
      <div class="form-group">
        <label for="schoolname">Name</label>
        <input
          type="text"
          class="form-control"
          id="schoolname"
          required
          v-model="school.schoolname"
          name="schoolname"
        />
      </div>

      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="school.address"
          name="address"
        />
      </div>
      
    <div class="form-group">
   <label for="teachers">Teacher</label>
    <multiselect
     class="form-control"
       id="teachers"
        required
      v-model="selectedteacher"
       name="teachers"
      :options="teacher"
      :multiple="true"
      :close-on-select="false"
      :clear-on-select="false" 
      :preserve-search="true"
       placeholder="Pick some"
        label="teachername" 
        track-by="teachername" 
        :preselect-first="true" >
    </multiselect>
  </div>

  <div class="form-group">
   <label for="teachers">Student</label>
    <multiselect
     class="form-control"
       id="students"
       required
      v-model=" selectedstudent"
       name="students"
      :options="student"
      :multiple="true" 
      :close-on-select="false"
      :preserve-search="true"
       placeholder="Pick some"
        label="studentname" 
        track-by="studentname" 
        :preselect-first="true">
    </multiselect>
  </div>
    <button @click="saveSchool" class="btn btn-success">Submit</button>
    <button @click="listingPage" class="btn btn-danger">Cancel</button>
    </div>
  </div>
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import School from "@/types/School";
import SchoolService from "@/services/SchoolService";
import Multiselect from '@suadelabs/vue3-multiselect'
import TeacherService from "@/services/TeacherService";
import Teacher from "@/types/Teacher";
import StudentService from "@/services/StudentService";
import Student from "@/types/Student";

export default defineComponent({

  name: "add-school", 
  components: { Multiselect },

  data() {
    return {
        teacher: [] as Teacher[],
        student:[] as Student[],
        school: {
        schoolname: "",
        address: "",
       } as School,
      submitted: false,
       selectedteacher: [],
       selectedstudent: [],
    };
},
 
 methods: {
    saveSchool() {
      let data = {
        schoolid: this.school.schoolid,
        schoolname: this.school.schoolname,
        address: this.school.address,
        teachers:this.selectedteacher,
        students:this. selectedstudent,
    };

      SchoolService.createSchool(data)
        .then((response) => {
          this.school.schoolid = response.data.schoolid;
          console.log(response.data);
          this.submitted = true;
           this.$router.replace('/school');
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    retrieveTeachers() {
      TeacherService.getAllTeachers()
        .then((response) => {
          this.teacher = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

     retrieveStudents() {
      StudentService.getAllStudents()
        .then((response) => {
          this.student = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    listingPage(){
      this.$router.replace('/school');
    }
},
   mounted() {
    this.retrieveTeachers();
    this.retrieveStudents();

 },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style src="vue-multiselect/dist/vue-multiselect.min.css">
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
