// Shubhankar/School/client/src/app/components/createschool/createschool.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { IDropdownSettings } from 'ng-multiselect-dropdown';
import { School } from 'src/app/models/school';
import { Student } from 'src/app/models/student';
import { Teacher } from 'src/app/models/teacher';
import { SchoolService } from 'src/app/services/school.service';

@Component({
  selector: 'app-createschool',
  templateUrl: './createschool.component.html',
  styleUrls: ['./createschool.component.css'],
})
export class CreateschoolComponent implements OnInit {
  createSchool!: FormGroup;
  submitted: boolean = false;
  dropdownSettings: IDropdownSettings = {};
  dropdownSettingstudent: IDropdownSettings = {};

  id?: number;
  isAddMode?: boolean;

  school: School = {
    schoolname: '',
    address: '',
    teachers: [],
    students: [],
  };
  teachers: Teacher[] = [];
  students: Student[] = [];
  currentTeacher!: Teacher;
  AddedTeachers: Teacher[] = [];
  currentStudent!: Student;
  AddedStudent: Student[] = [];
  
  constructor(
    private schoolService: SchoolService,
    private router: Router,
    private route: ActivatedRoute,
    private formBuilder: FormBuilder
  ) {}

  ngOnInit(): void {
    this.createSchool = this.formBuilder.group({
      schoolname: ['', Validators.required],
      address: ['', Validators.required],
      teachers: ['', Validators.required],
      students: ['', Validators.required],
    });
   
    this.dropdownSettings = {
      idField: 'teacherid',
      textField: 'teachername',
      itemsShowLimit: 3,
      allowSearchFilter: true
    };

    this.retrieveTeachers();
    this.dropdownSettingstudent = {
      idField: 'studentid',
      textField: 'studentname',
      itemsShowLimit: 3,
      allowSearchFilter: true
    };

    this.retrieveStudents();
    this.retrieveSchool(this.route.snapshot.params.id);

    this.id = this.route.snapshot.params['id'];
    this.isAddMode = !this.id;
  }

  async retrieveTeachers(): Promise<void> {
    this.teachers = await this.schoolService.getallTeachers();
  }

  async retrieveStudents(): Promise<void> {
    this.students = await this.schoolService.getallStudents();
  }

  async selectedTeacher(teacher: any): Promise<void> {
    this.currentTeacher = teacher;
    this.AddedTeachers?.push(this.currentTeacher);
  }

  async selectedStudent(student: any): Promise<void> {
    this.currentStudent = student;
    this.AddedStudent?.push(this.currentStudent);
  }

  get fval() {
    return this.createSchool.controls;
  }

  async saveSchool() {
    this.submitted = true;
    if (this.createSchool.invalid) {
      return;
    }
    this.getSubmit();
  }

  async getSubmit() {
    this.submitted = true;
    const schoolinfo: School = {
      schoolname: this.school.schoolname,
      address: this.school.address,
      teachers: this.AddedTeachers,
      students: this.AddedStudent,
    };
    await this.schoolService.createSchool(schoolinfo);
    this.router.navigate(['school-list']);
  }

  getBack() {
    this.router.navigate(['school-list']);
  }

  async retrieveSchool(id: number): Promise<void> {
    this.school = await this.schoolService.getSchoolbyid(id);
  }

  async updateSchool() {
    this.submitted = true;
    if (this.createSchool.invalid) {
      return;
    }
    this.getUpdated();
  }

  async getUpdated() {
    this.submitted = true;
    const schoolinfo: School = {
      schoolid:this.school.schoolid,
      schoolname: this.school.schoolname,
      address: this.school.address,
      teachers: this.AddedTeachers,
      students: this.AddedStudent,
    };
    await this.schoolService.updateSchool(schoolinfo);
    this.router.navigate(['school-list']);
  }
}

<div class="row">
  <div class="col-md-4 offset-md-3 col-md-6 col-sm-offset-2 col-sm-8">
    <h4 *ngIf="isAddMode">Add School</h4>
    <h4 *ngIf="!isAddMode">Edit School</h4>
    <form [formGroup]="createSchool" (ngSubmit)="updateSchool()">
      <div class="form-group">
        <label for="schoolname">schoolName</label>
        <input
          type="schoolname"
          class="form-control"
          id="schoolname"
          formControlName="schoolname"
          [(ngModel)]="school.schoolname"
          [ngClass]="{ 'is-invalid': submitted && fval.schoolname.errors }"
        />
        <div
          *ngIf="submitted && fval.schoolname.errors"
          class="invalid-feedback"
        >
          <div *ngIf="fval.schoolname.errors.required">
            Name Field is required
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <input
          type="address"
          class="form-control"
          id="address"
          formControlName="address"
          [(ngModel)]="school.address"
          [ngClass]="{ 'is-invalid': submitted && fval.address.errors }"
        />
        <div *ngIf="submitted && fval.address.errors" class="invalid-feedback">
          <div *ngIf="fval.address.errors.required">
            Address Field is required
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="teachers">Teacher</label>
        <ng-multiselect-dropdown
        type="teachers"
        class="form-control"
        id="teachers"
         formControlName="teachers"
          [(ngModel)]="school.teachers"
          [settings]="dropdownSettings"
          [data]="teachers"
          (onSelect)="selectedTeacher($event)"
          [ngClass]="{ 'is-invalid': submitted && fval.teachers.errors }"
          
        >
        <div *ngIf="submitted && fval.teachers.errors" class="invalid-feedback">
          <div *ngIf="fval.teachers.errors.required">
            Teacher Field is required
          </div>
        </div>
      

        </ng-multiselect-dropdown>
      </div>
      <div class="form-group">
        <label for="students">Student</label>
        <ng-multiselect-dropdown
        type="students"
        class="form-control"
        id="students"
          formControlName="students"
          [(ngModel)]="school.students"
          [settings]="dropdownSettingstudent"
          [data]="students"
          (onSelect)="selectedStudent($event)"
         [ngClass]="{ 'is-invalid': submitted && fval.students.errors }"
        >
        <div *ngIf="submitted && fval.students.errors" class="invalid-feedback">
          <div *ngIf="fval.students.errors.required">
            Student Field is required
          </div>
        </div>

        </ng-multiselect-dropdown>
      </div>
      <button
      type="button"  *ngIf="isAddMode"
      class="btn btn-outline-success"
      (click)="saveSchool()"
    >
      Save
    </button>
      <button *ngIf="!isAddMode"
        type="button"
        class="btn btn-outline-success"
        (click)="updateSchool()"
      >
        Update
      </button>
      <button type="button" class="btn btn-outline-danger" (click)="getBack()">
        Cancel
      </button>
    </form>
  </div>
</div>

// Shubhankar/School/client vuejs/src/components/Createschool.vue
<!-- eslint-disable prettier/prettier -->
<template>
   <div class="submit-form">   
    <div>
      <div class="form-group">
        <label for="schoolname">Name</label>
        <input
          type="text"
          class="form-control"
          id="schoolname"
          required
          v-model="school.schoolname"
          name="schoolname"
        />
      </div>

      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="school.address"
          name="address"
        />
      </div>
      
    <div class="form-group">
   <label for="teachers">Teacher</label>
    <multiselect
     class="form-control"
       id="teachers"
        required
      v-model="selectedteacher"
       name="teachers"
      :options="teacher"
      :multiple="true"
      :close-on-select="false"
      :clear-on-select="false" 
      :preserve-search="true"
       placeholder="Pick some"
        label="teachername" 
        track-by="teachername" 
        :preselect-first="true" >
    </multiselect>
  </div>

  <div class="form-group">
   <label for="teachers">Student</label>
    <multiselect
     class="form-control"
       id="students"
       required
      v-model=" selectedstudent"
       name="students"
      :options="student"
      :multiple="true" 
      :close-on-select="false"
      :preserve-search="true"
       placeholder="Pick some"
        label="studentname" 
        track-by="studentname" 
        :preselect-first="true">
    </multiselect>
  </div>
    <button @click="saveSchool" class="btn btn-success">Submit</button>
    <button @click="listingPage" class="btn btn-danger">Cancel</button>
    </div>
  </div>
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import School from "@/types/School";
import SchoolService from "@/services/SchoolService";
import Multiselect from '@suadelabs/vue3-multiselect'
import TeacherService from "@/services/TeacherService";
import Teacher from "@/types/Teacher";
import StudentService from "@/services/StudentService";
import Student from "@/types/Student";

export default defineComponent({

  name: "add-school", 
  components: { Multiselect },

  data() {
    return {
        teacher: [] as Teacher[],
        student:[] as Student[],
        school: {
        schoolname: "",
        address: "",
       } as School,
      submitted: false,
       selectedteacher: [],
       selectedstudent: [],
    };
},
 
 methods: {
    saveSchool() {
      let data = {
        schoolid: this.school.schoolid,
        schoolname: this.school.schoolname,
        address: this.school.address,
        teachers:this.selectedteacher,
        students:this. selectedstudent,
    };

      SchoolService.createSchool(data)
        .then((response) => {
          this.school.schoolid = response.data.schoolid;
          console.log(response.data);
          this.submitted = true;
           this.$router.replace('/school');
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    retrieveTeachers() {
      TeacherService.getAllTeachers()
        .then((response) => {
          this.teacher = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

     retrieveStudents() {
      StudentService.getAllStudents()
        .then((response) => {
          this.student = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    listingPage(){
      this.$router.replace('/school');
    }
},
   mounted() {
    this.retrieveTeachers();
    this.retrieveStudents();

 },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style src="vue-multiselect/dist/vue-multiselect.min.css">
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
