// shashi/student-task/client/src/app/components/create-teacher/create-teacher.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { School } from 'src/app/models/school.model';
import { Teacher } from 'src/app/models/teacher.model';
import { SchoolService } from 'src/app/services/student-task-service';
import { Gender } from 'src/app/services/student-task-service';

@Component({
  selector: 'app-create-teacher',
  templateUrl: './create-teacher.component.html',
  styleUrls: ['./create-teacher.component.css'],
})
export class CreateTeacherComponent implements OnInit {
  schoolsList: School[] = [];
  currentSchool!: School;
  selectedSchool: School[] = [];
  createTeacherForm!: FormGroup;
  submitted = false;
  teacher: Teacher = {
    teachername: '',
    address: '',
    email: '',
    gender: '',
    school: [],
  };
  gendersList?: string[];
  currentGender!: string;
  selectedGender!: any;
  model = { option: 'option3' };
  ischecked?: boolean;
  constructor(
    private schoolService: SchoolService,
    private formBuilder: FormBuilder,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    if (this.route.snapshot.params.id) {
      this.getTeacherById(this.route.snapshot.params.id);
    }
    this.createTeacherForm = this.formBuilder.group({
      teachername: ['', Validators.required],
      address: ['', Validators.required],
      email: ['', Validators.required],
      gender: ['', Validators.required],
      school: ['', Validators.required],
    });
    this.retieveGenders();
    this.retrieveschools();
  }
  get formValidation() {
    return this.createTeacherForm.controls;
  }
  retieveGenders() {
    this.gendersList = this.schoolService.genderList;
  }
  async retrieveschools(): Promise<void> {
    this.schoolsList = await this.schoolService.getSchools();
  }
  async checkValidation(): Promise<void> {
    this.submitted = true;
    if (this.createTeacherForm.invalid) {
      return;
    } else {
      this.saveTeacherDetails();
    }
  }
  async saveTeacherDetails(): Promise<void> {
    const teacherData: Teacher = {
      teachername: this.teacher.teachername,
      address: this.teacher.address,
      email: this.teacher.email,
      gender: this.teacher.gender,
      school: this.selectedSchool,
    };
    await this.schoolService.createTeacher(teacherData);
    this.router.navigate(['/teacherslist']);
  }
  getSelectedTeacherGender(gender: string) {
    this.currentGender = gender;
  }
  async selectedSchoolMethod(school: School): Promise<void> {
    this.currentSchool = school;
    this.selectedSchool?.push(this.currentSchool);
  }

  async getTeacherById(id: number): Promise<void> {
    this.teacher = await this.schoolService.getTeacherById(id);
    this.teacherSchool(this.currentSchool);
  }
  async teacherSchool(school: School) {
    if ((this.ischecked = true)) {
      console.log(school);
      const data = this.teacher.school?.filter(
        (s) => s.schoolid === school.schoolname
      );
      //this.currentSchool = data[0];
    }
  }
  async updateTeacher(): Promise<void> {
    const teacherData: Teacher = {
      teacherid: this.teacher.teacherid,
      teachername: this.teacher.teachername,
      address: this.teacher.address,
      email: this.teacher.email,
      gender: this.teacher.gender,
      school: this.teacher.school,
    };
    await this.schoolService.updateTeacher(teacherData);
  }
}

<div class="container">
  <h5 class="card-title text-center pb-0 fs-4">Create Teacher</h5>
  <br />
  <div class="row">
    <div class="col-md-6 offset-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <form [formGroup]="createTeacherForm" (ngSubmit)="checkValidation()">
            <div class="form-group">
              <label>teacher name</label>
              <input
                type="text"
                formControlName="teachername"
                name="teachername"
                class="form-control"
                [ngClass]="{
                  'is-invalid': submitted && formValidation.teachername.errors
                }"
                [(ngModel)]="teacher.teachername"
              />
              <div
                *ngIf="submitted && formValidation.teachername.errors"
                class="invalid-feedback"
              >
                <div *ngIf="formValidation.teachername.errors.required">
                  teacher name is required
                </div>
              </div>
            </div>
            <br />
            <div class="form-group">
              <label>Address</label>
              <input
                type="text"
                formControlName="address"
                name="address"
                class="form-control"
                [ngClass]="{
                  'is-invalid': submitted && formValidation.address.errors
                }"
                [(ngModel)]="teacher.address"
              />
              <div
                *ngIf="submitted && formValidation.address.errors"
                class="invalid-feedback"
              >
                <div *ngIf="formValidation.address.errors.required">
                  address is required
                </div>
              </div>
            </div>
            <br />
            <div class="form-group">
              <label>Email</label>
              <input
                type="text"
                formControlName="email"
                class="form-control"
                [ngClass]="{
                  'is-invalid': submitted && formValidation.email.errors
                }"
                [(ngModel)]="teacher.email"
              />
              <div
                *ngIf="submitted && formValidation.email.errors"
                class="invalid-feedback"
              >
                <div *ngIf="formValidation.email.errors.required">
                  email is required
                </div>
              </div>
            </div>
            <br />
            <div class="column">
              <label for="options">select gender:</label>
              <div *ngFor="let gender of gendersList">
                <input
                  name="gender"
                  formControlName="gender"
                  type="radio"
                  [value]="gender"
                  [(ngModel)]="teacher.gender"
                  [ngClass]="{
                    'is-invalid': submitted && formValidation.gender.errors
                  }"
                />{{ gender }}
                <div
                  *ngIf="submitted && formValidation.gender.errors"
                  class="invalid-feedback"
                >
                  <div *ngIf="formValidation.gender.errors.required">
                    gender is required
                  </div>
                </div>
              </div>
            </div>
            <div class="column">
              <label for="options">schoolsList:</label>
              <div *ngFor="let school of schoolsList">
                <input
                  name="options"
                  formControlName="school"
                  type="checkbox"
                  (ngModelChange)="teacherSchool($event)"
                  checked="ischecked"
                  [ngClass]="{
                    'is-invalid': submitted && formValidation.school.errors
                  }"
                  (click)="selectedSchoolMethod(school)"
                />{{ school.schoolname }}
                <div
                  *ngIf="submitted && formValidation.school.errors"
                  class="invalid-feedback"
                >
                  <div *ngIf="formValidation.school.errors.required">
                    school is required
                  </div>
                </div>
              </div>
            </div>
            <br />
            <div class="text-center">
              <button class="btn btn-primary btn-sm">Submit</button>
              <button
                class="btn btn-outline-success btn-sm btn-space"
                routerLink="/teacherslist"
                (click)="updateTeacher()"
              >
                Update
              </button>
              <button
                class="btn btn-danger btn-sm btn-space"
                routerLink="/teacherslist"
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
        <br />
      </div>
    </div>
  </div>
</div>

// Shubhankar/School/client vuejs/src/components/CreateTeacher.vue
<!-- eslint-disable prettier/prettier -->
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="teachername">Name</label>
        <input
          type="text"
          class="form-control"
          id="teachername"
          required
          v-model="teacher.teachername"
          name="teachername"
        />
      </div>

      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="teacher.address"
          name="address"
        />
      </div>

      <div class="form-group">
        <label for="phonenumber">Contact</label>
        <input
          type="text"
          class="form-control"
          id="phonenumber"
          required
          v-model="teacher.phonenumber"
          name="phonenumber"
        />
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          required
          v-model="teacher.email"
          name="email"
        />
      </div>

   <div class="form-group">
    <label for="gender">Gender</label><br>
  <input type="radio" id="Male" value="Male" v-model="picked">
  <label for="Male">Male</label><br>
  <input type="radio" id="Female" value="Female" v-model="picked">
  <label for="Female">Female</label><br>
  <input type="radio" id="Others" value="Others" v-model="picked">
  <label for="Female">Others</label><br>
  <span>Picked: {{ picked }}</span><br>
   </div>
  
         <div class="form-group">
    <label for="schools">Select School</label><br>
      <ul class="object administrator-checkbox-list">
          <li  :class="{ active: index == currentIndex }"
           v-for="(school, index) in schools"
        :key="index">
             <label v-bind:for="school.schoolid">
        <div  >
          <input type="checkbox" v-model="selectedSchool" v-bind:value="school">
            <span>{{ school.schoolname }}</span>
        </div>
        </label>
    </li>
      </ul>
         </div>
          
        </div>
      </div>

      <button @click="saveTeacher" class="btn btn-success">Submit</button>
      <button @click="listingPage" class="btn btn-danger">Cancel</button>
 
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import ResponseData from "@/types/ResponseData";
import Teacher from "@/types/Teacher";
import TeacherService from "@/services/TeacherService";
import SchoolService from "@/services/SchoolService";
import School from "@/types/School";

export default defineComponent({
  name: "teacher",

  data() {
    
    return {
      schools : [] as School[],
      selectedSchool:[],
       currentSchool: {} as School,
      teacher: {
        teachername: "",
        address: "",
        email: "",
        gender: "",
      } as Teacher,
      submitted: false,
      picked: '',
    // selected: 'Male',
    options: [
      { value: 'Male' },
      { value: 'Female' },
      { value: 'Others' }
    ]
    };
  },
  methods: {
    saveTeacher() {
      let data = {
        teacherid: this.teacher.teacherid,
        teachername: this.teacher.teachername,
        address: this.teacher.address,
        phonenumber: this.teacher.phonenumber,
        email: this.teacher.email,
        gender: this.picked,
        schools:this.selectedSchool,
      };

      TeacherService.createTeacher(data)
        .then((response: ResponseData) => {
          this.teacher.teacherid = response.data.teacherid;
          console.log(response.data);
          this.submitted = true;
           this.$router.replace('/teacher');
        })
        .catch((e: Error) => {
          console.log(e);
        });
        
    },
     retrieveSchools() {
      SchoolService.getAllSchool()
        .then((response: ResponseData) => {
          this.schools = response.data;
          
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

  listingPage(){
      this.$router.replace('/teacher');
    }
  },
  
 
  mounted() {
    this.saveTeacher();
    this.retrieveSchools();
  },
});
</script>

<style>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
