// harsha/School-Teacher-Student/client/src/app/components/create-student/create-student.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { FileUploadService } from 'src/app/services/file-upload.service';
import { School } from '../../models/school.model';
import { Student } from '../../models/student.model';
import { SchoolService } from '../../services/school.service';
import { StudentService } from '../../services/student.service';

@Component({
  selector: 'app-create-student',
  templateUrl: './create-student.component.html',
  styleUrls: ['./create-student.component.css'],
})
export class CreateStudentComponent implements OnInit {
  registerForm!: FormGroup;
  submitted!: boolean;
  schools: School[] = [];
  genders: string[] = [];
  selectedSchool: School = {};
  selectedFiles?: FileList;
  currentFile?: File;
  progress = 0;
  message = '';
  id?: number;
  addForm?: boolean;
  currentStudent: Student = {
    studentName: '',
    gender: '',
    address: '',
    email: '',
    school: {},
  };

  constructor(
    private schoolService: SchoolService,
    private studentService: StudentService,
    private router: Router,
    private formBuilder: FormBuilder,
    private fileUploadService: FileUploadService,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.registerForm = this.formBuilder.group({
      studentName: ['', Validators.required],
      genders: ['', Validators.required],
      dateOfBirth: ['', Validators.required],
      address: ['', Validators.required],
      email: [
        '',
        [
          Validators.required,
          Validators.email,
          Validators.pattern('^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$'),
        ],
      ],
      phoneNo: ['', Validators.required],
      school: ['', Validators.required],
    });
    this.getSchools();
    this.getGenders();
    this.getStudentById(this.route.snapshot.params.id);
    this.id = this.route.snapshot.params.id;
    this.addForm = !this.id;
  }

  get validation() {
    return this.registerForm.controls;
  }

  signup() {
    this.submitted = true;
    if (this.registerForm.invalid) {
      return;
    }
    alert('form fields are validated successfully!');
    this.saveStudent();
  }

  async getSchools(): Promise<void> {
    this.schools = await this.schoolService.getSchools();
  }

  async getGenders() {
    this.genders = await this.studentService.getGender();
  }

  onSelected(school: string) {
    const schoolData = this.schools.filter((s) => s.schoolId === +school);
    this.selectedSchool = schoolData[0];
  }

  async getStudentById(id: number): Promise<void> {
    this.currentStudent = await this.studentService.getStudentById(id);
  }

  async saveStudent(): Promise<void> {
    const student: Student = {
      studentName: this.currentStudent.studentName,
      gender: this.currentStudent.gender,
      dateOfBirth: this.currentStudent.dateOfBirth,
      address: this.currentStudent.address,
      email: this.currentStudent.email,
      phoneNo: this.currentStudent.phoneNo,
      school: this.currentStudent.school,
    };
    await this.studentService.createStudent(student);
    this.router.navigate(['/student-list']);
  }

  async updateStudent(): Promise<void> {
    const student: Student = {
      studentId: this.currentStudent.studentId,
      studentName: this.currentStudent.studentName,
      gender: this.currentStudent.gender,
      dateOfBirth: this.currentStudent.dateOfBirth,
      address: this.currentStudent.address,
      email: this.currentStudent.email,
      phoneNo: this.currentStudent.phoneNo,
      school: this.currentStudent.school,
    };
    await this.studentService.updateStudent(
      this.currentStudent.studentId!,
      student
    );
    this.router.navigate(['/student-list']);
  }

  selectFile(event: Event): void {
    this.selectedFiles = (event.target as HTMLInputElement).files!;
  }

  upload(): void {
    this.progress = 0;
    if (this.selectedFiles) {
      const file: File | null = this.selectedFiles.item(0);
      if (file) {
        this.currentFile = file;
        this.fileUploadService.upload(this.currentFile);
      }
      this.selectedFiles = undefined;
    }
  }
}

<h1 class="card-title text-center" *ngIf="addForm">ADD STUDENT</h1>
<h1 class="card-title text-center" *ngIf="!addForm">EDIT STUDENT</h1>
<div class="form">
  <form [formGroup]="registerForm">
    <div class="form-group">
      <label for="studentName">Name</label>
      <input type="studentName" formControlName="studentName" placeholder="Enter your name" class="form-control item"
        [(ngModel)]="currentStudent.studentName"
        [ngClass]="{ 'is-invalid': submitted && validation.studentName.errors }" />
      <div *ngIf="this.submitted && validation.studentName.errors" class="invalid-feedback">
        <div *ngIf="validation.studentName.errors.required">
          Name Field is required
        </div>
      </div>
    </div>

    <div class="form-group">
      <label for="genders">Select a gender</label>
      <div *ngFor="let gender of genders; let i = index">
        <input formControlName="genders" name="genders" type="radio" [value]="gender"
          [(ngModel)]="currentStudent.gender" />
        <label for="">{{ gender }}</label>
      </div>
    </div>

    <div class="form-group">
      <input matInput [matDatepicker]="picker" placeholder="Choose a date" [(ngModel)]="currentStudent.dateOfBirth"
        formControlName="dateOfBirth" name="dateOfBirth" />
      <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
      <mat-datepicker #picker></mat-datepicker>
    </div>

    <div class="form-group">
      <label for="address">Address</label>
      <input type="address" formControlName="address" placeholder="Enter your address" class="form-control item"
        [(ngModel)]="currentStudent.address" [ngClass]="{ 'is-invalid': submitted && validation.address.errors }" />
      <div *ngIf="this.submitted && validation.address.errors" class="invalid-feedback">
        <div *ngIf="validation.address.errors.required">
          Address Field is required
        </div>
      </div>
    </div>

    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" formControlName="email" placeholder="Enter your email" class="form-control item"
        [(ngModel)]="currentStudent.email" [ngClass]="{ 'is-invalid': submitted && validation.email.errors }" />
      <div *ngIf="this.submitted && validation.email.errors" class="invalid-feedback">
        <div *ngIf="validation.email.errors.required">
          Email Field is required
        </div>
      </div>
    </div>

    <div class="form-group">
      <label for="phoneNo">Phone No</label>
      <input type="phoneNo" formControlName="phoneNo" placeholder="Enter your phoneNo" class="form-control item"
        [(ngModel)]="currentStudent.phoneNo" [ngClass]="{ 'is-invalid': submitted && validation.phoneNo.errors }" />
      <div *ngIf="this.submitted && validation.phoneNo.errors" class="invalid-feedback">
        <div *ngIf="validation.phoneNo.errors.required">
          Phone No Field is required
        </div>
      </div>
    </div>

    <div class="form-group">
      <label>
        <input type="file" (change)="selectFile($event)" />
      </label>
    </div>
    <button class="btn-primary" [disabled]="!selectedFiles" (click)="upload()">
      Upload
    </button>

    <div class="form-group">
      <p class="text-center">
        Schools
        <select class="form-control" formControlName="school" name="school"
          [(ngModel)]="currentStudent.school && currentStudent.school.schoolId" (ngModelChange)="onSelected($event)">
          <option disabled [value]="" selected>Choose School</option>
          <option *ngFor="let school of schools" [ngValue]="school.schoolId">
            {{ school.schoolName }}
          </option>
        </select>
      </p>
    </div>
    <button *ngIf="addForm" type="button" class="btn btn-success" (click)="signup()">
      Save
    </button>
    <button *ngIf="!addForm" type="button" class="btn btn-success" (click)="updateStudent()">
      Update
    </button>
    <button type=" button" class="btn btn-warning" routerLink="/student-list">
      Cancel
    </button>
  </form>
</div>

// Shubhankar/School/client vuejs/src/components/CreateStudent.vue
<!-- eslint-disable prettier/prettier -->
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="studentname">Name</label>
        <input
          type="text"
          class="form-control"
          id="studentname"
          required
          v-model="student.studentname"
          name="studentname"
        />
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="student.address"
          name="address"
        />
      </div>
      <div class="form-group">
        <label for="phonenumber">Contact</label>
        <input
          type="text"
          class="form-control"
          id="phonenumber"
          required
          v-model="student.phonenumber"
          name="phonenumber"
        />
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          required
          v-model="student.email"
          name="email"
        />
      </div>

      <div class="form-group">
        <label for="gender">Gender</label>
        <input
          type="text"
          class="form-control"
          id="gender"
          required
          v-model="student.gender"
          name="gender"
        />
      </div>

      <div class="form-group">
        <label for="dateofbirth">Born </label>
        <input
          type="date"
          class="form-control"
          id="dateofbirth"
          required
          v-model="student.dateofbirth"
          name="dateofbirth"
        />
      </div>

     <div class="form-group">
        <label>School List: </label>
        <select  v-model="student.school" @change="onSchoolSelect($event)">
          <option>Select School</option>
          <option           
            placeholder="select school"           
            v-for="(school, index) in schools"
            :key="index"
            :value="school.schoolid"
          >
            {{ school.schoolname }}
          </option>
        </select>
      </div>


      <button @click="saveStudent" class="btn btn-success">Submit</button>
       <button @click="listingPage" class="btn btn-danger">Cancel</button>
    </div>
    </div>
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import Student from "@/types/Student";
import StudentService from "@/services/StudentService";
import SchoolService from "@/services/SchoolService";
import School from "@/types/School";

export default defineComponent({
  name: "student",

  data() {
    return {
     schools:  [] as School[],
      student: {
        studentname: "",
        address: "",
        email: "",
        gender: "",
        dateofbirth:"",
       } as Student,
      submitted: false,
      currentSchool: {} as School,
       
    };
  },
  
  methods: {
  async  saveStudent() {
      const data = {
        studentid: this.student.studentid,
        studentname: this.student.studentname,
        address: this.student.address,
        phonenumber: this.student.phonenumber,
        email: this.student.email,
        gender: this.student.gender,
        dateofbirth:this.student.dateofbirth,
        school:this.student.school,
     };

    await  StudentService.createStudent(data)
        .then((response) => {
          this.student.studentid = response.data.studentid;
          console.log(response.data);
          this.submitted = true;
           this.$router.replace('/student');
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

   listingPage(){
      this.$router.replace('/student');
    },

   retrieveSchools() {
      SchoolService.getAllSchool()
        .then((response) => {
          this.schools = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
 
   onSchoolSelect(event: Event) { 
      const src = (event.target as HTMLInputElement).value;
      const data = this.schools.filter((s) => s.schoolid === +src);
     this.currentSchool = data[0];
     console.log(this.currentSchool);
    },  
  },
  mounted() {
    this.saveStudent();
    this.retrieveSchools()
  },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
