// harsha/School-Teacher-Student/client-ReactJS/src/components/student/edit-student.component.tsx
import { ChangeEvent, Component } from "react";
import SchoolService from "../../services/school.service";
import StudentService from "../../services/student.service";
import { Link, RouteComponentProps } from "react-router-dom";
import { School } from "../../types/school.type";
import { Student } from "../../types/student.type";
import Multiselect from "multiselect-react-dropdown";

interface RouterProps {
  // type for `match.params`
  id: string; // must be type `string` since value comes from the URL
}

type Props = RouteComponentProps<RouterProps>;

type State = {
  currentStudent: Student;
  schools: Array<School>;
};

const genders = [{ value: "Male" }, { value: "Female" }];

export default class EditStudent extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.onChangeGender = this.onChangeGender.bind(this);
    this.onChangeDateOfBirth = this.onChangeDateOfBirth.bind(this);
    this.onChangeEmail = this.onChangeEmail.bind(this);
    this.onChangePhoneNo = this.onChangePhoneNo.bind(this);
    this.onChangeSchools = this.onChangeSchools.bind(this);
    this.getStudent = this.getStudent.bind(this);
    this.updateStudent = this.updateStudent.bind(this);

    this.state = {
      currentStudent: {
        studentId: null,
        studentName: "",
        address: "",
        gender: "",
        email: "",
        school: {
          schoolName: "",
        },
      },
      schools: [],
    };
  }

  componentDidMount() {
    this.getStudent(this.props.match.params.id);
    this.retrieveSchools();
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    const teacherName = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          teacherName: teacherName,
        },
      };
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    const address = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          address: address,
        },
      };
    });
  }

  onChangeGender(e: ChangeEvent<HTMLInputElement>) {
    const gender = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          gender: gender,
        },
      };
    });
  }

  onChangeDateOfBirth(e: ChangeEvent<HTMLInputElement>) {
    const dateOfBirth = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          dateOfBirth: dateOfBirth,
        },
      };
    });
  }

  onChangeEmail(e: ChangeEvent<HTMLInputElement>) {
    const email = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          email: email,
        },
      };
    });
  }

  onChangePhoneNo(e: ChangeEvent<HTMLInputElement>) {
    const phoneNo = e.target.valueAsNumber;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          phoneNo: phoneNo,
        },
      };
    });
  }

  onChangeSchools(e: any) {
    const schools = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          schools: schools,
        },
      };
    });
  }

  retrieveSchools() {
    SchoolService.getSchools()
      .then((response: any) => {
        this.setState({
          schools: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  getStudent(id: string) {
    StudentService.get(id)
      .then((response: any) => {
        this.setState({
          currentStudent: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  updateStudent() {
    StudentService.update(
      this.state.currentStudent,
      this.state.currentStudent.studentId
    )
      .then((response: any) => {
        console.log(response.data);
        this.props.history.push("/teachers");
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { currentStudent, schools } = this.state;

    return (
      <div className="edit-form">
        <h2>EDIT STUDENT</h2>
        <form>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={currentStudent.studentName}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={currentStudent.address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>

          <div className="form-group">Select a Gender</div>
          <label>
            <input
              type="radio"
              name="gender"
              value={currentStudent.gender}
              checked={currentStudent.gender}
              onChange={this.onChangeGender}
            />
            {currentStudent.gender}
          </label>

          <div className="form-group">
            <label htmlFor="date">DOB</label>
            <input
              type="date"
              className="form-control"
              value={currentStudent.dateOfBirth}
              onChange={this.onChangeDateOfBirth}
              name="date"
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              type="text"
              className="form-control"
              id="email"
              required
              value={currentStudent.email}
              onChange={this.onChangeEmail}
              name="email"
            />
          </div>

          <div className="form-group">
            <label htmlFor="phoneNo">Phone No</label>
            <input
              type="number"
              className="form-control"
              id="phoneNo"
              required
              value={currentStudent.phoneNo}
              onChange={this.onChangePhoneNo}
              name="phoneNo"
            />
          </div>

          <div className="form-group">
            <select>
              <option value="">Select School</option>
              {/* {schools.map((school) => ( */}
                <option
                //   key={school.schoolId}
                  typeof="checked"
                  selected={true}
                  value={currentStudent.school?.schoolName}
                  onChange={this.onChangeSchools}
                >
                  {currentStudent.school?.schoolName}
                </option>
                {/* ))} */}
            </select>
          </div>

          <button
            onClick={this.updateStudent}
            type="button"
            className="btn btn-success"
          >
            Update
          </button>
          <Link to="/students">
            <button type="button" className="btn btn-warning">
              Cancel
            </button>
          </Link>
        </form>
      </div>
    );
  }
}

// Shubhankar/School/client vuejs/src/components/Editstudent.vue
<!-- eslint-disable prettier/prettier -->
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="studentname">Name</label>
        <input
          type="text"
          class="form-control"
          id="studentname"
          required
          v-model="selectedStudent.studentname"
          name="studentname"
        />
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="selectedStudent.address"
          name="address"
        />
      </div>
      <div class="form-group">
        <label for="phonenumber">Contact</label>
        <input
          type="text"
          class="form-control"
          id="phonenumber"
          required
          v-model="selectedStudent.phonenumber"
          name="phonenumber"
        />
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          required
          v-model="selectedStudent.email"
          name="email"
        />
      </div>
       <div class="form-group">
        <label for="gender">Gender</label>
        <input
          type="text"
          class="form-control"
          id="gender"
          required
          v-model="selectedStudent.gender"
          name="gender"
        />
      </div>
      <div class="form-group">
        <label for="dateofbirth">Born </label>
        <input
          type="date"
          class="form-control"
          id="dateofbirth"
          required
          v-model="selectedStudent.dateofbirth"
          name="dateofbirth"
        />
      </div>
      <div class="form-group">
        <label>School List: </label>
        <select v-model="selectedStudent.school.schoolid">
          <option>Select School</option>
          <option
            placeholder="select school"
            v-for="(school, index) in schools"
            :key="index"
            :value="school.schoolid"
          >
            {{ school.schoolname }}
          </option>
        </select>
      </div>
      <button @click="updateStudent" class="btn btn-success">Update</button>
      <button @click="listingPage" class="btn btn-danger">Cancel</button>
    </div>
  </div>
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import ResponseData from "@/types/ResponseData";
import School from "@/types/School";
import StudentService from "@/services/StudentService";
import Student from "@/types/Student";
import SchoolService from "@/services/SchoolService";

export default defineComponent({
  name: "edit-student",

  data() {
    return {
      schools: [] as School[],
      selectedStudent: {
        studentname: "",
        address: "",
        phonenumber: "",
        email: "",
        gender: "",
        dateofbirth: "",
        school: {},
      } as Student,
      message: "",
      submitted: false,
    };
  },

 methods: {
    updateStudent() {
      StudentService.updateStudent(this.selectedStudent)
        .then((response) => {
          console.log(response);
          this.$router.replace("/student");
          this.message = "the school is updated";
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    retrieveStudent(id:any) {
      StudentService.getStudentbyId(id)
        .then((response) => {
          this.selectedStudent = response.data;
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    retrieveSchools() {
      SchoolService.getAllSchool()
        .then((response) => {
          this.schools = response.data;
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    listingPage() {
      this.$router.replace("/student");
    },
  },
  mounted() {
    this.retrieveStudent(this.$route.params.id);
    this.retrieveSchools();
  },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style src="vue-multiselect/dist/vue-multiselect.min.css">
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
