// harsha/School-Teacher-Student/client-ReactJS/src/components/teacher/edit-teacher.component.tsx
import { ChangeEvent, Component } from "react";
import SchoolService from "../../services/school.service";
import TeacherService from "../../services/teacher.service";
import { Link, RouteComponentProps } from "react-router-dom";
import { Teacher } from "../../types/teacher.type";
import { School } from "../../types/school.type";

interface RouterProps {
     // type for `match.params`
  id: string; // must be type `string` since value comes from the URL
}

type Props = RouteComponentProps<RouterProps>;

type State =  {
    currentTeacher: Teacher;
  schools:Array<School>
};

const genders = [
    { value: "Male" },
    { value: "Female" },
  ];

export default class EditTeacher extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.onChangeGender = this.onChangeGender.bind(this);
    this.onChangeEmail = this.onChangeEmail.bind(this);
    this.onChangePhoneNo = this.onChangePhoneNo.bind(this);
    this.onChangeSchools = this.onChangeSchools.bind(this);
    this.getTeacher = this.getTeacher.bind(this);
    this.updateTeacher = this.updateTeacher.bind(this);

    this.state = {
        currentTeacher:{
            teacherId:null,
      teacherName: "",
      address: "",
      gender: "",
      email: "",
      schools: [],
        },
        schools:[]
    };
  }

  componentDidMount() {
    this.getTeacher(this.props.match.params.id);
    this.retrieveSchools();
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    const teacherName = e.target.value;

    this.setState(function (prevState) {
      return {
        currentTeacher: {
          ...prevState.currentTeacher,
          teacherName: teacherName,
        },
      };
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    const address = e.target.value;

    this.setState(function (prevState) {
      return {
        currentTeacher: {
          ...prevState.currentTeacher,
          address: address,
        },
      };
    });
  }

  onChangeGender(e: ChangeEvent<HTMLInputElement>) {
    const gender = e.target.value;

    this.setState(function (prevState) {
      return {
        currentTeacher: {
          ...prevState.currentTeacher,
          gender: gender,
        },
      };
    });
  }

  onChangeEmail(e: ChangeEvent<HTMLInputElement>) {
    const email = e.target.value;

    this.setState(function (prevState) {
      return {
        currentTeacher: {
          ...prevState.currentTeacher,
          email: email,
        },
      };
    });
  }

  onChangePhoneNo(e: ChangeEvent<HTMLInputElement>) {
    const phoneNo = e.target.valueAsNumber;

    this.setState(function (prevState) {
      return {
        currentTeacher: {
          ...prevState.currentTeacher,
          phoneNo: phoneNo,
        },
      };
    });
  }

  onChangeSchools(e: any) {
    const schools = e.target.value;

    this.setState(function (prevState) {
      return {
        currentTeacher: {
          ...prevState.currentTeacher,
          schools: schools,
        },
      };
    });
  }

  retrieveSchools() {
    SchoolService.getSchools()
      .then((response: any) => {
        this.setState({
          schools: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  getTeacher(id: string) {
    TeacherService.get(id)
      .then((response: any) => {
        this.setState({
            currentTeacher: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  updateTeacher() {
    TeacherService.update(
      this.state.currentTeacher,
      this.state.currentTeacher.teacherId
    )
      .then((response: any) => {
        console.log(response.data);
        this.props.history.push("/teachers");
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { currentTeacher,  schools } = this.state;

    return (
      <div className="edit-form">
        <h2>EDIT TEACHER</h2>
        <form>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={currentTeacher.teacherName}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={currentTeacher.address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>

          <div className="form-group">Select a Gender</div>
            <label >
              <input
                type="radio"
                name="gender"
                value={currentTeacher.gender}
                checked={currentTeacher.gender}
                onChange={this.onChangeGender}
              />
              {currentTeacher.gender}
            </label>

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              type="text"
              className="form-control"
              id="email"
              required
              value={currentTeacher.email}
              onChange={this.onChangeEmail}
              name="email"
            />
          </div>

          <div className="form-group">
            <label htmlFor="phoneNo">Phone No</label>
            <input
              type="number"
              className="form-control"
              id="phoneNo"
              required
              value={currentTeacher.phoneNo}
              onChange={this.onChangePhoneNo}
              name="phoneNo"
            />
          </div>

          <div className="form-group">
          <label >Schools</label>
          {schools.map((school, i) => (
            <div key={i}>
              <input
                type="checkbox"
                name="schools"
                value={school.schoolName}
                onChange={this.onChangeSchools}
              />{" "}
              {school.schoolName}
            </div>
          ))}</div>

          <button
            onClick={this.updateTeacher}
            type="button"
            className="btn btn-success"
          >
            Update
          </button>
          <Link to="/teachers">
            <button type="button" className="btn btn-warning">
              Cancel
            </button>
          </Link>
        </form>
      </div>
    );
  }
}

// Shubhankar/School/client vuejs/src/components/Editteacher.vue
<!-- eslint-disable prettier/prettier -->
<template>
<div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="teachername">Name</label>
        <input
          type="text"
          class="form-control"
          id="teachername"
          required
          v-model="selectedTeacher.teachername"
          name="teachername"
        />
      </div>

      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="selectedTeacher.address"
          name="address"
        />
      </div>

      <div class="form-group">
        <label for="phonenumber">Contact</label>
        <input
          type="text"
          class="form-control"
          id="phonenumber"
          required
          v-model="selectedTeacher.phonenumber"
          name="phonenumber"
        />
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          required
          v-model="selectedTeacher.email"
          name="email"
        />
      </div>

   <div class="form-group">
    <label for="gender">Gender</label><br>
  <input type="radio" id="Male" value="Male" v-model="selectedTeacher.gender">
  <label for="Male">Male</label><br>
  <input type="radio" id="Female" value="Female" v-model="selectedTeacher.gender">
  <label for="Female">Female</label><br>
  <input type="radio" id="Others" value="Others" v-model="selectedTeacher.gender">
  <label for="Female">Others</label><br>
  <span>Picked: {{ picked }}</span><br>
   </div>
  
         <!-- <div class="form-group">
          <label for="schools">Select School</label><br>
                <li  :class="{ active: index == currentIndex }"
                v-for="(school, index) in schools"
              :key="index">
                  <label v-bind:for="school.schoolid">
              <div  >
                <input type="checkbox" v-model="selectedTeacher.school" v-bind:value="school">
                  <span>{{ school.schoolname }}</span>
              </div>
              </label>
          </li> -->

      
          <div  class="form-group">
            <label for="schools">Select School</label><br>
            <li v-for="(school, index) in schools"
                  :key="index">
            <input type="checkbox"
              :fieldId="school.schoolname"
              :label="school.schoolname"
              :checked="value.includes(school.schoolid)"
              :key="school"
               />
              <span>{{ school.schoolname }}</span>
              </li>
          </div>
        </div>
      </div>

      <button @click="updateTeacher" class="btn btn-success">Update</button>
      <button @click="listingPage" class="btn btn-danger">Cancel</button>
 
</template>

<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import ResponseData from "@/types/ResponseData";
import School from "@/types/School";
import SchoolService from "@/services/SchoolService";
 import TeacherService from "@/services/TeacherService";
import Teacher from "@/types/Teacher";

export default defineComponent({
  name: "edit-teacher", 
  
  
  data() {
    return {
        schools:[] as School[],
         selectedTeacher: {
             teachername: "",
             address: "",
             email: "",
             gender: "",
             schools:{}
           } as Teacher,
          message: "",
          submitted: false,
          value : [] as number[],
    };
},

methods: {
    updateTeacher() {
     
     TeacherService.updateTeacher(this.selectedTeacher)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.message = "the teacher is updated";
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    retrieveTeachers(id: any) {
      TeacherService.createTeacherbyId(id)
        .then((response: ResponseData) => {
          this.selectedTeacher = response.data;
          for(const i of this.selectedTeacher.schools){
            this.value.push(i.schoolid!);
        }
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
  
   retrieveSchools() {
      SchoolService.getAllSchool()
        .then((response: ResponseData) => {
          this.schools = response.data;
          
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
 listingPage(){
      this.$router.replace('/teacher');
    }
    
},
   mounted() {
    this.retrieveTeachers(this.$route.params.id);
    this.retrieveSchools();
 },
});
</script>

<!-- eslint-disable prettier/prettier -->
<style src="vue-multiselect/dist/vue-multiselect.min.css">
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
