// harsha/School-Teacher-Student/client-ReactJS/src/components/school/edit-school.component.tsx
import Multiselect from "multiselect-react-dropdown";
import { Component, ChangeEvent } from "react";
import { Link, RouteComponentProps } from "react-router-dom";
import SchoolService from "../../services/school.service";
import TeacherService from "../../services/teacher.service";
import StudentService from "../../services/student.service";
import { School } from "../../types/school.type";
import { Student } from "../../types/student.type";
import { Teacher } from "../../types/teacher.type";

interface RouterProps {
  // type for `match.params`
  id: string; // must be type `string` since value comes from the URL
}

type Props = RouteComponentProps<RouterProps>;

type State = {
  currentSchool: School;
  students: Array<Student>;
  teachers: Array<Teacher>;
};

export default class EditSchool extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.getSchool = this.getSchool.bind(this);
    this.updateSchool = this.updateSchool.bind(this);

    this.state = {
      currentSchool: {
        schoolName: "",
        address: "",
      },
      teachers: [],
      students: [],
    };
  }

  componentDidMount() {
    this.getSchool(this.props.match.params.id);
    this.retrieveTeachers();
    this.retrieveStudents();
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    const schoolName = e.target.value;

    this.setState(function (prevState) {
      return {
        currentSchool: {
          ...prevState.currentSchool,
          schoolName: schoolName,
        },
      };
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    const address = e.target.value;

    this.setState((prevState) => ({
      currentSchool: {
        ...prevState.currentSchool,
        address: address,
      },
    }));
  }
  retrieveTeachers() {
    TeacherService.getTeachers()
      .then((response) => {
        this.setState({
          teachers: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  retrieveStudents() {
    StudentService.getStudents()
      .then((response) => {
        this.setState({
          students: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  getSchool(id: string) {
    SchoolService.get(id)
      .then((response) => {
        this.setState({
          currentSchool: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  updateSchool() {
    SchoolService.update(
      this.state.currentSchool,
      this.state.currentSchool.schoolId!
    )
      .then((response) => {
        console.log(response.data);
        this.props.history.push("/schools");
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { currentSchool, teachers, students } = this.state;

    return (
      <>
        <h4>EDIT SCHOOL</h4>
        <div className="edit-form">
          <form>
            <div className="form-group">
              <label htmlFor="schoolName">Name</label>
              <input
                type="text"
                className="form-control"
                id="schoolName"
                value={currentSchool.schoolName}
                onChange={this.onChangeName}
              />
            </div>
            <div className="form-group">
              <label htmlFor="address">Address</label>
              <input
                type="text"
                className="form-control"
                id="address"
                value={currentSchool.address}
                onChange={this.onChangeAddress}
              />
            </div>

            <div className="form-group">
              <label>Teachers</label>
              <Multiselect
                options={teachers}
                selectedValues={currentSchool.teachers}
                closeIcon="close"
                placeholder="Choose Teachers"
                displayValue="teacherName"
              />
            </div>

            <div className="form-group">
              <label>Students</label>
              <Multiselect
                options={students}
                selectedValues={currentSchool.students}
                closeIcon="close"
                placeholder="Choose Students"
                displayValue="studentName"
              />
            </div>
          </form>

          <button
            type="submit"
            className="btn badge-success"
            onClick={this.updateSchool}
          >
            Update
          </button>
          <Link to={"/schools"}>
            <button type="submit" className="btn badge-warning">
              Cancel
            </button>
          </Link>
        </div>
      </>
    );
  }
}

// Shubhankar/School/client vuejs/src/components/Editschool.vue
<!-- eslint-disable prettier/prettier -->
<template>
   <div class="submit-form">   
    <div>
      <div class="form-group">
        <label for="schoolname">Name</label>
        <input
          type="text"
          class="form-control"
          id="schoolname"
          required
          v-model="selectedSchool.schoolname"
          name="schoolname"
        />
      </div>

      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="selectedSchool.address"
          name="address"
        />
      </div>
      
    <div class="form-group">
   <label for="teachers">Teacher</label>
    <multiselect
     class="form-control"
       id="teachers"
        required
      v-model="selectedSchool.teachers"
       name="teachers"
      :options="teacher"
      :multiple="true"
      :close-on-select="false"
      :clear-on-select="false" 
      :preserve-search="true"
       placeholder="Pick some"
        label="teachername" 
        track-by="teachername" 
        :preselect-first="true" >
    </multiselect>
  </div>

  <div class="form-group">
   <label for="teachers">Student</label>
    <multiselect
     class="form-control"
       id="students"
        required
      v-model=" selectedSchool.students"
       name="students"
      :options="student"
      :multiple="true" 
      :close-on-select="false"
      :preserve-search="true"
       placeholder="Pick some"
        label="studentname" 
        track-by="studentname" 
        :preselect-first="true">
    </multiselect>
  </div>
  
   <button @click="updateSchool" class="btn btn-success">Update</button>
    <button @click="listingPage" class="btn btn-danger">Cancel</button>
    </div>
  </div>
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import School from "@/types/School";
import SchoolService from "@/services/SchoolService";
import Multiselect from '@suadelabs/vue3-multiselect'
import TeacherService from "@/services/TeacherService";
import Teacher from "@/types/Teacher";
import StudentService from "@/services/StudentService";
import Student from "@/types/Student";

export default defineComponent({
  name: "edit-school", 
   components: { Multiselect },
  
  data() {
    return {
         teacher: [] as Teacher[],
         student:[] as Student[],
          selectedSchool:{} as School,
          message: "",
          submitted: false,
    };
},

methods: {
    updateSchool() {
     
     SchoolService.updateSchool(this.selectedSchool)
        .then((response) => {
          console.log(response);
            this.$router.replace('/school');
          this.message = "the school is updated";
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    retrieveTeachers() {
      TeacherService.getAllTeachers()
        .then((response) => {
          this.teacher = response.data;
         })
        .catch((e: Error) => {
          console.log(e);
        });
    },

     retrieveStudents() {
      StudentService.getAllStudents()
        .then((response) => {
          this.student = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
      
      retrieveSchoolbyId(id :any){
         SchoolService.getSchoolbyId(id)
         .then((response) => {
          this.selectedSchool = response.data;
          console.log(response);
        })
        .catch((e: Error) => {
          console.log(e);
        });
      },

      listingPage(){
      this.$router.replace('/school');
    }

    
},
   mounted() {
    this.retrieveTeachers();
    this.retrieveStudents();
    this.retrieveSchoolbyId(this.$route.params.id);
 },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style src="vue-multiselect/dist/vue-multiselect.min.css">
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
