// adarsh/school/client/src/app/components/teacher-listing/teacher-listing.component.ts
import { Component, OnInit } from '@angular/core';
import { Teacher } from 'src/app/models/teacher';
import { SchoolService } from 'src/app/services/school.service';

@Component({
  selector: 'app-teacher-listing',
  templateUrl: './teacher-listing.component.html',
  styleUrls: ['./teacher-listing.component.css'],
})
export class TeacherListingComponent implements OnInit {
  teachers:Teacher[]=[]
  constructor( private schoolService: SchoolService,) {}

  ngOnInit(): void {
    this.retrieveTeachers();
  }
  async retrieveTeachers() {
    this.teachers = await this.schoolService.getTeachers();
  }
}

<div class="list row">
    <div class="col-md-8">
      <div class="input-group mb-3"></div>
    </div>
    <div class="col-md-6">
      <h4>TEACHER LIST</h4>
      <ul class="list-group"></ul>
      <td>
        <button routerLink="/addTeacher">ADD TEACHER</button>
      </td>
    <br>
    </div>
   
  
    <div class="container">
      <table class="table table-bordered justify-content-center">
        <thead class="thead-light">
          <tr class="active">
            <th class="text-center" scope="col">NAME</th>
            <th class="text-center" scope="col">ADRESS</th>
            <th class="text-center" scope="col">EMAIL</th>
            <th class="text-center" scope="col">GENDER</th>
            <th class="text-center" scope="col">PHONE</th>

            <th class="text-center" scope="col">EDIT</th>
          </tr>
        </thead>
        <tbody *ngFor="let teacher of teachers">
          <tr class="success">
            <th class="text-center" scope="row">{{ teacher.name }}</th>
            <th class="text-center" scope="row">{{ teacher.address }}</th>
            <th class="text-center" scope="row">{{ teacher.email }}</th>
            <th class="text-center" scope="row">{{ teacher.gender}}</th>
            <th class="text-center" scope="row">{{ teacher.phone}}</th>
           
            <th class="text-center" scope="row">
              <button
                type="button"
                class="btn btn-info btn-sm mr-2"
                routerLink="/teacher/{{ teacher.id }}"
              >
                Edit
              </button>
             
            </th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

// Shubhankar/School/client vuejs/src/components/TeacherListing.vue
<!-- eslint-disable prettier/prettier -->
<template>
    <h4>Teacher List</h4>
  <div class="list row">
    <div class="col-md-6">
   </div>
   <table class="table table-striped table-bordered justify-content-center">
  <thead class="thead-light">
    <tr class="active">
    
      <th class="text-center" scope="col">Name</th>
     <th class="text-center" scope="col">Address</th>
       <th class="text-center" scope="col">Email</th>
       <th class="text-center" scope="col">Contact</th>
       <th class="text-center" scope="col">Gender</th>
    </tr>
  </thead>
  <tbody  
          :class="{ active: index == currentIndex }"
          v-for="(teacher, index) in teachers"
          :key="index">
      <tr class="success">
         <th class="text-center" scope="row">{{ teacher.teachername }}</th>
       <th class="text-center" scope="row">{{ teacher.address }}</th>
       <th class="text-center" scope="row">{{ teacher.email }}</th>
        <th class="text-center" scope="row">{{ teacher.phonenumber }}</th>
       <th class="text-center" scope="row">{{ teacher.gender }}</th>
      </tr>
   </tbody>
</table>
</div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Teacher from "@/types/Teacher";
import ResponseData from "@/types/ResponseData";
import getAllTeachers from "@/services/TeacherService";

export default defineComponent({
  name: "teacher-list",
  data() {
    return {
      teachers: [] as Teacher[],
      currentTeachers: {} as Teacher,
      currentIndex: -1,
      title: "",
    };
  },
  methods: {
    retrieveTeachers() {
      getAllTeachers.getAllTeachers()
        .then((response: ResponseData) => {
          this.teachers = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
},
  mounted() {
    this.retrieveTeachers();
  },
});
</script>

<style>
.list {
  text-align: left;
  max-width: 750px;
  margin: auto;
  background-color: blanchedalmond;
}
</style>
