// adarsh/tutorial/clint/src/app/components/tutorial-details/tutorial-details.component.ts
import { Component, OnInit } from '@angular/core';
import { TutorialService } from 'src/app/services/tutorial.service';
import { ActivatedRoute, Router } from '@angular/router';
import { Tutorial } from 'src/app/models/tutorial.model';
import { Category } from 'src/app/models/category.model';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import * as moment from 'moment-timezone';
import { Moment } from 'moment';

@Component({
  selector: 'app-tutorial-details',
  templateUrl: './tutorial-details.component.html',
  styleUrls: ['./tutorial-details.component.css'],
})
export class TutorialDetailsComponent implements OnInit {
  tutorial: Tutorial[] = [];
  categories: Category[] = [];
  selectedCategory = new Category();
  selectedCategoryNew = new Category();
  selectedCategories: Category[] = [];
  submitted: boolean = false;
  countries: any;

  currentTutorial: Tutorial = {
    title: '',
    description: '',
    author: '',
    categories: [],
    countries: '',
    timeZone: '',
  };
  message = '';
  registerForm!: FormGroup;
  selectedTz?: string;
  timeZone?: string[];

  constructor(
    private tutorialService: TutorialService,
    private route: ActivatedRoute,
    private router: Router,
    private formBuilder: FormBuilder
  ) {}

  ngOnInit(): void {
    this.registerForm = this.formBuilder.group({
      description: ['', Validators.required],
      title: ['', Validators.required],
      categories: ['', Validators.required],
      author: ['', Validators.required],
      countries: ['', Validators.required],
    });

    this.retrieveTutorials();
    this.retrieveCategory();
    this.countries = this.getCountries();
    if (this.route.snapshot.params.id != 'add') {
      this.getTutorial(this.route.snapshot.params.id);
    }
    this.timeZone = moment.tz.names();
  }
  get fval() {
    return this.registerForm.controls;
  }

  signup() {
    this.submitted = true;
    if (this.registerForm.invalid) {
      return;
    }
    alert('form fields are validated successfully!');
    this.saveTutorial();
  }

  getCountries() {
    return this.tutorialService.getCountriesData();
  }

  async saveTutorial(): Promise<void> {
    const data = {
      title: this.currentTutorial.title,
      description: this.currentTutorial.description,
      categories: this.selectedCategories,
      timeZone: this.currentTutorial.timeZone,
    };

    await this.tutorialService.createTutorial(data);
    this.router.navigate(['tutorials']);
  }

  async update(): Promise<void> {
    const data = {
      id: this.currentTutorial.id,
      title: this.currentTutorial.title,
      description: this.currentTutorial.description,
      categories: this.selectedCategories,
    };
    if (this.selectedCategories.length)
      await this.tutorialService.updateTutorial(data);
  }

  onSelected(value: Category) {
    if (this.categories) {
      for (let category of this.categories) {
        if (category.id == value.id) {
          this.selectedCategoryNew.title = category.title;
          this.selectedCategories.push(this.selectedCategoryNew);
        }
      }
    }
  }

  private async getTutorial(id: Number) {
    const data = await this.tutorialService.getTutor(id);
    this.currentTutorial = data;
    if (this.currentTutorial.categories) {
      this.selectedCategory = this.currentTutorial.categories[0];
    }
  }

  async retrieveTutorials(): Promise<void> {
    this.tutorial = await this.tutorialService.getAll();
  }

  async retrieveCategory(): Promise<void> {
    this.categories = await this.tutorialService.getCategories();
    console.log();
  }
  public timeZoneChanged(timeZone: string): void {
    this.selectedTz = timeZone;
    this.currentTutorial.timeZone = timeZone;
  }
}

// async saveTutorial() {
//   const tutorialData: Tutorial = {
//     title: this.currentTutorial.title,
//     description: this.currentTutorial.description,
//     categories: this.selectedCategories
//   };
//   tutorialData.categories = this.selectedCategories;
//   await this.tutorialService.createTutorial(tutorialData);
//   console.log(tutorialData);
// }

// updatePublished(status: boolean): void {
//   const data = {
//     title: this.currentTutorial.title,
//     description: this.currentTutorial.description,
//     published: status,
//   }

//   this.message = ''

//   this.tutorialService.update(this.currentTutorial.id, data).subscribe(
//     (response) => {
//       console.log(response)
//       this.message = response.message
//         ? response.message
//         : 'The status was updated successfully!'
//     },
//     (error) => {
//       console.log(error)
//     },
//   )
// }

// updateTutorial(): void {
//   this.message = ''

//   this.tutorialService
//     .update(this.currentTutorial.id, this.currentTutorial)
//     .subscribe(
//       (response) => {
//         console.log(response)
//         this.message = response.message
//           ? response.message
//           : 'This tutorial was updated successfully!'
//       },
//       (error) => {
//         console.log(error)
//       },
//     )
// }

// deleteTutorial(): void {
//   this.tutorialService.delete(this.currentTutorial.id).subscribe(
//     (response) => {
//       console.log(response)
//       this.router.navigate(['/tutorials'])
//     },
//     (error) => {
//       console.log(error)
//     },
//   )
// }

<div>
  <div class="edit-form">
    <h4>Tutorial</h4>
    <form [formGroup]="registerForm" (ngSubmit)="signup();">

      <div class="form-group">
        <label for="title">Title</label>
        <input type="text" formControlName="title" class="form-control" [(ngModel)]="currentTutorial.title"
          [ngClass]="{ 'is-invalid': submitted && fval.title.errors }" />
        <div *ngIf="this.submitted && fval.title.errors" class="invalid-feedback">
          <div *ngIf="fval.title.errors.required" style="color: red">
            Title is required
          </div>
        </div>
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <input type="text" formControlName="description" class="form-control" [(ngModel)]="currentTutorial.description"
          [ngClass]="{ 'is-invalid': submitted && fval.description.errors }" />
        <div *ngIf="this.submitted && fval.description.errors " class="invalid-feedback">
          <div *ngIf="fval.description.errors.required" style="color: red">
            Description is required
          </div>
        </div>
      </div>
      <br>

      <div class="form-group">
        <label for="author">Author</label>
        <input type="text" formControlName="author" class="form-control" [(ngModel)]="currentTutorial.author"
          [ngClass]="{ 'is-invalid': submitted && fval.author.errors }" />
        <div *ngIf="this.submitted && fval.author.errors" class="invalid-feedback">
          <div *ngIf="fval.author.errors.required" style="color: red">
            Author is required
          </div>
        </div>
      </div>
      <br>

      <div class="form-group">
        <p>Category : <select formControlName="categories" class="form-control" placeholder="Choose Category"
            style="width: 50%;" [(ngModel)]="selectedCategory.id" (ngModelChange)="onSelected(selectedCategory)"
            name="categories" [ngClass]="{ 'is-invalid': submitted && fval.categories.errors }">
            <option value="Choose Category">Choose Category</option>
            <option *ngFor="let category of categories" [ngValue]="category.id">{{category.title}}</option>
          </select>
        <div *ngIf="this.submitted  && fval.categories.errors" style="color: red">
          <div *ngIf="fval.categories.errors.required">
            Selecting atleast one Category is required
          </div>
        </div>
      </div>
      <br>

      <div>
        <p>Country : <select formControlName="countries" class="form-control" placeholder="Choose Country"
            style="width: 50%;" name="country" [(ngModel)]="currentTutorial.countries"
            [ngClass]="{ 'is-invalid': submitted && fval.countries.errors }">
            <option value="Choose Country">Choose Country</option>
            <option *ngFor="let country of countries">{{country.name}}</option>
          </select>
        <div *ngIf="this.submitted && fval.countries.errors" style="color: red">
          <div *ngIf="fval.countries.errors.required">
            Selecting atleast one Country is required
          </div>
        </div>
      </div>
      <div>
        <form #f="ngForm">
          <div class="form-group">
            <label>Select time zone: </label>
            <select name="timeZone" [ngModel]="selectedTz" (ngModelChange)="timeZoneChanged($event)">
              <option *ngFor="let tz of timeZone" [value]="tz">
                {{ tz }}
              </option>
            </select>
          </div>
          <br>
          <button type="submit" class="btn btn-info btn-sm mr-2" routerLink="/tutorials" (click)=" saveTutorial()">
            Submit </button>
          <button type="submit" class="btn btn-info btn-sm mr-2" (click)="update()"> Update </button>
        </form>
      </div>

// Shubhankar/School/client vuejs/src/components/TutorialDetails.vue
/* eslint-disable */

<template>
  <div v-if="currentTutorial.id" class="edit-form">
    <h4>Tutorial</h4>
    <form>
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          v-model="currentTutorial.title"
        />
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <input
          type="text"
          class="form-control"
          id="description"
          v-model="currentTutorial.description"
        />
      </div>

      <div class="form-group">
        <label><strong>Status:</strong></label>
        {{ currentTutorial.published ? "Published" : "Pending" }}
      </div>
    </form>

    <button
      class="badge badge-primary mr-2"
      v-if="currentTutorial.published"
      @click="updatePublished(false)"
    >
      UnPublish
    </button>
    <button
      v-else
      class="badge badge-primary mr-2"
      @click="updatePublished(true)"
    >
      Publish
    </button>

    <button class="badge badge-danger mr-2" @click="deleteTutorial">
      Delete
    </button>

    <button type="submit" class="badge badge-success" @click="updateTutorial">
      Update
    </button>
    <p>{{ message }}</p>
  </div>

  <div v-else>
    <br />
    <p>Please click on a Tutorial...</p>
  </div>
</template>

<script lang="ts">
/* eslint-disable */
import { defineComponent } from "vue";
import TutorialDataService from "@/services/TutorialDataService";

import ResponseData from "@/types/ResponseData";
import Tutorial from "@/types/Tutorial";

export default defineComponent({
  name: "tutorial",
  data() {
    return {
      currentTutorial: {} as Tutorial,
      message: "",
    };
  },
  methods: {
    getTutorial(id: any) {
      TutorialDataService.get(id)
        .then((response: ResponseData) => {
          this.currentTutorial = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    updatePublished(status: boolean) {
      let data = {
        id: this.currentTutorial.id,
        title: this.currentTutorial.title,
        description: this.currentTutorial.description,
        published: status,
      };

      TutorialDataService.update(this.currentTutorial.id, data)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.currentTutorial.published = status;
          this.message = "The status was updated successfully!";
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    updateTutorial() {
      TutorialDataService.update(this.currentTutorial.id, this.currentTutorial)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.message = "The tutorial was updated successfully!";
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    deleteTutorial() {
      TutorialDataService.delete(this.currentTutorial.id)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.$router.push({ name: "tutorials" });
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
  },
  mounted() {
    this.message = "";
    this.getTutorial(this.$route.params.id);
  },
});
</script>

<style>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
