// harsha/School-Teacher-Student/client-ReactJS/src/components/edit-school.component.tsx
import Multiselect from "multiselect-react-dropdown";
import { Component, ChangeEvent } from "react";
import { Link, RouteComponentProps } from "react-router-dom";
import SchoolService from "../services/school.service";
import TeacherService from "../services/teacher.service";
import StudentService from "../services/student.service";
import { School } from "../types/school.type";
import { Student } from "../types/student.type";
import { Teacher } from "../types/teacher.type";

interface RouterProps {
  // type for `match.params`
  id: string; // must be type `string` since value comes from the URL
}

type Props = RouteComponentProps<RouterProps>;

type State = {
  currentSchool: School;
  students:Array<Student>,
  teachers:Array<Teacher>
};

export default class EditSchool extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.getSchool = this.getSchool.bind(this);
    this.updateSchool = this.updateSchool.bind(this);

    this.state = {
      currentSchool: {
        schoolId: null,
        schoolName: "",
        address: "",
      },
      teachers:[],
      students:[]
    };
  }

  componentDidMount() {
    this.getSchool(this.props.match.params.id);
    this.retrieveTeachers();
    this.retrieveStudents();
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    const schoolName = e.target.value;

    this.setState(function (prevState) {
      return {
        currentSchool: {
          ...prevState.currentSchool,
          schoolName: schoolName,
        },
      };
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    const address = e.target.value;

    this.setState((prevState) => ({
      currentSchool: {
        ...prevState.currentSchool,
        address: address,
      },
    }));
  }
  retrieveTeachers() {
    TeacherService.getTeachers()
      .then((response: any) => {
        this.setState({
          teachers: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  retrieveStudents() {
    StudentService.getStudents()
      .then((response: any) => {
        this.setState({
          students: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  getSchool(id: string) {
    SchoolService.get(id)
      .then((response: any) => {
        this.setState({
          currentSchool: response.data,
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  updateSchool() {
    SchoolService.update(
      this.state.currentSchool,
      this.state.currentSchool.schoolId
    )
      .then((response: any) => {
        console.log(response.data);
        this.props.history.push("/schools");
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { currentSchool, teachers, students } = this.state;

    return (
      <>
        <h4>EDIT SCHOOL</h4>
        <div className="edit-form">
          <form>
            <div className="form-group">
              <label htmlFor="schoolName">Name</label>
              <input
                type="text"
                className="form-control"
                id="schoolName"
                value={currentSchool.schoolName}
                onChange={this.onChangeName}
              />
            </div>
            <div className="form-group">
              <label htmlFor="address">Address</label>
              <input
                type="text"
                className="form-control"
                id="address"
                value={currentSchool.address}
                onChange={this.onChangeAddress}
              />
            </div>

            <div className="form-group">
            <label >Teachers</label>
            <Multiselect
              options={teachers}
              selectedValues={currentSchool.teachers}
              closeIcon="close"
              placeholder="Choose Teachers"
              displayValue="teacherName"
            />
          </div>

            <div className="form-group">
            <label >Teachers</label>
            <Multiselect
              options={students}
              selectedValues={currentSchool.students}
              closeIcon="close"
              placeholder="Choose Students"
              displayValue="studentName"
            />
          </div>
          </form>

          <button
            type="submit"
            className="btn badge-success"
            onClick={this.updateSchool}
          >
            Update
          </button>
          <Link to={"/schools"}>
            <button type="submit" className="btn badge-warning">
              Cancel
            </button>
          </Link>
        </div>
      </>
    );
  }
}

// adarsh/school/VUE-client/src/components/EditSchool.vue
<script lang="ts">/* eslint-disable */
import { defineComponent } from "vue";
import studentservice from "@/services/studentservice";
import School from "@/types/school";
import ResponseData from "@/types/ResponseData";
import Multiselect from "@suadelabs/vue3-multiselect";
import { Student } from "@/types/student";
import { Teacher } from "@/types/teacher";

export default defineComponent({
  components: { Multiselect },
  name: "edit-school",
  data() {
    return {
      currentSchool: {} as School,
      message: "",
      teacherData: [] as Teacher[],
      studentData: [] as Student[],
      selectedTeachers: [] as Teacher[],
      selectedStudents: [] as Teacher[],
    };
  },
  methods: {
    getSchool(id: any) {
      studentservice
        .getSchool(id)
        .then((response: ResponseData) => {
          this.currentSchool = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    updateSchool() {
        studentservice.updateSchool(this.currentSchool.id,this.currentSchool)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.message = "The tutorial was updated successfully!";
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    retrieveTeachers() {
      studentservice
        .getAllTeachers()
        .then((response: ResponseData) => {
          this.teacherData = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    retrieveStudents() {
      studentservice
        .getAllStudents()
        .then((response: ResponseData) => {
          this.studentData = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
 
  mounted() {
    this.message = "";
    this.getSchool(this.$route.params.id);
    this.retrieveStudents();
      this.retrieveTeachers()
  },
  }
});
</script>
<template>
  <div v-if="currentSchool.schoolid" class="edit-form">
    <h4>Edit-School</h4>
    <form>
      <div class="form-group">
        <label for="schoolname">Schoolname</label>
        <input
          type="text"
          class="form-control"
          id="schoolname"
          v-model="currentSchool.schoolname"
        />
      </div>
      <div class="form-group">
        <label for="address">address</label>
        <input
          type="text"
          class="form-control"
          id="address"
          v-model="currentSchool.address"
        />
      </div>      
      <div class="form-group">
          <multiselect
            class="form-control"
            id="teacher"
            required
            v-model="currentSchool.teacher"
            name="teacher"
            :options="teacherData"
            :multiple="true"
            :close-on-select="false"
            :clear-on-select="false"
            :preserve-search="true"
            placeholder="Select Teacher"
            label="teachername"
            track-by="teachername"
            :preselect-first="true"
          >
          </multiselect>
        </div>
        <div class="form-group">
          <multiselect
            class="form-control"
            id="students"
            required
            v-model="currentSchool.students"
            name="students"
            :options="studentData"
            :multiple="true"
            :close-on-select="false"
            :clear-on-select="false"
            :preserve-search="true"
            placeholder="Select Student"
            label="studentname"
            track-by="studentname"
            :preselect-first="true"
          >
          </multiselect>
        </div>
    </form>
    <button class="badge badge-danger mr-2" @click="deleteSchool">Delete</button>

    <button type="submit" class="badge badge-success mr-2" @click="updateSchool()">Update</button>

    <router-link 
          :to="'/school'"
          class="badge badge-warning"
          custom
      v-slot="{ navigate }"
          > <button  
          class="badge badge-primary mr-2" 
          @click="navigate"  
        role="link"
        >Back</button>
      </router-link
        >   
    <p>{{ message }}</p>
  </div>

  <div v-else>
    <br />
    <p>Please click on a Tutorial...</p>
  </div>
</template>
<style src="vue-multiselect/dist/vue-multiselect.min.css">
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
