// harsha/School-Teacher-Student/client-ReactJS/src/components/student/edit-student.component.tsx
import { ChangeEvent, Component } from "react";
import SchoolService from "../../services/school.service";
import StudentService from "../../services/student.service";
import { Link, RouteComponentProps } from "react-router-dom";
import { School } from "../../types/school.type";
import { Student } from "../../types/student.type";
import Multiselect from "multiselect-react-dropdown";

interface RouterProps {
  // type for `match.params`
  id: string; // must be type `string` since value comes from the URL
}

type Props = RouteComponentProps<RouterProps>;

type State = {
  currentStudent: Student;
  schools: Array<School>;
};

const genders = [{ value: "Male" }, { value: "Female" }];

export default class EditStudent extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeName = this.onChangeName.bind(this);
    this.onChangeAddress = this.onChangeAddress.bind(this);
    this.onChangeGender = this.onChangeGender.bind(this);
    this.onChangeDateOfBirth = this.onChangeDateOfBirth.bind(this);
    this.onChangeEmail = this.onChangeEmail.bind(this);
    this.onChangePhoneNo = this.onChangePhoneNo.bind(this);
    this.onChangeSchools = this.onChangeSchools.bind(this);
    this.getStudent = this.getStudent.bind(this);
    this.updateStudent = this.updateStudent.bind(this);

    this.state = {
      currentStudent: {
        studentId: null,
        studentName: "",
        address: "",
        gender: "",
        email: "",
        school: {
          schoolName: "",
        },
      },
      schools: [],
    };
  }

  componentDidMount() {
    this.getStudent(this.props.match.params.id);
    this.retrieveSchools();
  }

  onChangeName(e: ChangeEvent<HTMLInputElement>) {
    const teacherName = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          teacherName: teacherName,
        },
      };
    });
  }

  onChangeAddress(e: ChangeEvent<HTMLInputElement>) {
    const address = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          address: address,
        },
      };
    });
  }

  onChangeGender(e: ChangeEvent<HTMLInputElement>) {
    const gender = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          gender: gender,
        },
      };
    });
  }

  onChangeDateOfBirth(e: ChangeEvent<HTMLInputElement>) {
    const dateOfBirth = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          dateOfBirth: dateOfBirth,
        },
      };
    });
  }

  onChangeEmail(e: ChangeEvent<HTMLInputElement>) {
    const email = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          email: email,
        },
      };
    });
  }

  onChangePhoneNo(e: ChangeEvent<HTMLInputElement>) {
    const phoneNo = e.target.valueAsNumber;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          phoneNo: phoneNo,
        },
      };
    });
  }

  onChangeSchools(e: any) {
    const schools = e.target.value;

    this.setState(function (prevState) {
      return {
        currentStudent: {
          ...prevState.currentStudent,
          schools: schools,
        },
      };
    });
  }

  retrieveSchools() {
    SchoolService.getSchools()
      .then((response: any) => {
        this.setState({
          schools: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  getStudent(id: string) {
    StudentService.get(id)
      .then((response: any) => {
        this.setState({
          currentStudent: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  updateStudent() {
    StudentService.update(
      this.state.currentStudent,
      this.state.currentStudent.studentId
    )
      .then((response: any) => {
        console.log(response.data);
        this.props.history.push("/teachers");
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { currentStudent, schools } = this.state;

    return (
      <div className="edit-form">
        <h2>EDIT STUDENT</h2>
        <form>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              required
              value={currentStudent.studentName}
              onChange={this.onChangeName}
              name="name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Address</label>
            <input
              type="text"
              className="form-control"
              id="address"
              required
              value={currentStudent.address}
              onChange={this.onChangeAddress}
              name="address"
            />
          </div>

          <div className="form-group">Select a Gender</div>
          <label>
            <input
              type="radio"
              name="gender"
              value={currentStudent.gender}
              checked={currentStudent.gender}
              onChange={this.onChangeGender}
            />
            {currentStudent.gender}
          </label>

          <div className="form-group">
            <label htmlFor="date">DOB</label>
            <input
              type="date"
              className="form-control"
              value={currentStudent.dateOfBirth}
              onChange={this.onChangeDateOfBirth}
              name="date"
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              type="text"
              className="form-control"
              id="email"
              required
              value={currentStudent.email}
              onChange={this.onChangeEmail}
              name="email"
            />
          </div>

          <div className="form-group">
            <label htmlFor="phoneNo">Phone No</label>
            <input
              type="number"
              className="form-control"
              id="phoneNo"
              required
              value={currentStudent.phoneNo}
              onChange={this.onChangePhoneNo}
              name="phoneNo"
            />
          </div>

          <div className="form-group">
            <select>
              <option value="">Select School</option>
              {/* {schools.map((school) => ( */}
                <option
                //   key={school.schoolId}
                  typeof="checked"
                  selected={true}
                  value={currentStudent.school?.schoolName}
                  onChange={this.onChangeSchools}
                >
                  {currentStudent.school?.schoolName}
                </option>
                {/* ))} */}
            </select>
          </div>

          <button
            onClick={this.updateStudent}
            type="button"
            className="btn btn-success"
          >
            Update
          </button>
          <Link to="/students">
            <button type="button" className="btn btn-warning">
              Cancel
            </button>
          </Link>
        </form>
      </div>
    );
  }
}

// adarsh/school/VUE-client/src/components/EditStudent.vue
<script lang="ts">/* eslint-disable */
import { defineComponent } from "vue";
import studentservice from "@/services/studentservice";
import { Student } from "@/types/student";
import ResponseData from "@/types/ResponseData";
import School from "@/types/school";
export default defineComponent({

  name: "edit-student",
  data() {
    return {
      currentStudent: {} as Student,
      message: "",  
      schoolList: [] as School[],
      currentSchool: {} as School,
    };
  },
  methods: {
    getStudentById(id: any) {
      studentservice
        .getStudent(id)
        .then((response: ResponseData) => {
          this.currentStudent = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    retrieveSchools() {
      studentservice
        .getAllSchools()
        .then((response: ResponseData) => {
          this.schoolList = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
    onSchoolSelect(event:any) { 
      const src = event.target.value;
      const data = this.schoolList.filter((s) => s.id === +src);
     this.currentSchool = data[0];
     console.log(this.currentSchool);
    },
    updateStudent() {
        studentservice.updateStudent(this.currentStudent.id,this.currentStudent)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.message = "The student was updated successfully!";
        })
        .catch((e: Error) => {
          console.log(e);
        });       
    },
  //   deleteStudent() {
  //     studentservice.deleteStudent(this.currentStudent.studentid)
  //       .then((response: ResponseData) => {
  //         console.log(response.data);
  //         this.$router.push({ name: "studentlist" });
  //       })
  //       .catch((e: Error) => {
  //         console.log(e);
  //       });
  //   }, 
  // },
  mounted() {
    this.message = "";
    this.getStudentById(this.$route.params.id);
    this.retrieveSchools()
  },
  }
});
</script>
<template>
  <div v-if="currentStudent.id" class="edit-form">
    <h4>Edit-Student</h4>
    <form>
      <div class="form-group">
        <label for="name">student name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          v-model="currentStudent.name"
        />
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <textarea
          class="form-control"
          id="address"
          required
          v-model="currentStudent.address"     
        ></textarea>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          v-model="currentStudent.email"
        />
      </div>
      <div class="form-group">
        <label for="phone">Phone-Number</label>
        <input
          type="text"
          class="form-control"
          id="phone"
          v-model="currentStudent.phone"
        />
      </div>
      <div class="form-group">
        <label for="gender">Gender</label>
        <input
          type="text"
          class="form-control"
          id="gender"
          v-model="currentStudent.gender"
        />
      </div>
      <label for="gender">Select Gender</label>      
      <div class="form-group">
  <input type="radio" id="male" value="male" v-model="currentStudent.gender">
  <label for="male">Male</label><br>
  <input type="radio" id="female" value="female" v-model="currentStudent.gender">
  <label for="female">Female</label><br>
  <input type="radio" id="others" value="others" v-model="currentStudent.gender"> 
  <label for="others">Others</label><br>
</div>
      <div class="form-group">
        <label for="dateOfBirth">Date of birth</label>
        <input
          type="Date"
          class="form-control"
          id="dateOfBirth"
          required
          v-model="currentStudent.dateOfBirth"
          name="dateOfBirth"
        />
      </div>
      <label for="schools">School List:-</label>
      <div
        class="col-md-6"
        v-for="(entry, index) in currentStudent.schools"
        :key="index"       
      >   
          {{ entry}}
      </div>
      <br />
      <div class="form-group">
        <label>School List: </label>      
        <select  v-model="currentStudent.school.id" @change="onSchoolSelect($event)">
          <option>Select School</option>
          <option           
            placeholder="select school"           
            v-for="(entry, index) in schoolList"
            :key="index"
            :value="entry.id"
          >
            {{ entry.name }}
          </option>
        </select>
      </div>  
    </form>
    <button class="badge badge-danger mr-2" @click="deleteStudent">Delete</button>

    <button type="submit" class="badge badge-success mr-2" @click="updateStudent()">Update</button>

    <router-link 
          :to="'/studentlist'"
          class="badge badge-warning"
          custom
      v-slot="{ navigate }"
          > <button  
          class="badge badge-primary mr-2" 
          @click="navigate"  
        role="link"
        >Back</button>
      </router-link
        >   
    <p>{{ message }}</p>
  </div>

  <div v-else>
    <br />
    <p>Please click on a Tutorial...</p>
  </div>
</template>
<style>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>
