// harsha/School-Teacher-Student/client-ReactJS/src/components/student-list.component.tsx
import { Component } from "react";
import StudentService from "../services/student.service";
import { Link } from "react-router-dom";
import { Student } from "../types/student.type";

type Props = {};

type State = {
  students: Array<Student>;
};

export default class StudentsList extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.retrieveStudents = this.retrieveStudents.bind(this);

    this.state = {
      students: [],
    };
  }

  componentDidMount() {
    this.retrieveStudents();
  }

  retrieveStudents() {
    StudentService.getStudents()
      .then((response: any) => {
        this.setState({
          students: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { students } = this.state;

    return (
      <>
        <div>
          <Link to={"/add-student"}>
            <button type="button" className="btn btn-success">
              Add Student
            </button>
          </Link>
        </div>
        <h4>Students List</h4>
        <div className="list row">
          <div className="col-md-6">
            <table className="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Address</th>
                  <th>Gender</th>
                  <th>DOB</th>
                  <th>Email</th>
                  <th>Created Date</th>
                  <th>Phone No</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {students.map((student: Student) => {
                  return (
                    <tr key={student.studentId}>
                      <td>{student.studentId}</td>
                      <td>{student.studentName}</td>
                      <td>{student.address}</td>
                      <td>{student.gender}</td>
                      <td>{student.dateOfBirth}</td>
                      <td>{student.email}</td>
                      <td>{student.createdDate}</td>
                      <td>{student.phoneNo}</td>
                      <td>
                        {
                          <Link to={"/edit-student"}>
                            <button type="button" className="btn btn-primary">
                              Edit
                            </button>
                          </Link>
                        }
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </>
    );
  }
}

// adarsh/school/VUE-client/src/components/StudentList.vue
<template>
  <div class="list row">
    <div class="col-md-8"></div>
    <div class="col-md-6">
      <h4 v-size="'big'">Student List</h4>
      <ul class="list-group"></ul>
      <td>
        <input
          value="Add"
          @click="createStudent"
          class="btn float-right btn-primary"
        />
      </td>
      <br />
    </div>
    <br />
    <div class="container">
      <table class="table table-bordered justify-content-center">
        <thead class="thead-light">
          <tr class="active">
            <th class="text-center" scope="col">NAME</th>
            <th class="text-center" scope="col">ADRESS</th>
            <th class="text-center" scope="col">EMAIL</th>
            <th class="text-center" scope="col">GENDER</th>
            <th class="text-center" scope="col">DATA</th>
            <th class="text-center" scope="col">EDIT</th>
          </tr>
        </thead>
        <tbody v-for="(student, index) in students" :key="index">
          <tr class="success">
            <th class="text-center" scope="row">{{ student.name }}</th>
            <th class="text-center" scope="row">{{ student.address }}</th>
            <th class="text-center" scope="row">{{ student.email }}</th>
            <th class="text-center" scope="row">{{ student.gender }}</th>
            <th class="text-center" scope="row">{{ student.dateOfBirth }}</th>

            <th class="text-center" scope="row">
              <router-link
                :to="'/students/' + student.id"
                class="badge badge-warning"
                custom
                v-slot="{ navigate }"
              >
                <button
                  type="button"
                  class="btn btn-info btn-sm mr-2"
                  @click="navigate"
                  role="link"
                >
                  EDIT
                </button>
              </router-link>
            </th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { School } from "@/types/school";
import SchoolService from "@/services/SchoolService";
import { Student } from "@/types/student";

@Component
export default class StudentList extends Vue {
  students: Student[] = [];
  newStudent: Student = {
    name: "",
    address: "",
    email: "",
    gender: "",
    dateOfBirth: "",
    schools: {},
  };
  private currentIndex: number = -1;
  private title: string = "";
  searchStudent: Student[] = [];

  retrieveStudent() {
    SchoolService.getAllStudents()
      .then((response) => {
        this.students = response.data;
        this.searchStudent = this.students;
      })
      .catch((e) => {});
  }
  createStudent() {
    this.$router.replace("/studentsAdd");
  }
  addName() {
    console.log("adarsh");
  }
  mounted() {
    this.retrieveStudent();
  }
}
</script>

<style scoped>
.list {
  text-align: left;
  max-width: 750px;
  margin: auto;
}
</style>
