// harsha/School-Teacher-Student/client-ReactJS/src/App.tsx
import { Component } from "react";
import { Switch, Route, Link } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import "./App.css";

import SchoolsList from "./components/school-list.component";
import TeachersList from "./components/teacher-list.component";
import StudentsList from "./components/student-list.component";

class App extends Component {
  render() {
    return (
      <div>
        <nav className="navbar navbar-expand navbar-dark bg-dark">
          <div className="navbar-nav mr-auto">
            <li className="nav-item">
              <Link to={"/schools"} className="nav-link">
                Schools
              </Link>
            </li>
            <li className="nav-item">
              <Link to={"/teachers"} className="nav-link">
                Teachers
              </Link>
            </li>
            <li className="nav-item">
              <Link to={"/students"} className="nav-link">
                Students
              </Link>
            </li>
          </div>
        </nav>

        <div className="container mt-3">
          <Switch>
            <Route exact path={["/", "/schools"]} component={SchoolsList} />
            <Route exact path= "/teachers" component={TeachersList} />
            <Route exact path= "/students" component={StudentsList} />
          </Switch>
        </div>
      </div>
    );
  }
}

export default App;

// Shubhankar/School/client vuejs/src/App.vue
<!-- eslint-disable prettier/prettier -->
<template>
  <div id="app">
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <router-link to="/" class="navbar-brand">SchoolManagement</router-link>
      <div class="navbar-nav mr-auto">
       <li class="nav-item">
          <router-link to="/school" class="nav-link">School</router-link>
        </li>
         <li class="nav-item">
          <router-link to="/teacher" class="nav-link">Teacher</router-link>
        </li>  
        <li class="nav-item">
          <router-link to="/student" class="nav-link">Student</router-link>
        </li> 
    </div>
    </nav>
    <div class="container mt-3">
      <router-view />
    </div>
  </div>
    
</template>

<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "App",
  
});
</script>
