// Shubhankar/School/client vuejs/src/components/CreateTeacher.vue
<!-- eslint-disable prettier/prettier -->
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="teachername">Name</label>
        <input
          type="text"
          class="form-control"
          id="teachername"
          required
          v-model="teacher.teachername"
          name="teachername"
        />
      </div>

      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="teacher.address"
          name="address"
        />
      </div>

      <div class="form-group">
        <label for="phonenumber">Contact</label>
        <input
          type="text"
          class="form-control"
          id="phonenumber"
          required
          v-model="teacher.phonenumber"
          name="phonenumber"
        />
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          required
          v-model="teacher.email"
          name="email"
        />
      </div>

      <div class="form-group">
        <label for="gender">Gender</label><br />
        <input type="radio" id="Male" value="Male" v-model="picked" />
        <label for="Male">Male</label><br />
        <input type="radio" id="Female" value="Female" v-model="picked" />
        <label for="Female">Female</label><br />
        <input type="radio" id="Others" value="Others" v-model="picked" />
        <label for="Female">Others</label><br />
        <span>Picked: {{ picked }}</span
        ><br />
      </div>

      <div class="form-group">
        <label for="schools">Select School</label><br />
        <ul class="object administrator-checkbox-list">
          <li
            :class="{ active: index == currentIndex }"
            v-for="(school, index) in schools"
            :key="index"
          >
            <label v-bind:for="school.schoolid">
              <div>
                <input
                  type="checkbox"
                  v-model="selectedSchool"
                  v-bind:value="school"
                />
                <span>{{ school.schoolname }}</span>
              </div>
            </label>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <button @click="saveTeacher" class="btn btn-success">Submit</button>
  <button @click="listingPage" class="btn btn-danger">Cancel</button>
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import ResponseData from "@/types/ResponseData";
import Teacher from "@/types/Teacher";
import TeacherService from "@/services/TeacherService";
import SchoolService from "@/services/SchoolService";
import School from "@/types/School";

export default defineComponent({
  name: "teacher",

  data() {
    return {
      schools: [] as School[],
      selectedSchool: [],
      currentSchool: {} as School,
      teacher: {
        teachername: "",
        address: "",
        email: "",
        gender: "",
      } as Teacher,
      submitted: false,
      picked: "",
    };
  },

  methods: {
    saveTeacher() {
      let data = {
        teacherid: this.teacher.teacherid,
        teachername: this.teacher.teachername,
        address: this.teacher.address,
        phonenumber: this.teacher.phonenumber,
        email: this.teacher.email,
        gender: this.picked,
        schools: this.selectedSchool,
      };

      TeacherService.createTeacher(data)
         this.submitted = true;    
    },
    retrieveSchools() {
      SchoolService.getAllSchool()
        .then((response) => {
          this.schools = response.data;
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    listingPage() {
      this.$router.replace("/teacher");
    },
  },

  mounted() {
    this.saveTeacher();
    this.retrieveSchools();
  },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// Shubhankar/School/client/src/app/components/createteacher/createteacher.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { School } from 'src/app/models/school';
import { Teacher } from 'src/app/models/teacher';
import { SchoolService } from 'src/app/services/school.service';

@Component({
  selector: 'app-createteacher',
  templateUrl: './createteacher.component.html',
  styleUrls: ['./createteacher.component.css'],
})
export class CreateteacherComponent implements OnInit {
  createTeacher!: FormGroup;
  submitted: boolean = false;
  teacher: Teacher = {
    teachername: '',
    address: '',
    phonenumber: '',
    email: '',
    gender: '',
    schools: [],
  };

  id?: number;
  isAddMode?: boolean;

  schools: School[] = [];
  currentSchool: School = {};
  selectedSchool: School[] = [];

  constructor(
    private schoolService: SchoolService,
    private router: Router,
    private formBuilder: FormBuilder,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.createTeacher = this.formBuilder.group({
      teachername: ['', Validators.required],
      address: ['', Validators.required],
      phonenumber: ['', Validators.required],
      email: ['', Validators.required],
      gender: ['', Validators.required],
      schools:['', Validators.required],
    });
    this.retrieveSchool();
    this.retrieveTeacher(this.route.snapshot.params.id);

    this.id = this.route.snapshot.params['id'];
    this.isAddMode = !this.id;
  }

  async retrieveSchool(): Promise<void> {
    this.schools = await this.schoolService.getallSchoolRecords();
  }

   async selectedSchoolRecord(school: School): Promise<void> {
    this.currentSchool = school;
    this.selectedSchool?.push(this.currentSchool);
  }

  get fval() {
    return this.createTeacher.controls;
  }
 
  async saveTeacher() {
    this.submitted = true;
    if (this.createTeacher.invalid) {
      return;
    }
    this.getSubmit();
  }

  async getSubmit() {
    this.submitted = true;
    const teacherinfo: Teacher = {
      teachername: this.teacher.teachername,
      address: this.teacher.address,
      phonenumber: this.teacher.phonenumber,
      email: this.teacher.email,
      gender: this.teacher.gender,
      schools: this.selectedSchool,
    };
    await this.schoolService.createTeacher(teacherinfo);
    this.router.navigate(['/teacher-list']);
  }

  getBack() {
    this.router.navigate(['/teacher-list']);
  }

  async retrieveTeacher(id: number): Promise<void> {
    this.teacher = await this.schoolService.getTeacherbyid(id);
  }

  async updateTeacher() {
    this.submitted = true;
    if (this.createTeacher.invalid) {
      return;
    }
    this.getUpdated();
  }

  async getUpdated() {
    this.submitted = true;
    const teacherinfo: Teacher = {
      teacherid: this.teacher.teacherid,
      teachername: this.teacher.teachername,
      address: this.teacher.address,
      phonenumber: this.teacher.phonenumber,
      email: this.teacher.email,
      gender: this.teacher.gender,
      schools: this.selectedSchool,
    };
    await this.schoolService.updateTeacher(teacherinfo);
    this.router.navigate(['/teacher-list']);
  }

  async selectedSchools(school: string) {
    console.log(school);
    const data = this.schools.filter((s) => s.schoolid === +school);
    this.currentSchool = data[0];
  }
}

<div class="row">
  <div class="col-md-4 offset-md-3 col-md-6 col-sm-offset-2 col-sm-8">
    <h4 *ngIf="isAddMode">Add Teacher</h4>
    <h4 *ngIf="!isAddMode">Edit Teacher</h4>
    <form [formGroup]="createTeacher" (ngSubmit)="updateTeacher()">
      <div class="form-group">
        <label for="teachername">TeacherName</label>
        <input
          type="teachername"
          class="form-control"
          id="teachername"
          formControlName="teachername"
          [(ngModel)]="teacher.teachername"
          [ngClass]="{ 'is-invalid': submitted && fval.teachername.errors }"
        />
        <div
          *ngIf="submitted && fval.teachername.errors"
          class="invalid-feedback"
        >
          <div *ngIf="fval.teachername.errors.required">
            Name Field is required
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <input
          type="address"
          class="form-control"
          id="address"
          formControlName="address"
          [(ngModel)]="teacher.address"
          [ngClass]="{ 'is-invalid': submitted && fval.address.errors }"
        />
        <div *ngIf="submitted && fval.address.errors" class="invalid-feedback">
          <div *ngIf="fval.address.errors.required">
            Address Field is required
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="phonenumber">Contact</label>
        <input
          type="phonenumber"
          class="form-control"
          id="phonenumber"
          formControlName="phonenumber"
          [(ngModel)]="teacher.phonenumber"
          [ngClass]="{ 'is-invalid': submitted && fval.phonenumber.errors }"
        />
        <div
          *ngIf="submitted && fval.phonenumber.errors"
          class="invalid-feedback"
        >
          <div *ngIf="fval.phonenumber.errors.required">
            Contact Field is required
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="email"
          class="form-control"
          id="email"
          formControlName="email"
          [(ngModel)]="teacher.email"
          [ngClass]="{ 'is-invalid': submitted && fval.email.errors }"
        />
        <div *ngIf="submitted && fval.email.errors" class="invalid-feedback">
          <div *ngIf="fval.email.errors.required">Email Field is required</div>
        </div>
      </div>
      <div class="form-group">
        <label for="gender">Gender</label>
        <input
          type="gender"
          class="form-control"
          id="gender"
          formControlName="gender"
          [(ngModel)]="teacher.gender"
          [ngClass]="{ 'is-invalid': submitted && fval.gender.errors }"
        />
        <div *ngIf="submitted && fval.gender.errors" class="invalid-feedback">
          <div *ngIf="fval.gender.errors.required">
            Gender Field is required
          </div>
        </div>
      </div>
     <div class="column">
        <label>Select School</label>
        <div *ngFor="let school of schools">
          <input
            type="checkbox"
            (click)="selectedSchoolRecord(school)"
            [ngClass]="{ 'is-invalid': submitted && fval.schools.errors }"
            id="schools"
            name="schools"
            formControlName="schools"
           
          />{{ school.schoolname }}
          <div *ngIf="submitted && fval.schools.errors" class="invalid-feedback">
            <div *ngIf="fval.schools.errors.required">
              Schools Field is required
            </div>
          </div>
          </div>
     </div>
     

      <button  *ngIf="isAddMode"
      type="button"
      class="btn btn-outline-success"
      (click)="saveTeacher()"
    >
      Save
    </button>

      <button *ngIf="!isAddMode"
        type="button"
        class="btn btn-outline-success"
        (click)="updateTeacher()"
      >
        Update
      </button>
      <button type="button" class="btn btn-outline-danger" (click)="getBack()">
        Cancel
      </button>
    </form>
  </div>
</div>
