// harsha/School-Teacher-Student/client-ReactJS/src/components/teacher/teacher-list.component.tsx
import { Component } from "react";
import TeacherService from "../../services/teacher.service";
import { Link } from "react-router-dom";
import { Teacher } from "../../types/teacher.type";

type Props = {};

type State = {
  teachers: Array<Teacher>;
};

export default class TeachersList extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.retrieveTeachers = this.retrieveTeachers.bind(this);

    this.state = {
      teachers: [],
    };
  }

  componentDidMount() {
    this.retrieveTeachers();
  }

  retrieveTeachers() {
    TeacherService.getTeachers()
      .then((response: any) => {
        this.setState({
          teachers: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { teachers } = this.state;

    return (
      <>
        <div>
          <Link to={"/add-teacher"}>
            <button type="button" className="btn btn-success">
              Add Teacher
            </button>
          </Link>
        </div>
        <h4>Teachers List</h4>
        <div className="list row">
          <div className="col-md-8">
            <table className="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Address</th>
                  <th>Gender</th>
                  <th>Email</th>
                  <th>Created Date</th>
                  <th>Phone No</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {teachers.map((teacher: Teacher) => {
                  return (
                    <tr key={teacher.teacherId}>
                      <td>{teacher.teacherId}</td>
                      <td>{teacher.teacherName}</td>
                      <td>{teacher.address}</td>
                      <td>{teacher.gender}</td>
                      <td>{teacher.email}</td>
                      <td>{teacher.createdDate}</td>
                      <td>{teacher.phoneNo}</td>
                      <td>
                        {
                          <Link to={"/teachers/"+teacher.teacherId}>
                            <button type="button" className="btn btn-primary">
                              Edit
                            </button>
                          </Link>
                        }
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </>
    );
  }
}

// harsha/School-Teacher-Student/client/src/app/components/teacher-list/teacher-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Teacher } from 'src/app/models/teacher.model';
import { TeacherService } from 'src/app/services/teacher.service';

@Component({
  selector: 'app-teacher-list',
  templateUrl: './teacher-list.component.html',
  styleUrls: ['./teacher-list.component.css'],
})
export class TeacherListComponent implements OnInit {
  teachers: Teacher[] = [];

  constructor(private teacherService: TeacherService) {}

  ngOnInit(): void {
    this.getTeachers();
  }

  async getTeachers(): Promise<void> {
    this.teachers = await this.teacherService.getTeachers();
  }
}

<div class="panel">
  <div class="panel-heading">
    <div class="panel-body table-responsive">
      <h4 class="text-center">Teachers List</h4>
      <button class="btn btn-info" routerLink="/teacher">Add Teacher</button>
      <br /><br />
      <div>
        <table class="table table-bordered table-striped table-hover">
          <thead>
            <tr>
              <th class="text-center">Name</th>
              <th class="text-center">Gender</th>
              <th class="text-center">Address</th>
              <th class="text-center">Email</th>
              <th class="text-center">Phone No</th>
              <th class="text-center">Created Date</th>
              <th class="text-center">Action</th>
            </tr>
          </thead>
          <tbody *ngFor="let teacher of teachers; let i = index">
            <tr>
              <td class="text-center">{{ teacher.name }}</td>
              <td class="text-center">{{ teacher.gender }}</td>
              <td class="text-center">{{ teacher.address }}</td>
              <td class="text-center">{{ teacher.email }}</td>
              <td class="text-center">{{ teacher.phoneNo }}</td>
              <td class="text-center">{{ teacher.createdDate | date:'medium'}}</td>
              <td class="text-center">
                <button type="button" class="btn btn-info btn-space" routerLink="/teacher/{{ teacher.id }}">
                  Edit
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
