// adarsh/coustmer/client/src/app/app.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'Angular 12 Crud'
}

<div>
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <a href="#" class="navbar-brand">bezKoder</a>
    <div class="navbar-nav mr-auto">
      <li class="nav-item">
        <a routerLink="login" class="nav-link">Login</a>
      </li>
      <li class="nav-item">
        <a routerLink="customer" class="nav-link">Customer</a>
      </li>
      <li class="nav-item">
        <a routerLink="customergroup" class="nav-link">CustomerGroup</a>
      </li>
    </div>
  </nav>
  <div class="container mt-3">
    <router-outlet></router-outlet>
  </div>
</div>

// druthvik/Customers/client-reactjs/src/App.tsx
import { Component } from "react";
import { Switch, Route, Link } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import "./App.css";
import CustomerList from "./components/customerlisting.component";
import UploadImages from "./components/fileupload";

class App extends Component {
  render() {
    return (
      <div>
        <nav className="navbar navbar-expand navbar-dark bg-dark">
          <Link to={"/tutorials"} className="navbar-brand">
            bezKoder
          </Link>
          <div className="navbar-nav mr-auto"></div>
        </nav>

        <div className="container mt-3">
          <Switch>
            <Route exact path={["/", "/customer"]} component={CustomerList} />
            <Route path="/customerList" component={CustomerList} />
            <Route path="/upload" component={UploadImages} />
          </Switch>
        </div>
      </div>
    );
  }
}

export default App;
