// harsha/School-Teacher-Student/client-ReactJS/src/components/student-list.component.tsx
import { Component } from "react";
import StudentService from "../services/student.service";
import { Link } from "react-router-dom";
import { Student } from "../types/student.type";

type Props = {};

type State = {
  students: Array<Student>;
};

export default class StudentsList extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.retrieveStudents = this.retrieveStudents.bind(this);

    this.state = {
      students: [],
    };
  }

  componentDidMount() {
    this.retrieveStudents();
  }

  retrieveStudents() {
    StudentService.getStudents()
      .then((response: any) => {
        this.setState({
          students: response.data,
        });
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }

  render() {
    const { students } = this.state;

    return (
      <>
        <div>
          <Link to={"/add-student"}>
            <button type="button" className="btn btn-success">
              Add Student
            </button>
          </Link>
        </div>
        <h4>Students List</h4>
        <div className="list row">
          <div className="col-md-6">
            <table className="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Address</th>
                  <th>Gender</th>
                  <th>DOB</th>
                  <th>Email</th>
                  <th>Created Date</th>
                  <th>Phone No</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {students.map((student: Student) => {
                  return (
                    <tr key={student.studentId}>
                      <td>{student.studentId}</td>
                      <td>{student.studentName}</td>
                      <td>{student.address}</td>
                      <td>{student.gender}</td>
                      <td>{student.dateOfBirth}</td>
                      <td>{student.email}</td>
                      <td>{student.createdDate}</td>
                      <td>{student.phoneNo}</td>
                      <td>
                        {
                          <Link to={"/edit-student"}>
                            <button type="button" className="btn btn-primary">
                              Edit
                            </button>
                          </Link>
                        }
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </>
    );
  }
}

// harsha/School-Teacher-Student/client/src/app/components/student-list/student-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Student } from 'src/app/models/student.model';
import { StudentService } from 'src/app/services/student.service';

@Component({
  selector: 'app-student-list',
  templateUrl: './student-list.component.html',
  styleUrls: ['./student-list.component.css'],
})
export class StudentListComponent implements OnInit {
  students: Student[] = [];

  constructor(private studentService: StudentService) {}

  ngOnInit(): void {
    this.getStudents();
  }

  async getStudents(): Promise<void> {
    this.students = await this.studentService.getStudents();
  }
}

<div class="panel">
  <div class="panel-heading">
    <div class="panel-body table-responsive">
      <h4 class="text-center">Students List</h4>
      <button class="btn btn-info" routerLink="/student">Add Student</button>
      <br /><br />
      <div>
        <table class="table table-bordered table-striped table-hover">
          <thead>
            <tr>
              <th class="text-center">Name</th>
              <th class="text-center">Gender</th>
              <th class="text-center">Address</th>
              <th class="text-center">Date Of Birth</th>
              <th class="text-center">Email</th>
              <th class="text-center">Phone No</th>
              <th class="text-center">Created Date</th>
              <th class="text-center">Action</th>
            </tr>
          </thead>
          <tbody *ngFor="let student of students; let i = index">
            <tr>
              <td class="text-center">{{ student.name }}</td>
              <td class="text-center">{{ student.gender }}</td>
              <td class="text-center">{{ student.address }}</td>
              <td class="text-center">{{ student.dateOfBirth }}</td>
              <td class="text-center">{{ student.email }}</td>
              <td class="text-center">{{ student.phoneNo }}</td>
              <td class="text-center">{{ student.createdDate | date:'short'}}</td>
              <td class="text-center">
                <button type="button" class="btn btn-info btn-space" routerLink="/student/{{ student.id }}">
                  Edit
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
