// Shubhankar/School/client vuejs/src/components/CreateStudent.vue
<!-- eslint-disable prettier/prettier -->
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="studentname">Name</label>
        <input
          type="text"
          class="form-control"
          id="studentname"
          required
          v-model="student.studentname"
          name="studentname"
        />
      </div>
      <div class="form-group">
        <label for="address">Address</label>
        <input
          class="form-control"
          id="address"
          required
          v-model="student.address"
          name="address"
        />
      </div>
      <div class="form-group">
        <label for="phonenumber">Contact</label>
        <input
          type="text"
          class="form-control"
          id="phonenumber"
          required
          v-model="student.phonenumber"
          name="phonenumber"
        />
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          class="form-control"
          id="email"
          required
          v-model="student.email"
          name="email"
        />
      </div>

      <div class="form-group">
        <label for="gender">Gender</label>
        <input
          type="text"
          class="form-control"
          id="gender"
          required
          v-model="student.gender"
          name="gender"
        />
      </div>

      <div class="form-group">
        <label for="dateofbirth">Born </label>
        <input
          type="date"
          class="form-control"
          id="dateofbirth"
          required
          v-model="student.dateofbirth"
          name="dateofbirth"
        />
      </div>

     <div class="form-group">
        <label>School List: </label>
        <select  v-model="student.school" @change="onSchoolSelect($event)">
          <option>Select School</option>
          <option           
            placeholder="select school"           
            v-for="(school, index) in schools"
            :key="index"
            :value="school.schoolid"
          >
            {{ school.schoolname }}
          </option>
        </select>
      </div>


      <button @click="saveStudent" class="btn btn-success">Submit</button>
       <button @click="listingPage" class="btn btn-danger">Cancel</button>
    </div>
    </div>
</template>
<!-- eslint-disable prettier/prettier -->
<script lang="ts">
import { defineComponent } from "vue";
import Student from "@/types/Student";
import StudentService from "@/services/StudentService";
import SchoolService from "@/services/SchoolService";
import School from "@/types/School";

export default defineComponent({
  name: "student",

  data() {
    return {
     schools:  [] as School[],
      student: {
        studentname: "",
        address: "",
        email: "",
        gender: "",
        dateofbirth:"",
       } as Student,
      submitted: false,
      currentSchool: {} as School,
       
    };
  },
  
  methods: {
  async  saveStudent() {
      const data = {
        studentid: this.student.studentid,
        studentname: this.student.studentname,
        address: this.student.address,
        phonenumber: this.student.phonenumber,
        email: this.student.email,
        gender: this.student.gender,
        dateofbirth:this.student.dateofbirth,
        school:this.student.school,
     };

    await  StudentService.createStudent(data)
        .then((response) => {
          this.student.studentid = response.data.studentid;
          console.log(response.data);
          this.submitted = true;
           this.$router.replace('/student');
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

   listingPage(){
      this.$router.replace('/student');
    },

   retrieveSchools() {
      SchoolService.getAllSchool()
        .then((response) => {
          this.schools = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
 
   onSchoolSelect(event: Event) { 
      const src = (event.target as HTMLInputElement).value;
      const data = this.schools.filter((s) => s.schoolid === +src);
     this.currentSchool = data[0];
     console.log(this.currentSchool);
    },  
  },
  mounted() {
    this.saveStudent();
    this.retrieveSchools()
  },
});
</script>
<!-- eslint-disable prettier/prettier -->
<style>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// Shubhankar/School/client/src/app/components/createstudent/createstudent.component.ts
import {
  ChangeDetectorRef,
  Component,
  ElementRef,
  OnInit,
  ViewChild,
} from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Image } from 'src/app/models/image';
import { School } from 'src/app/models/school';

import { Student } from 'src/app/models/student';
import { Gender, SchoolService } from 'src/app/services/school.service';

@Component({
  selector: 'app-createstudent',
  templateUrl: './createstudent.component.html',
  styleUrls: ['./createstudent.component.css'],
})
export class CreatestudentComponent implements OnInit {
  id?: number;
  isAddMode?: boolean;
  createStudent!: FormGroup;
  submitted: boolean = false;
  currentGender!: string;
  genderlist: Gender[] = [];
  selectedGender!: any;

  selectedFiles?: Image;
  currentFile?: File;

  student: Student = {
    studentname: '',
    address: '',
    phonenumber: '',
    email: '',
    gender: '',
    dateofbirth: '',
    school: {},
  };

  schoolsList: School[] = [];
  currentSchool: School = {};

  schools: School[] = [];
  fileName = '';

  constructor(
    private schoolService: SchoolService,
    private router: Router,
    private formBuilder: FormBuilder,
    private route: ActivatedRoute,
    private cd: ChangeDetectorRef
  ) {}

  @ViewChild('fileInput') el: ElementRef | undefined;
  editFile = true;
  removeUpload = false;
  downloadFileName!: string;
  file!: File;
  progress?: number;

  ngOnInit(): void {
    this.createStudent = this.formBuilder.group({
      studentname: ['', Validators.required],
      address: ['', Validators.required],
      phonenumber: ['', Validators.required],
      email: ['',
        [
          Validators.required,
          Validators.email,
          Validators.pattern('^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$'),
        ],
      ],
      gender: ['', Validators.required],
      dateofbirth: ['', Validators.required],
      school: ['', Validators.required],
    });
    this.retriveGenders();
    this.retrieveSchool();
    this.retrieveStudentId(this.route.snapshot.params.id);

    this.id = this.route.snapshot.params['id'];
    this.isAddMode = !this.id;
  }

  async retrieveSchool(): Promise<void> {
    this.schoolsList = await this.schoolService.getallSchoolRecords();
    console.log(this.schools);
  }

  async retriveGenders(): Promise<void> {
    this.genderlist = await this.schoolService.genderList();
    console.log(this.genderlist);
  }

  get fval() {
    return this.createStudent.controls;
  }

  async create() {
    this.submitted = true;
    if (this.createStudent.invalid) {
      return;
    }
    this.getSubmit();
  }

  async getSubmit() {
    this.submitted = true;
    const studentinfo: Student = {
      studentname: this.student.studentname,
      address: this.student.address,
      phonenumber: this.student.phonenumber,
      email: this.student.email,
      gender: this.student.gender,
      file: this.selectedFiles,
      dateofbirth: this.student.dateofbirth,
      school: this.currentSchool,
    };
    await this.schoolService.createStudent(studentinfo);
    this.router.navigate(['student-list']);
  }

  getStudentGender(gender: Gender) {
    this.currentGender = gender.name;
  }

  private selectedLink: string = 'Male';

  setradio(e: string): void {
    this.selectedLink = e;
  }

  isSelected(name: string): boolean {
    if (!this.selectedLink) {
      return false;
    }

    return this.selectedLink === name;
  }

  onSelected(value: School) {
    this.student.school = value;
  }

  getBack() {
    this.router.navigate(['student-list']);
  }

  async retrieveStudentId(id: number): Promise<void> {
    this.student = await this.schoolService.getStudentbyid(id);
  }

  async update() {
    this.submitted = true;
    if (this.createStudent.invalid) {
      return;
    }
    this.getUpdated();
  }

  async getUpdated() {
    this.submitted = true;
    const studentinfo: Student = {
      studentid: this.student.studentid,
      studentname: this.student.studentname,
      address: this.student.address,
      phonenumber: this.student.phonenumber,
      email: this.student.email,
      gender: this.student.gender,
      file: this.selectedFiles,
      dateofbirth: this.student.dateofbirth,
      school: this.student.school,
    };
    await this.schoolService.updateStudent(studentinfo);
    this.router.navigate(['student-list']);
  }

  async uploadImage(): Promise<void> {
    this.schoolService.uploadFile(this.file);
  }

  chooseFile(event: any) {
    const reader = new FileReader();
    const file = event.target.files[0];
    this.file = file;
  }

  selectFile(event: any): void {
    this.selectedFiles = event.target.files;
  }

  uploadNewFile(): void {
    this.progress = 0;
    this.selectedFiles = this.selectedFiles && this.selectedFiles;
  }

  async selectedSchool(school: string) {
    console.log(school);
    const data = this.schoolsList.filter((s) => s.schoolid === +school);
    this.currentSchool = data[0];
  }
}

<div class="row">
  <div class="col-md-4 offset-md-3 col-md-6 col-sm-offset-2 col-sm-8">
    <h4 *ngIf="isAddMode">Add Student</h4>
    <h4 *ngIf="!isAddMode">Edit Student</h4>
    <form [formGroup]="createStudent" (ngSubmit)="create()">
      <div class="form-group">
        <label for="studentname">StudentName</label>
        <input
          type="studentname"
          class="form-control"
          id="studentname"
          formControlName="studentname"
          [(ngModel)]="student.studentname"
          [ngClass]="{ 'is-invalid': submitted && fval.studentname.errors }"
        />
        <div
          *ngIf="submitted && fval.studentname.errors"
          class="invalid-feedback"
        >
          <div *ngIf="fval.studentname.errors.required">
            Name Field is required
          </div>
        </div>
        <div class="form-group">
          <label for="address">Address</label>
          <input
            type="address"
            class="form-control"
            id="address"
            formControlName="address"
            [(ngModel)]="student.address"
            [ngClass]="{ 'is-invalid': submitted && fval.address.errors }"
          />
          <div
            *ngIf="submitted && fval.address.errors"
            class="invalid-feedback"
          >
            <div *ngIf="fval.address.errors.required">
              Address Field is required
            </div>
          </div>
          <div class="form-group">
            <label for="phonenumber">Contact</label>
            <input
              type="phonenumber"
              class="form-control"
              id="phonenumber"
              formControlName="phonenumber"
              [(ngModel)]="student.phonenumber"
              [ngClass]="{ 'is-invalid': submitted && fval.phonenumber.errors }"
            />
            <div
              *ngIf="submitted && fval.phonenumber.errors"
              class="invalid-feedback"
            >
              <div *ngIf="fval.phonenumber.errors.required">
                Contact Field is required
              </div>
            </div>
            <div class="form-group">
              <label for="email">Email</label>
              <input
                type="email"
                class="form-control"
                id="email"
                formControlName="email"
                [(ngModel)]="student.email"
                [ngClass]="{ 'is-invalid': submitted && fval.email.errors }"
              />
              <div
                *ngIf="submitted && fval.email.errors"
                class="invalid-feedback"
              >
                <div *ngIf="fval.email.errors.required">
                  Email Field is required
                </div>
              </div>
              <div class="form-group">
                <label for="gender">Gender</label>
                <div class="radio">
                  <label>
                    <input
                      type="radio"
                      name="gender"
                      id="gender"
                      formControlName="gender"
                      value="Male"
                      (click)="setradio('Male')"
                      [checked]="true"
                      [(ngModel)]="student.gender"
                      [ngClass]="{
                        'is-invalid': submitted && fval.gender.errors
                      }"
                    />
                    Male
                  </label>

                  <div class="radio">
                    <label>
                      <input
                        type="radio"
                        name="gender"
                        id="gender"
                        formControlName="gender"
                        value="Female"
                        (click)="setradio('Female')"
                        [(ngModel)]="student.gender"
                        [ngClass]="{
                          'is-invalid': submitted && fval.gender.errors
                        }"
                      />
                      Female
                    </label>
                  </div>

                  <div
                    *ngIf="submitted && fval.gender.errors"
                    class="invalid-feedback"
                  >
                    <div *ngIf="fval.gender.errors.required">
                      gender Field is required
                    </div>
                  </div>
                </div>

                <div class="row">
                  <label>
                    <input
                      type="file"
                      (change)="selectFile($event)"
                      (change)="uploadNewFile()"
                    />
                  </label>
                </div>
                <div class="form-group">
                  <label for="dateofbirth">Date Of Birth</label>
                   <input
                    type="date"
                    formControlName="dateofbirth"
                    class="form-control"
                    [(ngModel)]="student.dateofbirth"
                    [ngClass]="{
                      'is-invalid': submitted && fval.dateofbirth.errors
                    }"
                  />
                  <div
                    *ngIf="this.submitted && fval.dateofbirth.errors"
                    class="invalid-feedback"
                  >
                    <div *ngIf="fval.dateofbirth.errors.required">
                      Date Of Birth Field is required
                    </div>
                  </div>
                </div>
                  <div class="form-group">
                  <label for="school">School</label>
                  <select
                    class="form-control"
                    id="school"
                    formControlName="school"
                    required
                    [(ngModel)]="student.school && student.school.schoolid"
                    (ngModelChange)="selectedSchool($event)"
                    [ngClass]="{
                      'is-invalid': submitted && fval.school.errors
                    }"
                  >
                    <option
                      class="option"
                      *ngFor="let option of schoolsList"
                      [value]="option.schoolid"
                    >
                      {{ option.schoolname }}
                    </option>
                  </select>
                  <div
                    *ngIf="submitted && fval.school.errors"
                    class="invalid-feedback"
                  >
                    <div *ngIf="fval.school.errors.required">
                      School Field is required
                    </div>
                  </div>
                </div>
                <button
                  *ngIf="isAddMode"
                  type="button"
                  class="btn btn-outline-success"
                  (click)="create()"
                >
                  Save
                </button>

                <button
                  *ngIf="!isAddMode"
                  type="button"
                  class="btn btn-outline-success"
                  (click)="update()"
                >
                  Update
                </button>
                <button
                  type="button"
                  class="btn btn-outline-danger"
                  (click)="getBack()"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
