// shashi/student-task/vuejs/src/components/TutorialDetails.vue
/* eslint-disable */

<template>
  <div v-if="currentTutorial.id" class="edit-form">
    <h4>Tutorial</h4>
    <form>
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          v-model="currentTutorial.title"
        />
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <input
          type="text"
          class="form-control"
          id="description"
          v-model="currentTutorial.description"
        />
      </div>

      <div class="form-group">
        <label><strong>Status:</strong></label>
        {{ currentTutorial.published ? "Published" : "Pending" }}
      </div>
    </form>

    <button
      class="badge badge-primary mr-2"
      v-if="currentTutorial.published"
      @click="updatePublished(false)"
    >
      UnPublish
    </button>
    <button
      v-else
      class="badge badge-primary mr-2"
      @click="updatePublished(true)"
    >
      Publish
    </button>

    <button class="badge badge-danger mr-2" @click="deleteTutorial">
      Delete
    </button>

    <button type="submit" class="badge badge-success" @click="updateTutorial">
      Update
    </button>
    <p>{{ message }}</p>
  </div>

  <div v-else>
    <br />
    <p>Please click on a Tutorial...</p>
  </div>
</template>

<script lang="ts">
/* eslint-disable */
import { defineComponent } from "vue";
import TutorialDataService from "@/services/TutorialDataService";
import Tutorial from "@/types/Tutorial";
import ResponseData from "@/types/ResponseData";

export default defineComponent({
  name: "tutorial",
  data() {
    return {
      currentTutorial: {} as Tutorial,
      message: "",
    };
  },
  methods: {
    getTutorial(id: any) {
      TutorialDataService.get(id)
        .then((response: ResponseData) => {
          this.currentTutorial = response.data;
          console.log(response.data);
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    updatePublished(status: boolean) {
      let data = {
        id: this.currentTutorial.id,
        title: this.currentTutorial.title,
        description: this.currentTutorial.description,
        published: status,
      };

      TutorialDataService.update(this.currentTutorial.id, data)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.currentTutorial.published = status;
          this.message = "The status was updated successfully!";
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    updateTutorial() {
      TutorialDataService.update(this.currentTutorial.id, this.currentTutorial)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.message = "The tutorial was updated successfully!";
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },

    deleteTutorial() {
      TutorialDataService.delete(this.currentTutorial.id)
        .then((response: ResponseData) => {
          console.log(response.data);
          this.$router.push({ name: "tutorials" });
        })
        .catch((e: Error) => {
          console.log(e);
        });
    },
  },
  mounted() {
    this.message = "";
    this.getTutorial(this.$route.params.id);
  },
});
</script>

<style>
.edit-form {
  max-width: 300px;
  margin: auto;
}
</style>

// druthvik/tutorial/client/src/app/components/tutorial-details/tutorial-details.component.ts
import { Component, OnInit } from '@angular/core';
import { TutorialService } from 'src/app/services/tutorial.service';
import { ActivatedRoute, Router } from '@angular/router';
import { Tutorial } from 'src/app/models/tutorial.model';
import { Category } from 'src/app/models/category.model';

@Component({
  selector: 'app-tutorial-details',
  templateUrl: './tutorial-details.component.html',
  styleUrls: ['./tutorial-details.component.css'],
})
export class TutorialDetailsComponent implements OnInit {
  currentTutorial: Tutorial = {
    title: '',
    description: '',
    published: false,
    categories: [],
  };
  message = '';
  categories!: Category[];
  constructor(
    private tutorialService: TutorialService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.message = '';
    this.retriveCategory();
    this.getTutorialbyId(this.route.snapshot.params.id);
  }

  async retriveCategory(): Promise<void> {
    this.categories = await this.tutorialService.getAllCategory();
  }
  async getTutorialbyId(id: number) {
    this.currentTutorial = await this.tutorialService.getbyId(id);
  }

  updatePublished(status: boolean): void {
    const data = {
      title: this.currentTutorial.title,
      description: this.currentTutorial.description,
      published: status,
    };

    // this.message = '';
    // this.tutorialService.update(this.currentTutorial.id, data);

    // this.tutorialService.update(this.currentTutorial.id, data).subscribe(
    //   (response) => {
    //     this.currentTutorial.published = status;
    //     console.log(response);
    //     this.message = response.message
    //       ? response.message
    //       : 'This tutorial was updated successfully!';
    //   },
    //   (error) => {
    //     console.log(error);
    //   }
    // );
  }

  // updateTutorial(): void {
  //   this.message = '';

  //   this.tutorialService
  //     .update(this.currentTutorial.id, this.currentTutorial)
  //     .subscribe(
  //       (response) => {
  //         console.log(response);
  //         this.message = response.message
  //           ? response.message
  //           : 'This tutorial was updated successfully!';
  //       },
  //       (error) => {
  //         console.log(error);
  //       }
  //     );
  // }
  // updateTutorial() {
  //   this.message = '';

  //   this.tutorialService.update(this.currentTutorial.id, this.currentTutorial);
  // }

  // deleteTutorial() {
  //   this.tutorialService.delete(this.currentTutorial.id).subscribe(
  //     (response) => {
  //       this.router.navigate(['/tutorials']);
  //       console.log(response);
  //     },
  //     (error) => {
  //       console.log(error);
  //     }
  //   );
  //   this.router.navigate(['/tutorials']);
  // }

  async deletebyid() {
    await this.tutorialService.deletebyid(this.currentTutorial.id);
  }
}

<div>
  <div *ngIf="currentTutorial.id" class="edit-form">
    <h4>Tutorial</h4>
    <form>
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          [(ngModel)]="currentTutorial.title"
          name="title"
        />
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <input
          type="text"
          class="form-control"
          id="description"
          [(ngModel)]="currentTutorial.description"
          name="description"
        />
      </div>

      <div class="form-group">
        <label><strong>Status:</strong></label>
        {{ currentTutorial.published ? "Published" : "Pending" }}
      </div>
    </form>
    <div class="col-md-6">
      <select class="custom-select">
        [(ngModel)]="currentTutorial.categories
        <option *ngFor="let category of categories" [ngValue]="category">
          {{ category.title }}
        </option>
      </select>
      <br />
    </div>
    <br />

    <button
      class=""
      *ngIf="currentTutorial.published"
      (click)="updatePublished(false)"
    >
      UnPublish
    </button>
    <button
      *ngIf="!currentTutorial.published"
      class=""
      (click)="updatePublished(true)"
    >
      Publish
    </button>

    <button (click)="deletebyid()" routerLink="/tutorials">Delete</button>

    <!-- <button type="submit" class="" (click)="updateTutorial()">Update</button> -->
    <p>{{ message }}</p>
  </div>

  <div *ngIf="!currentTutorial.id">
    <br />
    <p>Cannot access this Tutorial...</p>
  </div>
</div>
