// druthvik/StudentManagement/client-reactjs/src/App.tsx
import { Component } from "react";
import { Switch, Route, Link } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import "./App.css";
import AddSchool from "./components/school/school.component";
import SchoolList from "./components/school/schoollist.component";
class App extends Component {
  render() {
    return (
      <div>
        <nav className="navbar navbar-expand navbar-dark bg-dark">
          <Link to={"/tutorials"} className="navbar-brand">
            bezKoder
          </Link>
          <div className="navbar-nav mr-auto">
            <li className="nav-item">
              <Link to={"/school"} className="nav-link">
                Add school
              </Link>
            </li>
            <li className="nav-item">
              <Link to={"/schoollist"} className="nav-link">
                School List
              </Link>
            </li>
          </div>
        </nav>

        <div className="container mt-3">
          <Switch>
            <Route exact path={["/", "/schoollist"]} component={SchoolList} />
            <Route path="/school" component={AddSchool} />
            <Route path="/schoollist" component={SchoolList} />
          </Switch>
        </div>
      </div>
    );
  }
}

export default App;

// druthvik/tutorial/client/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  constructor() {}
  ngOnInit(): void {}
  title = 'Angular 11 Crud';
}

<div>
  <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
    <a href="#" class="navbar-brand">bezKoder</a>
    <div class="navbar-nav mr-auto">
      <li class="nav-item">
        <a routerLink="LoginComponentComponent" class="nav-link">Login</a>
      </li>
      <li class="nav-item">
        <a routerLink="tutorials" class="nav-link">Tutorials</a>
      </li>
      <li class="nav-item">
        <a routerLink="add" class="nav-link">Add</a>
      </li>
      <li class="nav-item">
        <a routerLink="'tutorialform'" class="nav-link">TutorialForm</a>
      </li>
      <li class="nav-item">
        <a routerLink="validation" class="nav-link">validation</a>
      </li>
    </div>
  </nav>

  <div class="container mt-3">
    <router-outlet></router-outlet>
  </div>
</div>
